### ISSUE TITLE
no website anymore...figure out what to do.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1]
We had a website on sourceforge.net, but we moved here after that site has more or less died.
We had a web page area on sourceforge.net that allowed us to build custom web pages, which we did
using rst2html and the doc/ directory under the sarracenia repository.

So far, we are just linking into the sarracenia/doc repository, and letting links work, but it's... confusing.

on sf.net, there were some templates used to get menus and sidebars.  

Need to explore a bit figure out a path forward.

**Comment by nschonni** [comment]
https://help.github.com/articles/what-is-github-pages/
https://help.github.com/articles/user-organization-and-project-pages/
You can also keep the `docs` folder as your site https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

The pages are built off of https://jekyllrb.com/, but with a subset of whitelisted gems that can be found https://github.com/github/pages-gem

**Comment by petersilva** [comment]
What I did in the end:  re-worked pages to start with the README file in each repo, and link as a network of .rst's which are rendered automatically on github and gitlab.  so now any instance of repo mirroring with rst rendering provides website mirroring also.

publishing the website, or mirroring it, is only git push. (since we have internal mirrors on gitlab instances, this is great for us.)

Things done for this:
  - renamed some .txt files to .rst
 - added svg results of dia exports to the repo so image tags work in the repo.
 - re-worked the index on sf.net to refer to .rst's on github.

complete now.  OK until someone has a better idea.
