### ISSUE TITLE
report_exchange not declared...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#102]
if the configuration is not already writing to the same exchange for other reasons, the report_exchange will not be declared by the reporter, causing errors unless report_back is turned off.  Should include report_exchange declaration where necessary.

**Comment by petersilva** [comment]
@benlapETS if you are looking for a small thing to do that should be simpler to get done, this is a good candidate.  it's annoying to have to put ReportBack False in all the configurations. just need to check that setting in at the end for the settings (overwrite_default? somewhere like that) and pro-actively declare the exchange.

**Comment by michelgrenier** [comment]
deprecated : this comes from the old idea that sr_audit would be the one creating xl_USER (or xr_) and that would be The exchange for reporting for this user...

**Comment by petersilva** [comment]
the reportBack False being needed is a bug... the problem is that the proper exchange to receive the reports is not getting created... if it were, it would just silently work.

We just need the report publishing code to include declaring the exchange where necessary.
