### ISSUE TITLE
Search feature broken on documentation website

### ISSUE THREAD

**Issue by mshak2** [MetPX/sarracenia#1047]
When using the search bar here https://metpx.github.io/sarracenia/index.html, it loads forever.

**Comment by petersilva** [comment]
yeah... it originally worked (magically) then stopped (equally magically.) we just run sphinx on the tree. and github runs:

* https://github.com/MetPX/sarracenia/actions/workflows/docs.yml

Somebody needs to look at the logs and discover a complaint from sphinx or some such.

**Comment by petersilva** [comment]
fixed!
