### ISSUE TITLE
after_post runs even though nothing has been posted

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1066]
This causes a confusing log message saying

```
2024-05-03 02:30:44,644 [INFO] sarracenia.flowcb.log after_post posted to a file with baseUrl: http://example.com/ relPath: data/zps.202405030230.past_hourly.xml
```

If there are after_post plugins, it might also do unexpected things.

@petersilva already found the fix, just indent `self._runCallbacksWorklist('after_post') ` 4 characters so it is inside the if statement.

https://github.com/MetPX/sarracenia/blob/6ad476d5d1438bfa101f5754ed11fbc0cccd5b00/sarracenia/flow/__init__.py#L1125-L1141

**Comment by petersilva** [comment]
here is a healthy:
*after_post message  after post to **exchange: xwinnow00 topic: v03....** a file w*
```

after_post posted to exchange: xwinnow00 topic: v03.post.20240524.WXO-DD.model_gewps.25km.00 a file w

```
