### ISSUE TITLE
fileAgeMax doesn't work in all situations?

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1089]
I tried to use fileAgeMax in a sarra, where the incoming messages have mtime and atime headers. It didn't work. 

I think it's because fileAgeMax isn't implemented in gather.message? https://github.com/MetPX/sarracenia/blob/4ca61178718c7e4b8fc458faa6c9e65c5314cc37/sarracenia/flowcb/gather/message.py

I guess this is a feature request? I'm pretty sure it's not something that ever worked before, so not a bug.

**Comment by petersilva** [comment]
I have a patch for downloader... should I add support in the sender also?

**Comment by petersilva** [comment]
in order to implement fileAgeMinTime... would have to add a *deferred* worklist... and move stuff that is too young to that.
is that worthwhile... or should just discard stuff that is too young?

**Comment by petersilva** [comment]
fileAgeMax is implemented in nodupe.  I guess you don't have nodupe active?

**Comment by petersilva** [comment]
I went with 410 ... suggestions? https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

**Comment by reidsunderland** [comment]
No, nodupe is not active in the config where I want to use fileAgeMax. I want to allow duplicates, but not files that are too old.

I thought that fileAgeMax was originally implemented in nodupe, but then it was added to gather.file so it would work in a watch (even without nodupe, but I could be wrong?). https://github.com/MetPX/sarracenia/pull/926. That's why I was assuming we needed a matching implementation in gather.message.

Yes, having fileAgeMax work in both downloading and sending would be good. 

---

I didn't consider fileAgeMin. I don't think fileAgeMin is very useful in a sender or downloader. But it's probably good to have for completeness. I'm okay with discarding files/messages that are too young, at least as the first implementation and could be improved later. 

Adding a deferred worklist sounds like a good idea for the future. We already have waiting logic implemented in gather.file (for inflight/fileAgeMin), but it's just in memory. That could potentially be a source of data loss if a watch is stopped while it's waiting for something to become old enough to post. I think a deferred worklist might have the same risk of message loss, so we'd need to figure out what to do when stopping a config (write to disk, don't stop until the deferred worklist is empty?).

**Comment by petersilva** [comment]
we could deal with fileAgeMin by putting underage file on the "failed" queue, so they get retried later (one housekeeping interval later, at minimum.)  the retry queues is persisted reliably, so it would plug that vulnerability.  the difference would be instead of failing it at gather time, we do it in filter, where multiple worklists are available.

**Comment by petersilva** [comment]
fwiw... I patch I have... it breaks the static_flow test... mystery for now is why no PR.

**Comment by reidsunderland** [comment]
I think there's a small bug in the implementation of this. 

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 249, in <module>
    i.start()
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 240, in start
    self.running_instance.run()
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 592, in run
    self.filter()
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 995, in filter
    self.reject( m, 410, f"file too old: {age:g} sec. skipping: {m['new_file']}, ")
KeyError: 'new_file'
```

Maybe we should use relPath instead of new_file?

**Comment by petersilva** [comment]
good idea! Perhaps replace both occurrences?
