### ISSUE TITLE
Issue with has_vip routine 

### ISSUE THREAD

**Issue by habilinour** [MetPX/sarracenia#110]
I'm running 2.18.05b2 on Ubuntu 16.04 and I found an issue with has_vip  routine  which seems not to  return  all VIPs associated with a network interface.

**Comment by petersilva** [comment]
is is has_vip requires a third level of looping over addresses bound to a single interface.
Current version only loops over interfaces and checks the first address it finds.

**Comment by petersilva** [comment]
commit 355f1d74ee1c7b36fcb7301226efa71237e58e6c fixes this.

**Comment by petersilva** [comment]
released in 2.18.11
