### ISSUE TITLE
Queued column never updates

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1127]
We had to disable queue updating to fix a data flow corruption issue.
The work-around for #953 is to disable queue count updating.

**Comment by petersilva** [comment]
Since original queue declare calls caused mayhem (aka data loss) perhaps we can, more rarely, close the message connection.  When it auto-reopens it, it will cause the queued number to be updated.   suggestion would be to do this every housekeeping interval.  worries:
* message acks' don't survive close/open, if any thing is pending, that would be bad.   
* the housekeeping logic is called where (barring major issues) there should be no messages waiting for ack... so it's a very goot time to do that.

**Comment by reidsunderland** [comment]
fixed by #1160.
