### ISSUE TITLE
Option to log when a message is rejected because it's a duplicate, but not for any other reason

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1156]
Right now, we have the `logReject` option (which adds `reject` to the `logEvents`). We can turn this on to see why messages are rejected. 

But in cases where messages are rejected because they're duplicates, it would be nice to see that in the logs, without logging rejections for any other reasons. 

We could add a new option, maybe `logReject_duplicate` to turn on logging duplicates.

It should just take a couple changes in this area: https://github.com/MetPX/sarracenia/blob/301519e6edf0c4288f8fc2fbe25208a7d50d12e3/sarracenia/flowcb/log.py#L143-L150

to check for the new option and check if the report message contains nodupe?

https://github.com/MetPX/sarracenia/blob/301519e6edf0c4288f8fc2fbe25208a7d50d12e3/sarracenia/flowcb/nodupe/disk.py#L160-L174

v2 winnows would do this, and @junhu3 wants the same in sr3. I think it would be good to have this new option enabled by default in winnows.

Maybe @mshak2 has time to look at this one?

**Comment by reidsunderland** [comment]
I also see this inconsistency, I think maybe the cache check should be changed to nodupe check but I'm not sure if it was left as cache (from v2) for a specific reason:

https://github.com/MetPX/sarracenia/blob/301519e6edf0c4288f8fc2fbe25208a7d50d12e3/sarracenia/flowcb/nodupe/disk.py#L178-L182

**Comment by petersilva** [comment]
uh... logDuplicates as a flag?

**Comment by reidsunderland** [comment]
yeah that works too, i said `logReject_duplicates` because I thought of it as kind of a logReject subset option, but it doesn't matter to me what the option is called

**Comment by petersilva** [comment]
* logDuplicates ... add to flags in config.py.. default to False. (or add an event to logEvents.

* modify flowcb/log.py to honour...
   * there are multiple places where duplicates get refused... gotta check them all...
   * can check msg['report']['code'] == 304.
   * some fixes needed to flowcb/nodupe/disk.py (perhaps redis as well... )
   * fix typos modififi, cache vs. nodupe
   * some 304's are not always right... "too new" should become 425.
   * too old is also 304 ... should be ... 406 ... not acceptable.

**Comment by petersilva** [comment]
question: do we want to tack on the the other improvements to log to this issue?
* log sundew_extension if present.
* log first seven (based on git example) chars of identity value, like so "id: ab13f12"  
* log size.

to ... post?   or accept, or both?

**Comment by reidsunderland** [comment]
I created a separate issue for that, https://github.com/MetPX/sarracenia/issues/1195

**Comment by petersilva** [comment]
I'm wondering if we should have a "logReject" as a set argument, where the elements are the codes... so you can tune "which rejects" you want.

**Comment by reidsunderland** [comment]
I like that idea. Could we have some "shortcuts" that still let us turn on everything and would be backwards compatible with existing configs? So `logReject true/on` still works?

Or maybe the set option should be new, like `logRejectCodes` and `logReject` could remain as a flag option that works by adding all the possible codes to logRejectCodes?

**Comment by petersilva** [comment]
maybe as simple as logReportCode with the report codes as members of the set.
keep the other options untouched... or have them set logReportCode set appropriately.
could control logging of success and rejects with one option.

**Comment by reidsunderland** [comment]
logReportCode sounds good. 

Having the other options (logReject and logDuplicates) add codes to the logReportCode set seems like a good idea too.

Right now there's code in flowcb/log.py to check if reject is in logEvents, and that's how logDuplicates was implemented (check if nodupe is in logEvents). Implementing those options using logReportCode removes those two cases from flowcb/log and simplifies it to a standard check of report codes. I think that makes log.py a little bit simpler.
