### ISSUE TITLE
file_should_be_downloaded checks size before checksum... hmm...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1166]
Some identity algorithms are built to identify files that have the same meaning, but different byte streams. It's a domain specific property.  In such cases, the size will be different, but the checksum could be the same.

If the checksum is the same, one should not download.   The routine in flow/__init__.py  def file_should_be_downloaded() checks the file size first and returns True if the size is different... 

That's probably wrong when certain identity algorithms are in use.

**Comment by petersilva** [comment]
I noticed this reading the code, but have no user complaints... just noting it down for now.  likely DMS would products being downloaded (not just winnowed) might  misbehave... effect would be to download products with same identity field but different byte streams.   Since we have winnows to filter these out upstream, might not ever actually happen practically.

@junhu3

**Comment by reidsunderland** [comment]
This commit: https://github.com/MetPX/sarracenia/commit/123c8422fba3d6a5be14276344a800f6da4a1948 introduced a check to skip downloading a file when the mtime in the message is older than the mtime of the file on disk.

But there's also a check earlier in the code that compares the file size on disk with the size in the message. This means that as long as the file sizes are different, the mtime check gets bypassed and an older file is allowed to overwrite a newer file.

I wonder if the order of those checks should be reversed, so mtime gets checked first?

@junhu3 @andreleblanc11

**Comment by andreleblanc11** [comment]
Yeah, that seems wrong.
