### ISSUE TITLE
when started from windows command shell, sr_* is killed when the command shell exits

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#118]
on windows, open a command prompt with sr_subscribe in the path... on my system, Anaconda is installed, so an Anaconda prompt is sufficient:

sr_subscribe start whatever.conf

it starts, and runs in the background.  Kill the Anaconda shell window, and then start another one:

sr_subscribe status whatever.conf

will show all instances as *missing*.

**Comment by petersilva** [comment]
Process is launched by sr_instances/start_instance/subprocess.Popen.

solution might be to get it to run pythonw.exe, in place of python.exe.  but how to tell distutils to do such a thing?

Tried some startup otions on Popen, to no avail so far.

**Comment by petersilva** [comment]
fix committed. 
17415f103e4a5714846fe62dc81689af370a63df
97b2390953970f2a5004521471efc33fd3f79564

**Comment by petersilva** [comment]
fix released in 2.18.11b1

**Comment by petersilva** [comment]
Fix for Anaconda broke python.org. Daniel now working on it.

**Comment by benlapETS** [comment]
The way to avoid killing Sarracenia with a close event in PS would be to write and execute a [Start-Job](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/start-job?view=powershell-6) cmdlet. That would be the equivalent of writing '\<cmd\> &' or doing '^z' followed by 'bg' in a linux terminal. Though, I think that Daniel's solution with the task scheduler is still the best option. I will write a user manual to help our Windows users 

PYW is when you want to click on python script and dont want a console to pop up behind (ie when you're running a GUI with python). See 2 first answer [python or pythonw](https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe?noredirect=1&lq=1)

**Comment by benlapETS** [comment]
I think that we need to remove files .pyw extension genereation in Sarracenia as it is not needed anymore. When we dont want the shell, we have the Task Scheduler option that is now well documented in [Win without prompt](https://github.com/MetPX/sarracenia/blob/master/doc/windows/Windows.rst#running-sarracenia-without-a-command-prompt). Finally, everything works well with python.org, that would need to be double check before we close this issue I guess?

**Comment by petersilva** [comment]
I don't think we generate .pyw files... we were considering doing that, but do we do it?
It is setup.py that would do that.  What is there to remove? do you mean the windows_run thing?

**Comment by benlapETS** [comment]
Uh... I maybe misunderstood what was going on under the hood with pyw stuff. But with issue122 fixed and the documentation of [Win without prompt](https://github.com/MetPX/sarracenia/blob/master/doc/windows/Windows.rst#running-sarracenia-without-a-command-prompt) done what Ive should asked is: do we have something left to do here with the pyw stuff ? is that issue still meaningful ?

**Comment by petersilva** [comment]
It is resolved by #122
