### ISSUE TITLE
v2 "blast from the past" on sr_poll failover.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1184]
when upgrading from v2.21 -> v2.24.08 ... we thought we had allowed all the sr_poll file listings to update properly before switching the vip, but we got a blast from the past anyways.

We do not understand why this happenned.

**Comment by andreleblanc11** [comment]
Another weird behaviour noticed (not sure if it's the same issue or not)

## Observed behaviour
- We will be updating a server that has v2.21.04 of sarracenia v2 to a v2.23.07 and up.
- For some polls, once we start them back up, they will re-post *all* the files it founds on the remote server.
- Normally the `ls` file is supposed to catch duplicated files and avoid such behaviour.
- For whatever reason, the poll looks to be ignoring the `ls` file entries and keep posting all of the files found.
- This is **slightly** different than what is described in the issue description. It will keep having "blasts from the past" until the configuration is restarted and has its cache cleared.
- This doesn't impact all polls, only some specific ones. We're not sure why this is happening.

## How to fix
- Stop the poll
- Delete all the files under the cache directory `~sarra/.cache/sarra/poll/my-config/*`
- Start the poll
- **UPDATE : This fix DOESN'T ALWAYS WORK**

## Impact
- Luckily the impact isn't that big for the moment. It looks like after restarting the config and deleting the cache that the poll correctly constructs the `ls` file.

**Comment by petersilva** [comment]
this might be just a plain problem with v2 polls in the latest release, but only affecting some configurations.
It is not just when starting up after an upgrade.  It seems to recur once in a while if the poll runs for a long time.
still clarifying.

work-around: upgrade flow to sr3.
