### ISSUE TITLE
sr3 sanity (and sr3 start) does not start instances after config edited

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1194]
There's a problem with the sr3 cli. 

It correctly reports that a config is in a `partial` state (i.e. >=1 instance running, but less than the configured number of instances), but the count does not reflect this, it shows X/X running.

sr3 start also does not make any attempt to start the missing instance(s).

Steps to reproduce:

Run sr3 status and confirm that the config is in `run` state.

Modify an already running config file to add more instances. Run `sr3 status component/config` and `sr3 start` or `sr3 start component/config`. sr3 start will not start the missing instances.

sr3 status should show state `part`, but it the number of instances (run/expected) is not correct (it will show N/N where N is the number of instances).

**Comment by reidsunderland** [comment]
Before modifying the config to increase the instances from 3 to 5:

```
$ sr3 status sarra/get_thing
status:
Component/Config                                     Processes   Connection        Lag                              Rates
                                                     State   Run Retry  msg data   Que   LagMax   LagAvg  Last  %rej     pubsub   messages     RxData     TxData
                                                     -----   --- -----  --- ----   ---   ------   ------  ----  ----     ------   --------     ------     ------
sarra/get_thing                                   idle    3/3     0 100%   0%     0    0.00s    0.00s  372s  0.0%      0 B/s      0 m/s      0 B/s      0 B/s
      Total Running Configs:   1 ( Processes: 199 missing: 0 stray: 0 )
                     Memory: uss:15.6 GiB rss:18.0 GiB vms:44.9 GiB
                   CPU Time: User:693993.17s System:32221.96s
           Pub/Sub Received: 527 m/s (176.5 KiB/s), Sent:  206 m/s (83.6 KiB/s) Queued: 11703 Retry: 24422, Mean lag: 93.74s
              Data Received: 122 f/s (45.0 MiB/s), Sent: 112 f/s (901.7 KiB/s)
```


After increasing the instances from 3 to 5:

```
sr3 status sarra/get_thing
status:
Component/Config                                     Processes   Connection        Lag                              Rates
                                                     State   Run Retry  msg data   Que   LagMax   LagAvg  Last  %rej     pubsub   messages     RxData     TxData
                                                     -----   --- -----  --- ----   ---   ------   ------  ----  ----     ------   --------     ------     ------
sarra/get_thing                                   part    5/5     0 100%   0%     0    0.00s    0.00s  407s  0.0%      0 B/s      0 m/s      0 B/s      0 B/s
      Total Running Configs:   1 ( Processes: 199 missing: 0 stray: 0 )
                     Memory: uss:15.6 GiB rss:18.0 GiB vms:44.9 GiB
                   CPU Time: User:694336.67s System:32232.83s
           Pub/Sub Received: 530 m/s (180.8 KiB/s), Sent:  212 m/s (86.7 KiB/s) Queued: 13245 Retry: 24534, Mean lag: 114.59s
              Data Received: 124 f/s (42.3 MiB/s), Sent: 117 f/s (1.0 MiB/s)



sr3 start sarra/get_thing
starting:( 0 ) Done
```

**Comment by reidsunderland** [comment]
3.00.53rc1 correctly reports the number of running vs expected instances. sr3 start still doesn't start them.

That bug (incorrect number of running instances) was introduced between 3.00.53rc1 and 3.00.54rc1.

I went back to 3.00.42 but even that version doesn't start the missing instances with sr3 start component/config. It's possible that it never worked on sr3, but it does work on v2 and is very useful.

**Comment by petersilva** [comment]
um... 
* this is kind of a sugar thing... 
* stop, edit, start, and it will be ok.  (work-around.)

It makes sense that this should work, but this means of updating was never allowed for... it was originally conceived as stop/edit/start.

first thing to debate is... what should sr3 "expect".
* #of instances corresponding to number of .pid files?
* #of instances corresponding to config instances?

**Comment by petersilva** [comment]
I added the enhancement tag because the behaviour described in v2 is kind of accidental.  It was also intended to use stop/edit/start methods. the fact it works is just luck.

**Comment by reidsunderland** [comment]
Interesting, I didn't realize it was accidental in v2. Just running start (instead of stop/start or restart) is our normal process when increasing the instances in v2.

I think it's worth supporting, since you may want to add instances to a config that is in the middle of a long, slow download. Rather than stopping and interrupting the download, it's nicer to just add additional instances to help out.

I agree it's sugar and not a bug if it wasn't originally intended. The incorrect count is still a problem.

> first thing to debate is... what should sr3 "expect".
> 
> #of instances corresponding to number of .pid files?
> #of instances corresponding to config instances?

I think we should trust the config file.

**Comment by petersilva** [comment]
so... like... if you edit the config and lower the number of instances... should it stop/kill the too high ones?

**Comment by reidsunderland** [comment]
I would say yes, excess instances should gracefully get stopped. 

We've kind of talked about that problem in the context of containerization, dynamic scaling of instances up and down. Discussed a bit here: https://github.com/MetPX/sarracenia/issues/569 (there might be another issue, but I couldn't find it).

I don't think we should ever force kill an instance when trying to reduce the number of instances. 

We should just send SIGTERM (from sanity?) and hope it will eventually shut itself down. And have a new status for "too many instances running" to notify us if it doesn't shut down. Or we could have the instance itself periodically re-read the config and shut itself down if its instance number is greater than the number of set instances.

**Comment by petersilva** [comment]
Thinking about it... normally... changes to config files are not supposed to take effect until we stop/start... so you can edit things "freely" ... if we change, say bindings, and the number of instances, then sr3 sanity runs,  only the intances that get started will get the new bindings.  

similarly for accept/reject clauses... if we add instances we'll end up with asymmetry.
hmm...

**Comment by petersilva** [comment]
I don't think that having different instances running with potentially different versions of the config file is a good thing.
There may be aspects of an instance that depend on knowing the number of instances, and the lower numbered/earlier started instances will not have correct information.

Other completely different changes (plugin invocations, accept reject patterns, etc...) can be present in new config file versions, and having a fraction running different versions is probably error prone in practice.

Most people, in most cases, working with linux daemons, expect some sort of "restart" to be needed for a configuration file change to be activated.  

on balance:
*  I think the v2 behavior was a accident/mistake.
*  I think treating the config file as a working file until someone does an explicit intervention is the correct thing to do,
* What sr3 currently does is correct.

Tempted to tack on *wontfix* but not completely sure yet.
thoughts?

**Comment by reidsunderland** [comment]
I'm okay with wontfix for the start/sanity behaviour.  It makes sense to not want different versions of the same config running.

I think there's still weirdness in the status display that should eventually be fixed. But it's just a cosmetic issue so I don't think it's a high priority. If you have a config with 3 instances and all 3 instances are running, then you modify the config to have 5 instances, before restarting it or doing anything, sr3 status will report that 5/5 instances are running (it should say 3/5). But it  correctly reports that that the config is in `part`ial state.

**Comment by petersilva** [comment]
yeah... I have also seen it being ... optimistic? about reporting running instances... not sure what is going on there.
