### ISSUE TITLE
tlsRigour documentation inconsistent

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1201]
The documentation says:

> tlsRigour (default: medium)[](https://metpx.github.io/sarracenia/Reference/sr3_options.7.html#tlsrigour-default-medium)
> tlsRigour can be set to: lax, medium, or strict, and gives a hint to the application of how to configure TLS connections. TLS, or Transport Level Security (used to be called Secure Socket Layer (SSL)) is the wrapping of normal TCP sockets in standard encryption. There are many aspects of TLS negotiations, hostname checking, Certificate checking, validation, choice of ciphers. What is considered secure evolves over time, so settings which, a few years ago, were considered secure, are currently aggressively deprecated. This situation naturally leads to difficulties in communication due to different levels of compliance with whatever is currently defined as rigourous encryption.
> 
> If a site being connected to, has, for example, and expired certificate, and it is nevertheless necessary to use it, then set tlsRigour to lax and the connection should succeed regardless.

It says the options are lax, medium or strict, which is different than the code which expects lax, normal or strict.

https://github.com/MetPX/sarracenia/blob/f7563bc70c0805f18768298df5e6bef0e64a7856/sarracenia/config.py#L893

https://github.com/MetPX/sarracenia/blob/f7563bc70c0805f18768298df5e6bef0e64a7856/sarracenia/transfer/https.py#L58-L80

I'll update this while working on #1157. I will update the documentation to match the code (change medium in documentation to normal), unless someone objects.

**Comment by petersilva** [comment]
I got to this because I was in the area anyways... hope that's ok.
