### ISSUE TITLE
sftp creates directories when it shouldn't

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1242]
@MagikEh and @tysonkaufmann  found that SFTP is creating subdirectories when it shouldn't 

This change: https://github.com/MetPX/sarracenia/commit/7c95a6fc07c5bb72fc9f2f8efbb1df3cad4650bc#diff-e02ac4c315937c5c6b4c09a0468763f12a50c1e68613cadb0bf40508e5c6e657

Accidentally removed a `return` from cd_forced that was actually needed. 

cd_forced is supposed to cd to the directory. If it can't cd to it, it creates the dir. The bug is that even if the cd is successful, it still creates the directory instead of returning

**Comment by reidsunderland** [comment]
Sadly this bug is in 3.00.55. I think we might need to do a 3.00.55p1 release?

**Comment by petersilva** [comment]
sigh... https://github.com/MetPX/sarracenia/releases/tag/o3.00.55post1
