### ISSUE TITLE
U18.04 packages missing `sarracenia/flowcb/rename` directory w/ files

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1269]
The directory is available on U22.04 servers

```
root@ncp1-op:~# cat /etc/issue
Ubuntu 22.04.4 LTS \n \l
root@ncp1-op:~# ls -alFd /usr/lib/python3/dist-packages/sarracenia/flowcb/rename/
drwxr-xr-x 3 root root 48 Aug 15 15:56 /usr/lib/python3/dist-packages/sarracenia/flowcb/rename//
```

But is not on U18.04 servers?

```
root@ddsr-cmc-dev01:~# cat /etc/issue
Ubuntu 18.04.6 LTS \n \l
root@ddsr-cmc-dev01:~# ls -alFd /usr/lib/python3/dist-packages/sarracenia/flowcb/rename/
ls: cannot access '/usr/lib/python3/dist-packages/sarracenia/flowcb/rename/': No such file or directory
```

It looks like this has been the case since the inception of my `rename/raw2bulletin.py` plugin - [V3.0.53](https://github.com/MetPX/sarracenia/releases/tag/v3.0.53)

## Work around (kinda?)
Even when I tried to add the plugin to the gitlab repo it gave problems. 
The work around is to `mkdir rename` where it's supposed to be in the package directory. The code will then stop crashing, if the plugin is found from the gitlab repo.

**Comment by petersilva** [comment]
you need to have a \_\_init__.py (could have just *pass* in it... ) in the directory in order for the packaging utilities to include it... I guess the newer ones don't need it but the older ones do?
could that be what is going on?

**Comment by andreleblanc11** [comment]
The new pre-release package (3.00.56rc2) includes the `rename` directory now and its files. Closing issue.
