### ISSUE TITLE
a sort of "standby mode & catchup mode" for subscribers to offload brokers during long outages.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1275]
For prolonged outages on the client (a subscriber's disk goes down, as an example) where a subscriber (or sender) knows that they won't be able to resume transfers any time soon.

The subscriber will try to download each file (3 times), and put them in a retry_queue.  The effort of trying to download will be slow, is a wasted load, and might not keep up with the messages being posted.

Then you know you won't be able to complete transfers for some time, there should be a way to just put the messages directly in the retry_queue without trying the download.

When returned to service, we would need to always replay that retry_queue, and let new stuff queue up... or even add new stuff to the retry_queue instead of playing current stuff....
a "catch-up" mode.

**Clarification**:

The above describes what happens if you leave the subscriber running when you know downloads will fail.
An alternate strategy would be to stop the subscribers, and let the queue build up on the brokers.
All tuning/performance advice for all messages brokers recommends keeping queues short.  Large Queues slow down the entire broker, compromising other flows.  It is considered far better to persist the queues to local
storage rather then have the backlog build up (into millions) on the broker.

**Comment by petersilva** [comment]
one way of doing it...  could perhaps have an automatism... 

* if three downloads fail in a row, then go into "standby" mode.
* once in standby mode, perhaps return to "running" once every housekeeping interval.
* It will try three downloads, and go back into "standby" mode.
* if the a download succeeds, go from "standby" to "catchup" mode.
* in catchup mode, 
    * read only from the retry queue... 
    * append stuff from the socket to the end of the retry queue.

At some point, we decide we have caught up, (e.g. retry queue is empty) return to running normally ("running")

So analyst intervention would be zero.  They just start up the subscriber, it automatically goes into standby when it realizes it cannot write... and when it detects things are back, it catches up, and then goes back to normal.

**Comment by petersilva** [comment]
@junhu3 had a different idea? Now is the time to kick around different ones... the standby/catchup thing is what I was thinking... I was originally thinking it had to be manual, but maybe automatic works... other ideas?

**Comment by petersilva** [comment]
One implementation, put this in the configuration file:
```

attempts 0

```
Then it tries 0 times to download before putting something on the retry_queue, implementating *standby*
the recovery is normal however.

Turns out there is a bug:
```
2024-10-29 11:44:12,927 [INFO] 1054767 sarracenia.flowcb.log after_accept accepted: (lag: 3.14 )  exchange: xpublic subtopic: 20241029.WXO-DD.bulletins.alphanumeric.20241029.SX.KWAL.15 a file with baseUrl: https://hpfx.collab.science.gc.ca relPath: /20241029/WXO-DD/bulletins/alphanumeric/20241029/SX/KWAL/15/SXCN40_KWAL_291543___63617 sundew_extension: cvt_nws_bulletins-sr:KWAL:SX:3:Direct:20241029154407 id: aHplsxL size: 586
Traceback (most recent call last):
  File "/home/peter/sr3/sarracenia/instance.py", line 276, in <module>
    i.start()
  File "/home/peter/sr3/sarracenia/instance.py", line 267, in start
    self.running_instance.run()
  File "/home/peter/sr3/sarracenia/flow/__init__.py", line 608, in run
    self.work()
  File "/home/peter/sr3/sarracenia/flow/__init__.py", line 1175, in work
    self.do()
  File "/home/peter/sr3/sarracenia/flow/__init__.py", line 1165, in do
    self.do_download()
  File "/home/peter/sr3/sarracenia/flow/__init__.py", line 1904, in do_download
    if not ok:
UnboundLocalError: local variable 'ok' referenced before assignment
2024-10-29 11:44:13,057 1054764 [CRITICAL] root run_command subprocess.run failed err=Command '['/usr/bin/python3', '/home/peter/sr3/sarracenia/instance.py', '--no', '0', 'foreground', 'subscribe/hpfx_amis']' returned non-zero exit status 1.

```

**Comment by petersilva** [comment]
We spoke with the client today, and he seemed very reticent about catchup mode.  He described something very much like our normal recovery mode (prioritize current data, read from the retry queue when we are not fully occupied with current data.) so it seems like all we really need is the standby mode (implemented by *attempts 0* setting.)

This does not seem obvious as a way of doing it... should we add some sugar,... "sr3 standby subscribe/xx" will override the attempts setting (and maybe some timeouts? allow the messages longer ttl's to be used in a day or two?) also
*sr3 status* does not show anything obvious about being in standby mode.

**Comment by junhu3** [comment]
Here's what I did for nws after an outage to get the most recent data instead of backlog: 
```
- In nws, I moved all old data from the main directory data to a separate directory old_data.
- I already have separate poll for that directory.
- I alreadu have a separate sarra process get_old_data with only one instance (less than the main sarra process get_data)
```
That way, the main sarra is getting the current data and the old one is getting the old data. It will take time but eventually, the old_data directory will be empty. So my idea is having a separate "standby/catchup" subscribe and finding a way to move these "old message" to that subscriber manually or automatically. I have some ideas if we want to do that way...

**Comment by petersilva** [comment]
ok... I was thinking of  the HPC mirror case, in the HPC mirror case:

We don't have the data... all the data is on the site stores, and we aren't allowed to move it. heck, we can't even traverse it (would take hours) All we have is messages.  While the normal ops site store is down, we can run with the standby mode (attempt 0) we create a ~/.cache/sr3/maybe_host/subscribe/download_XX.retry files... where XX is per instance 01->39 ish...

So those download_retry files are just a sequence of messages, in json format, which can be reprocessed by the subscriber. If you do nothing, when they come back, we remove *accept 0* so it goes back to  default, and then it will be in *retry* state, when it will mix current and backlog together gradually recovering.

If you want explicitly to recover with another flow, then after you stop to change the config, you move the retry files to some other flow's state directory, or you can merge them into a different set of files... they are just json/text files. so you create a new retry file for your alternate flow.  So then you can start up the current flow, and it just deals with current stuff, while this backlog subscriber deals with the retry stuff.

I dunno... I think people will just wait for the normal retry logic to clean things up, rather than messing with the above.  The download_retry logic does a good job of mixing current and old traffic together so that you don't get starvation or excessive delay, but that won't help on a poll.  For a poll, it is painful.

For the nws poll... what you did makes sense... If you had not done that, the old and new data would have been interspersed and the poll would have been really slow until the backlog was cleared.  for that case a separate poll for the backlog makes all kinds of sense.   It sounds like the work done was doable by an experienced admin.  Is there something in sr3 that can make that easier next time?

**Comment by junhu3** [comment]
> If you want explicitly to recover with another flow, then after you stop to change the config, you move the retry files to some other flow's state directory, or you can merge them into a different set of files... they are just json/text files. so you create a new retry file for your alternate flow. So then you can start up the current flow, and it just deals with current stuff, while this backlog subscriber deals with the retry stuff.

 Yes, already tried that before, that's one of the way to do it. What I though is to make that automatically when it failed to download or in some conditions with an option in the subscriber like
```
save_retry_file_to  another_subscriber 
or 
post_to_outage_broker    another_broker 
or
post_to_outage_exchange another exchange 
```
Actually, will be similar to the sarra code post_broker and post_exchange lol

**Comment by petersilva** [comment]
if we want to post somewhere else... we can use a shovel to send it to another broker, with no change in code.  but even when we "land" somewhere... we need to persist to disk somehow. hmm...

**Comment by petersilva** [comment]
fwiw... the *attempts 0* support is in 3.0.56, which is propagating to main pumps and HPC at the moment.
