### ISSUE TITLE
hpfx connections hang after 4 hours?

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1277]
> Is this from dd or hpfx?

I always use "dd" because I find that HPFX forgets my subscriptions after about 4 hours.  I've written multiple messages to Sandrine, but never got a real response about it.

_Originally posted by @endlisnis in https://github.com/MetPX/sarracenia/issues/1261#issuecomment-2409085005_

**Comment by petersilva** [comment]
Just wanted to follow up on this comment... It's a different problem from #1261

**Comment by petersilva** [comment]
So the problem is ... if your subscriber crashes/ drops/whatever... if you come back and >4hours have passed, the queue is gone? Is that the complaint?

**Comment by endlisnis** [comment]
I should clarify that I haven't tried to reproduce this problem in a couple of months, but here's what I experienced:

(1) Subscriber stays connected for > 4 hours (it seems to happen at almost exactly 4 hours ± 1 minute).
(2) Messages stop flowing.
(3) All diagnostic messages seemed to indicate that everything was fine, just no messages were arriving.

I would restart the subscribers and the problem would persist.

If I changed the queue names, and then restarted the subscribers, it would receive messages for exactly 4 hours again and then stop.

I iterated that about 10 times before switching back to "dd".

**Comment by petersilva** [comment]
wow... that's weird... never seen anything like that... no idea what it could be... hmm...  

* what is the configuration... are you subscribed to a lot of different data or just one kind or...
* in recent versions... you can see lag and (if >=3.0.55) the size of the queue on the broker...
 (if you have a chance to try again... it would be good to see what *sr3 status* says, before
you get to the four hours.)

**Comment by petersilva** [comment]
I started a subscriber... (subscribe/hpfx_amis from the examples) ... in about 4 hours... I'll look for weirdnesses ... seems fine so far:
```
fractal% sr3 status
status: 
Component/Config     Processes   Connection        Lag                              Rates                                        
                     State   Run Retry  msg data   Que   LagMax   LagAvg     Last  %rej     pubsub   messages     RxData     TxData 
                     -----   --- -----  --- ----   ---   ------   ------     ----  ----     ------   --------     ------     ------ 
cpost/local_post     stop    0/0          -          -         -     -     -          -        -          -          -          -
subscribe/hpfx_amis  run     5/5     0 100%  18%     0   16.96s    3.59s    3.32s  0.4%     346B/s       2m/s   1.4KiB/s       0B/s 
      Total Running Configs:   1 ( Processes: 5 missing: 0 stray: 0 )
                     Memory: uss:246.9MiB rss:351.4MiB vms:571.0MiB 
                   CPU Time: User:3.41s System:0.76s 
	   Pub/Sub Received: 7m/s (1.0KiB/s), Sent:  0m/s (0B/s) Queued: 0 Retry: 0, Mean lag: 3.82s
	      Data Received: 7f/s (4.1KiB/s), Sent: 0f/s (0B/s) 
fractal% date
Mon 28 Oct 2024 12:26:05 PM EDT
fractal% 


```

**Comment by petersilva** [comment]
first try failed miserably... I likely found a different problem.  Checked after three hours and see this:
```
024-10-28 13:19:34,481 [ERROR] sarracenia.transfer.https __open__ unable to open https://hpfx.collab.science.gc.ca/20241028/WXO-DD/bulletins/alphanumeric/20241028/SR/KWAL/17/SRCN40_KWAL_281711___27699
2024-10-28 13:19:34,481 [ERROR] sarracenia.flow download could not get SRCN40_KWAL_281711___27699: signal alarm timed out
2024-10-28 13:19:34,481 [INFO] sarracenia.flow do_download attempt 1 failed to download https://hpfx.collab.science.gc.ca//20241028/WXO-DD/bulletins/alphanumeric/20241028/SR/KWAL/17/SRCN40_KWAL_281711___27699 to /tmp/hpfx_amis/SRCN40_KWAL_281711___27699
2024-10-28 13:19:34,481 [WARNING] sarracenia.flow do_download downloading again, attempt 2
2024-10-28 13:19:34,577 [WARNING] sarracenia.moth.amqp ack failed for tag: {'delivery_tag': 2096, 'channel_id': 2, 'connection_id': '16c6a19c-825d-4058-bfd7-a1c37294949e_sub', 'broker': 'hpfx.collab.science.gc.ca:5671//'}: EOF occurred in violation of protocol (_ssl.c:2406)
 ...

406)
2024-10-28 15:24:20,824 [INFO] sarracenia.moth.amqp ack Sleeping 64 seconds before re-trying ack...
2024-10-28 15:25:24,825 [WARNING] sarracenia.moth.amqp ack failed for tag: {'delivery_tag': 2096, 'channel_id': 2, 'connection_id': '16c6a19c-825d-4058-bfd7-a1c37294949e_sub', 'broker': 'hpfx.collab.science.gc.ca:5671//'}: EOF occurred in violation of protocol (_ssl.c:2406)


```

And just loops forever after that... ( opened #1278 for that.)

**Comment by petersilva** [comment]
OK after restarting... from that failure for 1 ack. I ran the subscriber for 6 hours... with nothing bad happenning... 3 seconds of lag... I will check it again tommorrow am.

**Comment by petersilva** [comment]
It happenned again... same bug... I did a local fix.  I´m seeing #1278  over and over, but nothing else.
two restarts so far.

**Comment by petersilva** [comment]
the local fix works... still exploring best method to address in other bug... for this issue... not reproducing...

**Comment by petersilva** [comment]
12 hours... (with fix for ack problem) fine... no problem.  Not reproducing.

**Comment by endlisnis** [comment]
I was able to create an alternate setup that uses hpfx, and it seems fine.  Maybe the problem is gone.  At some point, I'll switch my primary system back to hpfx and see if it is OK.

**Comment by petersilva** [comment]
you will probably hit the ack problem... rc3 will fix it.

**Comment by petersilva** [comment]
closing for now for inactivity...
