### ISSUE TITLE
use with non-rabbitmq brokers (interoperability) aka. MQTT

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#128]
Chatting with WMO people, we want to adopt standards that have multiple, interoperable implementations.  It has been pointed out that Sarracenia is currently reliant on a single broker implementation RabbitMQ, with no demonstrated interoperability.

**Comment by petersilva** [comment]
now that support for experimental v03 format is merged, have added experimental MQTT publisher
( commit: 5548738da3e3576dd77bafbaee491966234b2ad9 )

instructions for use are in the commit. sample config:

```
broker amqps://anonymous@dd.weather.gc.ca/
exchange xpublic

# add your own string to end to prevent clashes with multiple devs running flow test.
queue q_${BROKER_USER}.${PROGRAM}.${CONFIG}.${HOSTNAME}.${RANDID}

no_download

exp_2mqtt_post_broker mqtt://guest@localhost
post_exchange xwinnow 

plugin exp_2mqtt

accept .*

report_back False

```

That will publish a stream of notification to an MQTT broker on localhost 
(authentication not yet supported.)

In testing so far:

* not clear how subscriber achieves reliability (default connections in my sample restart clean every time, need to understand how to do persistence)  current subscriber misses messages.  subscriber code here:

```
import paho.mqtt.client as mqtt

def on_connect(client, userdata, flags, rc):
    print("Connected with result code "+str(rc))
    client.subscribe("#")

id=0

def on_message(client, userdata, msg):
    global id
    id = id + 1
    print( "     id: ", id )
    print( "  topic: ", msg.topic )
    print( "payload: ", msg.payload.decode("utf-8") )

client = mqtt.Client()

client.on_connect = on_connect
client.on_message = on_message

print('about to connect')
client.connect( 'localhost' )
print('done connect')

client.loop_forever()

```

**Comment by petersilva** [comment]
client=mqtt.Client(clean_session=False,client_id='my_queue_name')
will do the right thing for when things get disconnected.
client_id serves same purpose as queue_name on sarracenia AMQP connections.

Q: If multiple consumers connect with same queue_name, do they share it?

**Comment by petersilva** [comment]
make sure you look at https://github.com/MetPX/WMO_mesh for a working MQTT example.

**Comment by benlapETS** [comment]
Ok I had to take 2 steps back because of that issue:
- First step... this led me to try to understand how amqp is integrated before trying any changes in that direction.
- Second step... the sr startup procedure was unclear for me and it was confusing me in my understanding of amqp integration

Then, I started this issue on sr cleanup

**Comment by benlapETS** [comment]
Note1: The plan is to create a new module sr_mqtt which tries to duplicate sr_amqp functionnalities with sr_client as a parent for the common ground.
Note2: I will first try to draw an analysis from current dependencies on sr_amqp to accuratly specify the impact of this task.

**Comment by benlapETS** [comment]
Note1: If we want that Sarracenia publish and consume mqtt through an RabbitMQ amqp exchange, the responsibility of managing mqtt should belongs to sr_amqp module as we will stand to amqp standards (0-9-1). We decided to profit from the static plugin that is now available from RabbitMQ and that enable MQTT support and which seems relatively painless. That means that the coding should all be done in sr_amqp.
Note2: We should choose amq.topic exchange which is the default exchange for dealing with MQTT on RabbitMQ. This will minimize the development effort required for this issue and simplify our code in sr_amqp because we won't have to deal with MQTT exchanges at this level. 
Note3: We could open the door for realtime setup of MQTT exchange for later if the need arise. I think this would require passing through sr_rabbit and adding the code there to handle this.

**Comment by petersilva** [comment]
I think to avoid confusion, we need a separate issue to deal with the first step of the plan, which is quite different.  For this issue, we want Sarracenia to natively use an mqtt library to communicate with mqtt brokers, but @benlapETS found the mqtt plugin for rabbitmq which opened up a new, far quicker way
to get some initial interoperability, that could be quite popular.  #227   Likely should do that first, once it works, come back here.

**Comment by benlapETS** [comment]
Note1: This diagram is a bit sketchy but I'm adding it anyway. It will surely improve after time. This is kind of a basic UC for the issue.

![image](https://user-images.githubusercontent.com/11091581/59868277-8b9c5c80-935e-11e9-814b-4a80d29ecd9e.png)

**Comment by petersilva** [comment]
yes. that diagram looks like what we mean...

**Comment by benlapETS** [comment]
Note1. Here are the detailed use cases for the issue:
1. The analyst want to activate the MQTT Plugin in one of its RabbitMQ broker. This is where he decides the name of the mqtt topic exchange to use, the set of credentials used to communicate with it, the uses of anonymous, prefetch, the security support, vhost mapping. The information for those needs is all available at [MQTT Plugin](https://www.rabbitmq.com/mqtt.html) page. The configuration is usally done statically once. Then the system will set the configuration that we already support like adding exchange, adding user.  
2.

**Comment by petersilva** [comment]
for 1:  exactly right, for example, in Sarracenia we use the convention *anonymous:anonymous* ... to reflect that on with the mqtt_plugin, one might have rabbitmq settings such as:
```

mqtt.default_user = anonymous
mqtt.default_pass = anonymous

```
It would be upto the pump administrator to configure rabbitmq and sarracenia together to get a working configuration.

2.  that describes use of the rabbitmqtt_post_exchange setting, yes.

3.  that describes use of the rabbitmqtt_exchange setting, yes.

4. external mqtt clients... yes.

I think this is entirely correct.

**Comment by petersilva** [comment]
we would probably want to recommend use an exchange like:  xmqtt_public to be consistent with Sarracenia permission/conventions... exchanges start with x, and if readable by all, they should end in public...

**Comment by petersilva** [comment]
clarification of the above...:
`
mqtt.exchange = xmqtt_public

`
in the rabbitmq config file...

**Comment by benlapETS** [comment]
Oups sorry I moved my comments to #227 !

**Comment by benlapETS** [comment]
> for 1: exactly right, for example, in Sarracenia we use the convention _anonymous:anonymous_ ... to reflect that on with the mqtt_plugin, one might have rabbitmq settings such as:
> 
> ```
> 
> mqtt.default_user = anonymous
> mqtt.default_pass = anonymous
> ```
> 
> It would be upto the pump administrator to configure rabbitmq and sarracenia together to get a working configuration.
> 
>     1. that describes use of the rabbitmqtt_post_exchange setting, yes.
> 
>     2. that describes use of the rabbitmqtt_exchange setting, yes.
> 
>     3. external mqtt clients... yes.
> 
> 
> I think this is entirely correct.

I think that we will have to be carefull with anonymous users, citing the web page:
```
The plugin supports anonymous authentication but its use is highly discouraged and it is a subject to certain limitations (listed below) enforced for a reasonable level of security by default.
```

**Comment by petersilva** [comment]
anonymous is supposed to be a *readonly* user, much like an unauthenticated user on a web site.
the user should not be given permission to write anywhere (except perhaps reports of downloads.)
That is the Sarracenia convention... There isn't a way to provide *public* announcements without *public* (pseudo unauthenticated) access.

**Comment by petersilva** [comment]
Tyson now working on attacking it in the v3 codebase...
