### ISSUE TITLE
`sr3 disable` doesn't work when a config is first created

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1283]
# How to reproduce

- Create a new config
- Try to run `sr3 disable`
- When you run the command, there's no stdout output.
- When you check status after, the config shows as `stopped`

# Work around
- Create the cache directory either manually `mkdir -p ~/.cache/sr3/component/config` or (likely) run `sr3 declare component/config`

This isn't a bug but more of an inconvience for analysts that have created a new config but don't want to use it right away

**Comment by petersilva** [comment]
the disable command needs to create the cache dir if it doesn't exist.  should be an easy fix.

**Comment by petersilva** [comment]
Hey @mshak2 this would probably be a good thing to put in your todo queue.
