### ISSUE TITLE
Add segmentation to AM sender

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1284]
This was overlooked when I first created the AM sender. The sundew code will automatically segment data if the maximum bulletin length is reached. 

https://github.com/MetPX/Sundew/blob/main/lib/senderAm.py#L247-L301

The current sr3 AM sender now will fail when the `MaxBulLen` is reached. In traditional AM, this value is 32768 bytes. So any bulletin that is over 32768 bytes needs to be segmented. 

However in our AM receiver, we could easily use the same `MaxBulLen` so that we don't even need to segment the data.

https://github.com/MetPX/sarracenia/blob/4a9f6424eaee6ae50f6343bf6a7643a615c3740a/sarracenia/flowcb/send/am.py#L82-L84
https://github.com/MetPX/sarracenia/blob/4a9f6424eaee6ae50f6343bf6a7643a615c3740a/sarracenia/flowcb/gather/am.py#L86

Unfortunately, we do still send data directly to MM, so segmenting every 32768 bytes is still necessary.

**Comment by petersilva** [comment]
I specifically told you NOT to implement segmentation/reassembly.   We're not doing that.  was not overlooked was explicitly deemed out of scope.

**Comment by petersilva** [comment]
current behaviour is correct.  just refuse to send.

**Comment by andreleblanc11** [comment]
Did not remember that. Thanks for the reminder 😆

**Comment by petersilva** [comment]
It's understandable you forgot...  background:

* The official message length of the WMO was 15000 bytes when I started (early 2000's) and this limit went back 30 years or more.
* to get messages longer than 15,000 bytes, different groups came up with different methods for segmentations... so how you split up the message, correctly, depends on the WMO header. 
    * Sometimes you can just chop it wherever, other times you are supposed to stop with a complete sentence.  
    * You need to change the message header to match the parts of the message ... in different ways depending on the header.
    * If we get partitioned messages from apps on the AM network... we have to do reassembly (stitching them back together.)
 * when I was on GTS meetings in the 2000's we agreed to declare segmentation/reassembly obsolete.  GTS adopted 500,000 bytes as the maximum message size.
    * GTS messages are supposed to be able to be 500,000 bytes long... and segmentation is expressly deprecated.
    * It's only EC internal apps (AM) that have these limits which contradict WMO standards.

AM packages should learn to use 500,000 byte messages and that's it.

(nowadays entire GTS is being deprecated & replaced by WIS2... this limits are double irrelevant.)
