### ISSUE TITLE
Add `fileSizeMax` to sender

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1285]
We currently can use `fileSizeMax` in a component that downloads, to avoid downloading too big of files.

https://github.com/MetPX/sarracenia/blob/4a9f6424eaee6ae50f6343bf6a7643a615c3740a/sarracenia/flow/__init__.py#L1795-L1799

It would be nice to also have this for a sender.

Likely need to add same logic to `do_send`

https://github.com/MetPX/sarracenia/blob/4a9f6424eaee6ae50f6343bf6a7643a615c3740a/sarracenia/flow/__init__.py#L2814-L2827

**Comment by petersilva** [comment]
I very much prefer what we are doing here (refusing to send incomplete data by refusing to try to send it at all if it is too big.)   Some clients might request truncation... sending the bytes until we get to the max size ... perhaps with *TRUNCATED* being the last bytes...

That's:
* a bit more complicated to implement.
* what is a correct checksum? (how do you know a product is correct if you cannot see all of it.)
* does sending a partial product actually help anyone... what if the product has issues later on...?

I think refusing to send (what we have now) is the better approach.  We may, after conversations with the client ... be obliged to implement truncation.
