### ISSUE TITLE
Add a new amqp library

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#130]
Amqplib is what we call an abandonware (no new version since 2011), it is causing some issues (on the Windows side at least) and it might bring more problem in the future. There is a new alternative in python that could be interesting and it needs to be test in parallel in order to insure of its functionnality and its performance.

**Comment by petersilva** [comment]
yup. very good idea.

**Comment by petersilva** [comment]
I ran the flow test on issue130 branch.  It passed... good, but not so good:

The switching does not seem right. When I look in *Connections* tab of the broker management GUI, most of them were 0-8 and only a handful were 0-9-1.  Then I looked in pip and found an old amqlib there, so when both are present, it seems only a few components use amqp.

I removed the amqplib install, and now they are all 0-9-1.  good. Once it is purely using the new library, it seems to work better than the original.  It would likely be flaky in a transition scenario (where both libraries are present.)

**Comment by petersilva** [comment]
I also committed a change on the branch to the dependency in setup.py to be amqp instead of amqplib... so every time you install it does not pull in the old library.

**Comment by benlapETS** [comment]
I don't understand how it would be possible that it uses the old library and I am not convince that it would be related to pip. Also the only switching occurs in choose_amqp_client. I'm not sure if it would be possible that it uses amqplib in any way before it get through the switch and then bypass user config (ie. the connection is created from a parent process). I must admit that I havent test the switch yet as I was testing the fallthrough between libraries when different modules were removed and it was responding as I expected. I will look at this today.

**Comment by benlapETS** [comment]
I have two question which would help taking some decision with amqp related issues:

Do we really need Pika, I mean, is there people depending on it ? I tested it with the flow test and it rarely get through flow_limit (it hangs retrying to send msgs indefinitely) If not, i will remove everything with Pika and it will simplify our options.

Do we need a user config to switch between library, I mean, we could try import amqp and if it doesnt find, it import amqplib and a user who want one or another just pip install the one he wants and he dont needs to install both and the app automatically choose one or another ?

**Comment by benlapETS** [comment]
I made some reading and I found [this good overview](https://packaging.python.org/overview/#) of Python packaging, which I should have red before. It gives all possible options and as I can understand, we are handling this the right way for our needs, but if our needs changes, it would be a good reference.

**Comment by petersilva** [comment]
that link is fabulous... so packaging  it's far worse (even more complicated) than I knew, I hope we can tiptoe away slowly, what we have works for us for now.
