### ISSUE TITLE
delete_destination causes crash/race condition?

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1316]
The "file_should_be_downloaded" method can crash. I am using delete_destination, so I'm assuming it's related to that, but I'm not really sure how.

I don't think this is likely to be a very common occurrence, but we should probably make file_should_be_downloaded (or stat) more robust to prevent crashes.

I also don't understand why this is happening... This is where file_should_be_downloaded is called, and it's inside an if statement that checks if the file exists:
https://github.com/MetPX/sarracenia/blob/a4af0e2c21f211e1d993c3a183b8eed63dbfb09c/sarracenia/flow/__init__.py#L1885-L1893

file_should_be_downloaded is using `msg['new_path']`

https://github.com/MetPX/sarracenia/blob/a4af0e2c21f211e1d993c3a183b8eed63dbfb09c/sarracenia/flow/__init__.py#L1463-L1479

```
    self.do_download()
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 1892, in do_download
    if not self.file_should_be_downloaded(msg):
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 1479, in file_should_be_downloaded
    lstat = sarracenia.stat(msg['new_path'])
  File "/net/local/home/sunderlandr/sr3/sarracenia/__init__.py", line 262, in stat
    sa.st_mtime = os.path.getmtime(path)
  File "/usr/lib/python3.10/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/new_dd/20241203/WXO-DD/observations/swob-ml/partners/on-trca/20241203/hy046/2024-12-03-1105-trca-hy046-hy046-AUTO-swob.xml'
```

**Comment by petersilva** [comment]
hmm... probably multiple messages for same file... so multiple instances writing it stepping on eachother... like you said, a race condition.

**Comment by reidsunderland** [comment]
Oh yeah, that would explain how the file was there one moment and then gone shortly afterwards. I was running 50 instances to test the new DD, so it's quite possible that they were conflicting with each other.

We could wrap the call to `file_should_be_downloaded` in a try/except and download the file if it fails?

**Comment by petersilva** [comment]
sure.. if it fails... I guess assume it ain't there and download?
maybe with an error message that gives a hint. the race condition probably means we're downloading the same stuff multiple times... probably fix the config not to download so many copies of things...
