### ISSUE TITLE
`inflight None` in sender causes messages to get retried

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1327]
If you have a sender that doesn't have `inflight` set, messages will get retried. This is the exception message we are getting in the logs

```
sarracenia.flow send Exception details:
Traceback (most recent call last):
  File "/net/local/home/leblanca/.local/lib/python3.10/site-packages/sarracenia/flow/__init__.py", line 2418, in send
    'rename') and options.inflight.startswith('.'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

The `inflight` value defaults to `None`. 

```
sr3 show sender/config-name | grep inflight
'inflight': None
```

This also conflicts with what the documentation states? It says the inflight defaults to `.tmp` when `post_baseDir` isn't set.
https://metpx.github.io/sarracenia/Reference/sr3_options.7.html#inflight-string-default-tmp-or-none-if-post-broker-set

Regardless, `inflight None` shouldn't be failing.

**Comment by petersilva** [comment]
unclear what to do about documentation discrepancy.
* on the one hand... it might be a v2 default consistency thing... in v2 many different components had different defaults, and analysts lost track, so they started specifying it everywhere... losing any benefit of defaults.   So making it have one default for all components might be an purposeful change made in sr3... in which case we just fix the docs.
* on the other hand, we probably need inflight .tmp very often for senders... probably dumb not have it not be the default when no post_broker is set.
* It's also confusing to derive the inflight setting from post_broker setting... people won't guess. PoLA violated.

**Comment by petersilva** [comment]
PR is submitted, but doesn't affect documentation.

**Comment by petersilva** [comment]
OK.. I went with default is None everywhere...

**Comment by petersilva** [comment]
now have to fix sr3 convert to supply inflight option when it would have been the default in v2.

**Comment by petersilva** [comment]
That's done now too... PR is good to go.
