### ISSUE TITLE
sr_cpost  double posting?

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#14]
the log rotate does not seem to work and  there were cases where a file gets posted more than one time
(post with no change)

**Comment by petersilva** [comment]
fixed in 2.18.05b3
Dunno about this double posting thing...

**Comment by michelgrenier** [comment]
Because there was 5 or 6 instances of sr_cpost
Did not realized when issue was written

**Comment by petersilva** [comment]
ok... so not a real issue. closing.
