### ISSUE TITLE
Installation from Debuild Packaging Error: Ubuntu16.04

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarracenia#144]
Executables for sarracenia not in path after installing from package built with debuild

**Comment by msaraga** [comment]
They are also missing from the system, aside from inside of a temporary directory in the sarracenia git repo.

**Comment by petersilva** [comment]
that's a bobo that was introduced when I tried to make a transition package and failed miserably.
This patch: e43b332874b19ea71337af0aaedf493a5131302f broke it, found by bisecting.
It is reverted, so git pull ought to be enough.
