### ISSUE TITLE
Flow Test Requirements and Instructions Ambiguous

### ISSUE THREAD

**Issue by msaraga** [MetPX/sarracenia#145]
Need to clarify user account configurations for flow test:
-> Are tsource, tsub, tfeed and bunnymaster linux system accounts, or only amqp accounts?
-> What amqp permission profile should each user have?
-> Which user needs passwordless ssh (with own pub key in authorized_keys) ?
-> Additional requirements missing from docs?

(edited for clarity)

**Comment by benlapETS** [comment]
Sur ubuntu server 16.04 :+1: 
- Python n'est pas initialise par defaut et un quick fix a ete ln -s /usr/bin/python3 /usr/bin/python
- AMQP n'est pas a jour suite a linstallation avec apt et quick fix pip install --upgrade pip3 amqp

**Comment by msaraga** [comment]
For the python executable, just need to install python2 actually..

**Comment by petersilva** [comment]
This ticket is ambiguous ;-)  I don't know what it is about.  I don't think we should be using python2... it should all be explicitly python3, you can't link python->python3 on any system, that will break things system-wide. very bad, you wil be confused by weird stuff breaking forever.  as for ssh requirements, the requirement is to be able to login to the user running the flow test without a password... you need to setup keys for that.

**Comment by petersilva** [comment]
Does Ben's commit cover this issue:
af3bfb5c48b4fd99c02dff0e035086808003eadf
?

**Comment by msaraga** [comment]
I have edited the issue description to clarify what I was scratching my head about. I meant this one as a personal memo more than anything else, hence the confusion :)

Ben's commit doesn't specify that only the account which runs the flow test needs passwordless ssh on localhost. (I now know this is the only localhost account needed, but this isn't 100% clear in the docs either)

Additional requirements:
Python 2 needs to be installed for the rabbitmqadmin script to run.
(for the python linking, I don't know what we were thinking...)

All the details have been integrated into the flow test autoconfiguration script sarracenia/test/flow_autoconfig.sh in the branch of the same name. Will change docs and submit pull request in a bit.

**Comment by petersilva** [comment]
original description much improved. Thanks!

**Comment by petersilva** [comment]
the permission profile in AMQP is already laid out in the existing instructions, as it is set by the *role* lines devs are instructed to add to admin.conf.

declare role subscriber  hoho

declares the user hoho with the right permissions for a subscriber.
This is set up when one runs sr_audit --users foreground as already instructed.

There should be NO manual changes made using the GUI or rabbitmqadmin once the single password for the admin account is set up.  If such manual changes are needed, then a bug report should be filed.
(There might well be a problem, as only a handful of devs have exercised this code.)

**Comment by msaraga** [comment]
In the configuration instructions, should this command be run for all amqp users?
```bash
sudo rabbitmqctl set_permissions ${AMQP_USER} ".*" ".*" ".*"
```
When not run on users other than bunnymaster, things weren't working at all.

**Comment by petersilva** [comment]
nope. bad idea. it gives all users the ability to create queues and
exchanges with any name (similar to giving all users admin access.)
The regexps, as setup by sr_audit are expclicitly tailored to give role
based access (e.g declare role subscriber ) so they only get the right to
create queues and exchanges appropriate to their role on the broker.

Have a look here:

https://github.com/MetPX/sarracenia/blob/master/doc/Admin.rst#managing-users-on-a-pump-using-sr-audit

which describes in detail how this stuff should work.

**Comment by msaraga** [comment]
Ok great! I can confirm sr_audit works without explicit permission setting.
I'll close this issue since this wraps up just about all of the initial points.
