### ISSUE TITLE
Log rotation is missing some features

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#153]
As discussed with Peter, log rotation is actually only configurable with the _logrotate_ option which defines the number of maximum rotation to keep before deleting it.

After reviewing the code, I found that logrotate is confusing as it really means log life duration (number of rotation before it expires) and it should be rename to something like _log_ttl_. The default would stays at 5 rotations and the minimum would be 0 as it would disable the rotation.

We need to add an option where the user may define the interval he wants to rotate. This option would be named _logrotate_interval_ and it would be defined by **[1-9]?[0-9][dhDH]** (ie **2d**, **14H**, ...). Any combination with **0** would also disable log rotation, nothing else is accepted (ie. no, false, ...). The default rotation will be done at **midnight**

**Comment by petersilva** [comment]
logrotate_interval

**Comment by petersilva** [comment]
leave logrotate (current setting) alone... it will break existing configs to change it, although you could add a more appropriate synonym, and document it as such, but I think logrotate, and logrotate_interval is clear enough... but whatever not a big deal as long as we don´t break old configs.

**Comment by benlapETS** [comment]
For a little update, things have been documented in [sr_subscribe.1-issue153#logs](https://github.com/MetPX/sarracenia/blob/issue153/doc/sr_subscribe.1.rst#logs) this will soon be available on  [sr_subscribe.1-master#logs](https://github.com/MetPX/sarracenia/blob/master/doc/sr_subscribe.1.rst#logs), after the pull request is completed.
