### ISSUE TITLE
v03 ETCTS  parts header clarification

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#166]
given the direction from ET-CTS, it is obvious that the current formulation of the partition strategy header will not be acceptable.  I have suggested an specification here:

https://github.com/MetPX/wmo_mesh/issues/7

I think we should just implement it, and let people offer improvements.  It is so difficult to discuss things that don't exist.  Better to have something that does, then it can be tweaked.

**Comment by benlapETS** [comment]
What do we do when there is no parts. What seems to be the case for:
- Remove
- Link

**Comment by petersilva** [comment]
only the 'integrity' field is mandatory.  When integrity is 'remove' or 'link' then there are no corresponding 'size' or 'block' headers.
