### ISSUE TITLE
pulse... no longer required

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#17]
Since we have the means to check if the amqp connection is still alive  
consumer.isalive()  and publisher.isalive()    there is no more needs of having
a pulse poll to emit a dummy message to make sure the amqp connection works.

**Comment by petersilva** [comment]
hmm... dunno... if the idea is to keep the NAT connection alive, then sending a packet to avoid having the association time out sounds reasonable.  but yeah, could always just re-connect every time we figure out that the other end is dead... hmm... tough to say.

**Comment by petersilva** [comment]
Also, it gives us the *wall* feature, which I think is fun.

**Comment by petersilva** [comment]
also always good to get rid of unnecessary code...

**Comment by petersilva** [comment]
It is not there in sr3.
