### ISSUE TITLE
AMQPS in "A First Example" Documentation

### ISSUE THREAD

**Issue by jeixav** [MetPX/sarracenia#175]
[A First Example](https://github.com/MetPX/sarracenia/blob/master/doc/subscriber.rst#a-first-example) uses amqp://anonymous@dd.weather.gc.ca.

This does not seem to work. $HOME/.cache/sarra/log/sr_subscribe_dd_swob_0001.log shows:
```
2019-03-26 14:56:57,036 [ERROR] AMQP Sender cannot connect to: dd.weather.gc.ca
2019-03-26 14:56:57,036 [ERROR] Type=<class 'UnboundLocalError'>, Value=local variable 'msg' referenced before assignment
2019-03-26 14:56:57,037 [ERROR] Sleeping 5 seconds ...
```

If I switch to amps://anonymous@dd.weather.gc.ca, I do receive files. Should the example be revised?

**Comment by benlapETS** [comment]
The doc was outdated, good catch and thx for the help.

**Comment by petersilva** [comment]
@benlapETS can you push the change to master, so the fix is visible?

**Comment by petersilva** [comment]
found some more occurrence. committed and published.  Benoit found some more, coming up.

**Comment by petersilva** [comment]
caught them all, and b2 released.
