### ISSUE TITLE
If a file is put in retry, it takes at least a heartbeat interval before it is send.  Is that too long?

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#18]
The retry are reset at every heartbeat... This could lead into retry message to wait for a stretching
heartbeat time since the code auto adjust heartbeat to a greater value if required.

The retry reset   sr_retry.on_heartbeat()   could be called whenever the retry file is empty and
there are presence of  retry.new and/or retry.state...   hence getting rid of the heartbeat depedency
and hopefully  in  most cases,  catching up more quickly on small download or delivery very sparse error

**Comment by petersilva** [comment]
no, it isn't too long.  If an error happenned and we tried to do the operation three times, then waiting a decent interval is fine.  I think.
