### ISSUE TITLE
sr.py needs to be refactored

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#180]
Here are sequence diagrams of sr.py for this issue. They are identifying:
- main() procedure
![image](https://user-images.githubusercontent.com/11091581/56063991-ccfd0400-5d3e-11e9-8d81-12be7390ec40.png)
- scan_dir() and beyond procedures
![image](https://user-images.githubusercontent.com/11091581/56064008-d4bca880-5d3e-11e9-921c-1ee266f3172a.png)

Those diagrams now help to visualize what is going on in sr.py and maybe understand the synchrone part of the startup sequence. It tells us that only run_command and exec_action will be use as trigger for specific action on default programs if the config exist in .config/sarra directory

**Comment by benlapETS** [comment]
Note: During the refactoring I needed to setup the debug mode properly and it was adding an overhead in parsing arguments so I decided to add argparse to the code.

**Comment by petersilva** [comment]
A refactor has happenned for different reasons in #174. The entire sr.py code is thrown out in that issue, and the strategy is to avoid using any of the existing classes. probably can apply some ideas from here to that issue.
