### ISSUE TITLE
Logging structure is poorly designed and poorly implemented

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#185]
I suspect that the solution will required a long and thorough analysis, with a lot of examples, use cases and test cases. To really measure the size of the problem, I think I would need help of people using it in day to day to get feedback and idea:
- Peter pointed out that it would be a nice to have to be able to activate/deactivate logging in a more finer granular way so we would remove a lot of noise when trying to debug a problem.
- I encountered issues with the fact the components enable logging in different ways depending on the component and the action that seems to be random and which change during the running of the process. We then dont have a full control of what is popping out and this can be really annoying when a lot of process are running (like in the flow test). Also the log option (-l) doesnt work #186 .

**Comment by benlapETS** [comment]
#240 might be a good reference to this design problem...

**Comment by petersilva** [comment]
hey @benlapETS is this done by branch for #issue240 ( issue240_2 ) or is this something different again.  just looking to understand if we can close it as  part of the next release.

**Comment by benlapETS** [comment]
Let me take a look, I had 3 concerns here:
- (de)activating debug in finer granular way
- log option (-l) RESOLVED
- stdout/stderr redirection problem RESOLVED

**Comment by petersilva** [comment]
closing because I think you're saying it is resolved.
