### ISSUE TITLE
Cannot specify logpath (-l) from the command line

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#186]
I ran this cmd `sr_subscribe foreground -debug -l /local/ben/.cache/sarra/my_sr.log dd_ping` and this is what I get:
```
2019-04-17 13:46:12,280 [DEBUG] sr_config option ['-l', '/local/ben/.cache/sarra/my_sr.log']
...
2019-04-17 13:46:12,283 [DEBUG] sr_config user_log_dir  /local/ben/.cache/sarra/log 
...
2019-04-17 13:39:53,886 [DEBUG] Switching to rotating log file: /local/ben/.cache/sarra/log/sr_subscribe_dd_ping_01.log
```
Part of the problem is in sr_config.option() and the other part is in the fact that self.logpath get overriden after the option being parsed.

**Comment by petersilva** [comment]
likely should just remove -l option.  Advise people who want that to either use symbolic links from the default location, or set environment variables, as per freedesktop.org standard which applies.

**Comment by petersilva** [comment]
I just noticed the environment variable stuff is already explicitly documented in the sr_subscribe.1.rst manual page.

So it´s likely fine, to just remove the option entirely.

**Comment by benlapETS** [comment]
Just pushed the changes without pull request.
