### ISSUE TITLE
sr stop   takes very long on large configurations.  faster would be better.

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#19]
By adding an exponential backoff for sigterm (until a certain limit is reached than sigkill)
the sequential processing of sr.py have made stop take too long in some cases ( ~ 200 configurations 

found the max sleep limit was excessively high... corrected this morning...
parallelizing sr still a good thing.

Had to resubmit since I closed it by mistake

**Comment by petersilva** [comment]
fixed long ago... sends signals in parallel and does a collective wait and retry...
