### ISSUE TITLE
new feature : plugin pxSender_log.py  emulate sundew sender log

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#199]
This plugin IS ONLY LOGGING  NO DOWNLOAD, NO SEND

It provides a do_download to use in sr_subscribe
It provides a do_send     to use in sr_sender

And the announcement is restricted to http,ftp,sftp
it will only LOG

This interest of this plugin is that the log format is
similar to sundew's pxSender

The main purpose of this plugin is to have a tool to 
compare the routing of products between sundew and sarra

No files are actually being sent or downloaded

Sample usage:

  plugin pxSender_log.py

This is restricted to a mean to verify between logs of sundew
and logs on sarra... when the download or delivery of the products
are exactly the same on both side, taking out the plugin should
simply do the job... and let go of the sundew config

**Comment by petersilva** [comment]
sounds good!

**Comment by michelgrenier** [comment]
with a simple pxSender conversion to a sr_sender  I was inclined to think that  subtopic # would do the job because products would be routed according to the accept/reject in the config...  but  this is a mess.
1- the process receives all messages
2- some configs completely relate on the routing table and have   accept .* 

So I wrote this tool ... sundew_routing_2_sarra_subtopic.py  
In oder to get the subtopics you need to provide this tool all the routingtables (or the ones treating the sender you are working on if not as lazy as me)... 
You also need a whole day of the files on the aimed broker
 (ex. on ddi1 
cd /local/home/wxofeed/data/dd/public_data
find 20190512 -type f  > /tmp/ddi1_one_day )

You copy the one day file on the sundew server (or config server)
You cd to the  etc   directory  and run

./sundew_routing_2_sarra_subtopic.py  *Routing.conf  one_day_file  tx/senderX.conf

Will give it a try on senders after the pxatx stuff

**Comment by petersilva** [comment]
it would be good to get this sender logic committed to the master branch, so it is included
with the release.

**Comment by michelgrenier** [comment]
branch issue199 updated... the tools used in the presentation are under sarracenia/tools
the plugins under sarracenia/sarra/plugins,  the updated documentation  under
sarracenia/doc/migration ...
I hope this is good enough... back to pxatx migration :-)

**Comment by petersilva** [comment]
is the branch in mergeable shape?  if so, let me know and I will start looking at the patches.
or you could just generate a pull request.  there should be no changes that affect any thing as this is all new content, I guess.

**Comment by petersilva** [comment]
replaced by --simulate / --dry_run functionality built-in to sr3.
