### ISSUE TITLE
sr_cache: if a file is removed, and then re-created with the same content, the cache will suppress it.

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#20]
In C  the caching does not remove entries from cache except if they expire... if I well understood.
The only caveat with this is  if a file is deleted and recreated with same content... the cache will say
it was already processed... and the end result is the file is not re propagated.

in python,  there is a delete_path but it is really bad... it rewrites/clean the cache file...
so (1) could be removed from python and behave like in C
or (2) correct the python version and do it in C

This only affect sr_watch (or sr_cpost )

**Comment by petersilva** [comment]
I think this basically is "Works as designed"  I think the python is wrong on this one, if the file is deleted, it should stay in the cache.   If someone wants to erase the cache, that's a different thing. but the danger of a file being repeatedly deleted and re-created would totally avoid duplicate suppression... so it seems wrong.

I don't think this happens in v3, but I don't recall doing anything to change this... There isn't any code in sr3 to perform individual deletions.   So the behaviour is gone in sr3. and if it is present in v2, then it is not worth fixing at this point.
