### ISSUE TITLE
Log rotation distorts flow check (in flow_include.sh) counts

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#206]
It would be convenient to run flow test overnight for big sample tests, but actually the problem is that our counting in flow_include depends on logs and this introduce errors in the counting (msg, file and post) of sumlogs or, if we want to overcome, it will introduce too complex handling for each counting cases. Then, I suggest:
- to disable log rotation in every flow test config (which will resolve the problem easily)
- to design and implement test cases that cover everything we wish to test with our log rotation feature (I could create a separate issue on this)

**Comment by benlapETS** [comment]
This is how I managed to gather all the counts computed by plugins:
```
for i in file_total msg_total post_total; do for j in sr_*.log*; do grep -H "$i" $j | grep -v DEBUG | tail -1 >> test.txt; done; done;
cat test.txt | sort | less
```

**Comment by petersilva** [comment]
*invalid* tag means that the bug isn't a bug, but some kind of a misunderstanding of how the application should work... it refers to the issue being bogus, invalid... is that what you meant by putting that tag on this bug?

**Comment by petersilva** [comment]
As something to do while debugging, fine.  As a permanent change to the flow test, I don´t think it is a good idea.  would prefer to just fix the stuff that examines the logs to get the math calculated properly.

I think the flow_test should be as vanilla as possible, and disabling log rotation leaves us open to log rotation issues... and we already have something suspiciously like one of those ( https://github.com/MetPX/sarrac/issues/35 ) so would really prefer for flow test to work with default log rotation.   Eventually, @habilinour  wants to run the flow_test continuously on the dev/stage systems... perhaps with a periodic reset of some kind...

**Comment by benlapETS** [comment]
Ok no I didn't mean that, I meant that something is invalid but it is not a bug in sarra... but now my suggestion is invalid as we agree on a better solution that is to use countthem when applicable instead of sumlog in flow_include. That would also be more efficient.

**Comment by benlapETS** [comment]
Ok no I didn't mean that, I meant that something is invalid but it is not a bug in sarra... but now my suggestion is invalid as we agree on a better solution that is to use countthem when applicable instead of sumlog in flow_include. That would also be more efficient.
> _invalid_ tag means that the bug isn't a bug, but some kind of a misunderstanding of how the application should work... it refers to the issue being bogus, invalid... is that what you meant by putting that tag on this bug?

**Comment by benlapETS** [comment]
- Note1: But my suggestion on more unit test on log rotation still stand. As the flow test is an integration test it cannot be trustable to validate any cornercase test. It is like hunting a fly with an atomic bomb!!

**Comment by petersilva** [comment]
more tests == good :-)

**Comment by benlapETS** [comment]
- Note1: Here is a little script i made to better charaterize errors (or warnings), i will integrate this in flow_check
```
grep -E -h -o "\[ERROR\] *[^ ]+ [^/]|\[ERROR\] *[^ ]+ /" *.log* | sort | uniq -c | grep -v "encode_point()\|self.curve\|paramiko" | sort -r | awk '{$1=$1;print}' > test1.txt
while read p; do
 var0=`echo $p | cut -d " " -f2-`
 var1=($(grep -F -l "$var0" *.log*))
 var2=`echo $p | awk '{print $1;}'`
 echo $var2 `grep -F -m 1 "$var0" ${var1[0]} | cut -d' ' -f3-`
 echo ${var1[@]} | sed 's/ /\n/g' | grep -o -e "^.*f[0-9][0-9]" | uniq
 echo -e
done < test1.txt
```
I introduced this code in flow check to more accurate summaries

**Comment by petersilva** [comment]
sounds good.

**Comment by benlapETS** [comment]
Ok all the file_total and post_total have been switch to countthem with file_log and post_log. Couldn't do it for msg_total because there is no such msg_log, I would have to code it I guess, i am still undecided? I will start a test for the week end and see where the count are on monday for msg_total.

**Comment by benlapETS** [comment]
Note1: With some feedback that issue I added column formatting on summary output
Note2: I ran several test and the counts seem to be accurate now
