### ISSUE TITLE
"download" (aka copy) files locally

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#21]
the sr_file class in sr_file.py  could be expanded.
All modules found under  sr_sftp.py  and its class  could be defined in sr_file.py
A file_transport  class could be created...
 
 file:   could become (as sftp:) a way to download(cp) or send(cp) 

As it is now,  on_download or on_send need to be defined in plugins
to properly cp local file ... which is a little annoying... local file should be supported I would guess

**Comment by petersilva** [comment]
I kind of thought this already worked... if you sr_subscribe to a file: url, it copies the file, I think...
but not sure...

**Comment by michelgrenier** [comment]
Yes I think you are right ... Isn t it how Dominic uses it ?

**Comment by petersilva** [comment]
from an email:

> to download without using the network, I think it just works if we
> make an sr_subscribe configuration like:
>  
> lala.conf:
>  
> broker amqp://anonymous@localhost
> exchange xpublic
> base_dir /apps/sarra/public_data
> on_message msg_2local
> # on_message above changes URL from http:... to file: ...
>  
> directory /apps/px/rxq/lala
> accept <whatever>
>  
> not sure though, someone would need to test.
>
