### ISSUE TITLE
sr_poll/ sr_sarra ... etc  mismatch on file size

### ISSUE THREAD

**Issue by michelgrenier** [MetPX/sarracenia#211]

**Comment by michelgrenier** [comment]
FIX 1- Sometime there is no way of having the correct size of a file when polling... 
Currently it is mandatory to have a partflg in the message. For these cases where the size of
the file is unknown would be better to support message without partflg when it is requiered.
FIX 2- Also, when a mismatch is detected between the partflg and the actual file size (downloaded
or sent)  the partflg should be corrected to the actual file size ...

**Comment by petersilva** [comment]
@michelgrenier we have released the fixes you provided for this... Can we close this bug, or is there still other work needed for this?
