### ISSUE TITLE
bug in post_exchange_split for publishing message to multiple exchanges (ex: winnow01...20)

### ISSUE THREAD

**Issue by junhu3** [MetPX/sarracenia#231]
In sr_message.py, the following line takes the last character in the sum string and apply ord modulo the number of post_exchange_split:
           suffix= "%02d" % ( ord(self.headers['sum'][-1]) % self.post_exchange_split )

For ex: what we have noticed is that almost all messages were posted between value 3 to 12 with a post_exchange_split of 15.

**Comment by petersilva** [comment]
The encoding of checksum is hex digest.... Hence there are only 16 possible values.... They should be evenly distributed between 0 and 15....  Beyond 15 won't work with current single character method... Yup this is a problem

**Comment by michelgrenier** [comment]
to get a quasi free randomness  just have the first value from a random function than simply linearly increase the value and roll back to zero when the limit is reached... so of my head something like
    def __init__(self,parent):
          self.post_exchange_suffix = random.randint(0,parent.post_exchange_split)

def post(self,parent):
          ...cut...
          if self.post_exchange_split > 0 :
                # use current value of  self.post_exchange_suffix
                self.post_exchange_suffix += 1
                if self.post_exchange_suffix > self.post_exchange_split :
                   self.post_exchange_suffix = 0

So Each instances starts on its own splitted exchange and go onto the next each post
rolling over the possible values. That should do it fairly simply and efficiently
(somtheing to give to Benoit I guess)

**Comment by michelgrenier** [comment]
Hummm... the comment box removed my spacing so the code is all at beggining of line...
Oh well ... you can figure it all out.

**Comment by michelgrenier** [comment]
and jun's  problem is that I dont know why but most of its md5sum value ended with a number... narrowing down the randomization.

**Comment by petersilva** [comment]
Randomness is not helpful... Need items with the same check sum to go to the  same exchange for Winnowing to work.
need to use > 1 char if split > 15.

**Comment by michelgrenier** [comment]
Ah… you are right… I had forgotten its purpose.
:-(

**Comment by petersilva** [comment]
I think it is properly fixed, I changed the algorithm and now there should be no reasonable limit (stay in 2 digits) on the number of winnowing processes and the distribution is more likely to be even among them.

**Comment by petersilva** [comment]
fwiw, calculating it is 4x slower, 

```
>>> timeit.timeit( "ord('d,0ec5fa93c8415f46a461569f5052b50c'[-1])%15", number=1000 )
0.0001403780006512534
>>> timeit.timeit( "sum(bytearray('d,0ec5fa93c8415f46a461569f5052b50c','ascii'))%15", number=1000 )
0.0006160859993542545

```

**Comment by junhu3** [comment]
Worst case,we can always increase the sarra instances. If not, we can have different winnows for different sources like winnow-for-source1, winnow-for-source2,....

**Comment by petersilva** [comment]
pretty sure this is fixed.  ddsr1/2.science just still need to be upgraded, perhaps... 3/4 are OK already.
