### ISSUE TITLE
flow limit stops before cdnld retry is done

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#258]
Because of that, the flow test fails on automated build (travis-ci). We would need to count more accurately retries to ensure that we end the test only if nothing is left undone.

**Comment by petersilva** [comment]
using the size of .retry files, first with ls, and then with wc -l, one would be able to add a loop towards the end of flow_limit.sh to wait for retries to complete.  Unfortunately, I´m not sure if all retries will complete (there may be some real ones) so have to fiddle a bit.

**Comment by benlapETS** [comment]
Note1: I fixed that issue by fine tuning the delay on cclean.

Note2: Also fixed pclean by changing the source broker from xflow_public to xs_tsource. I had to remove the f91 in order to do that to avoid going into a bad loop and the consolidate checks for both tests into f90. I also had to fine tune the delay for pclean

**Comment by benlapETS** [comment]
Note1: I ran flow tests with 5000 samples and monitored closely the retries of pcleans and noticed that when the count stayed above 1000 for few minutes, that is where we begin to have delay with the flow test that was making pclean failed with unreasonable delays (100sec) where it was failing with shim library because of shim library issue. I am still unsure to report it because it is still hard to reproduce.

**Comment by petersilva** [comment]
tuning the delay is not a good approach, as it is naturally subject to many different sources of variability, such as hardware (different laptops and vm's will have different performance, affecting how processing slows down), data weather (peak periods versus gaps.), distance from source (data may move slower if one is further from the origin point.)  Once the shovels are stopped, I see the current code already checks tof the retries in progress, as I implemented this check a year ago in commit 892e8647157392ca60f65a2b7b36cc9147b297b4, when the tolerance for stuff in the retry queues was 0.   @benlapETS adjusted it in twice to first 10% and then 20% of the entire volume of the test.   This is not a good metric, as the test length grows this number will get very large.
I don't remember know why 0 wasn't fine in the first place.   Changing this metric is likely the source of the problem. I see the branch already reverts this change... will wait to see how things develop.

**Comment by petersilva** [comment]
looking ath travis, the longer tests run correctly, (24/24 tests OK) but the exit status is non-zero.
need to look into that.

**Comment by petersilva** [comment]
Seeing the same thing in the new static-flow tests, and addressed it by looping until there are no messages queued AND there is nothing in the retry queues.  static flow takes much longer to complete now, but is status is now correct. (20/20 good.)

**Comment by petersilva** [comment]
issue not present in flow tests today, closing.
