### ISSUE TITLE
try out github release feature? / Release notification mechanism broken

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#263]
metpx-devel@sf.net mailing list is now broken, we have not been putting binaries on sourceforge for a while already.  probably time to take down the old content... See if there is some value to building binary packages... not sure there is... launchpad does that better... we´ll perhaps release publishing is a better way to notify people

**Comment by petersilva** [comment]
tried publishing latest sarracenia release the usual, documented way... got 

> *Address not found*... your message wasn´t delivere to metpx-devel@sourceforge.net because the address could not be found, or is unable to receive mail.

so hard to inform people through a broken mailing list.

**Comment by petersilva** [comment]
also note, language corrections caused commit-id: 643ec6e1f4682ca4329b13a1ca1792b934db08b8
corrected an issue where two titles were given the same title, causing rst parser to freak-out, causing pypi upload to fail.   likely need to modify guides such that people must run rst2html on a file prior to committing to ensure it doesn´t crash the parser.

**Comment by benlapETS** [comment]
when travis-ci will be fine we could automate the deployment process through it...

**Comment by petersilva** [comment]
Current process is here:

https://github.com/MetPX/sarracenia/blob/master/doc/Dev.rst#releasing

It doesn't mention the letter sent to metpx-devel that is essentially a copy/paste of the changelog with a short summary, and a boilerplate tail that gives where packages can be obtained from.

**Comment by petersilva** [comment]
sample release notices here:

https://sourceforge.net/p/metpx/mailman/metpx-devel/

**Comment by petersilva** [comment]
I have been doing releases through github.  I don't know if anyone gets the announcements.
likely should have the client at least send them to the datamart mailing list.

**Comment by matthewdarwin** [comment]
Yes, I get the announcements from github.

![image](https://user-images.githubusercontent.com/26171839/71544513-78da9400-294e-11ea-88b4-c16fe034e1db.png)

**Comment by petersilva** [comment]
I guess this is working & we will do this for now.  No other better method is obvious.
