### ISSUE TITLE
v03 ETCTS size

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#272]
The last field missing from the 2019 ET-CTS meeting is the use of the size field. in v03 messages.
for the case:

v02 ... parts=1,sz,1,0,0 ... v03 size=sz

**Comment by petersilva** [comment]
note that this is already implemented in the c implementation, already released in 2.19.07

**Comment by petersilva** [comment]
after using msg_rawlog as per @benlapETS's suggestion... it was clear the v03 payload is fine.
no issue.

**Comment by petersilva** [comment]
Jan claims the messages are there. reopening.

**Comment by petersilva** [comment]
fire up a flow test check components:

* cpost (veille_f34) producing v03, has correct headers (yes, size, no partstr)

* watch (watch_f40) also is OK.

* cpump (pelle_ddX) is upconverting v02 to v03 OK, and result has size header (although value is in quotes, rather than a raw number.) this is the same as what the WMO feed should be doing, but using sr_shovel (python), rather than cpump (C)  Looking over  the configs, there is no equivalent upconversion happenning for the python implementation.  gap in coverage... hmm...

**Comment by petersilva** [comment]
OK, now using WMO_mesh_CMC configuration to download straight from the WMO sample feed,
then re-post on the local broker... and subscribe to that, and look at the raw messages in the broker GUI (so no parsing by application) and the messages are fine also.

I add msg_rawlog in the WMO_mesh_CMC configuration (subscription from the wmo sample feed) and it is still fine, there is no partstring, and there is a size header...  the rawlog is prints the AMQP body, sees, there is no processing at all... hmm...

**Comment by petersilva** [comment]
perhaps wrong exchange?

public datamart on https://hpfx.collab.science.gc.ca

the xpublic exchange is used to announce v02 format products.

The xs_pas037_wmosketch_public exchange is where the WMO v03 messages are announced.

could @josusky be looking at xpublic exchange, instead of the specialized one intended only for the WMO ?

**Comment by petersilva** [comment]
I don't know how the traffic @josusky is looking at is being generated... now looking at sample feed by using the  WMO_Sketch_2mqtt.conf sample used to pull traffic down from AMQP, and then post to a local MQTT broker.

the initial post looks fine:

`2019-10-13 10:11:38,160 [INFO] exp_2mqtt publishing topic=xpublic/v03/post/20191013T14/GTS/EBUM/IS, lag=0.000464916 body={"mode": "664", "from_cluster": "DDSR.CMC,DDI.CMC,DDSR.SCIENCE,DDI.SCIENCE", "atime": "20191013T141125.570374012", "mtime": "20191013T141125.570374012", "to_clusters": "DDI.CMC,DDSR.CMC,DDI.SCIENCE,DDI.SCIENCE", "source": "UCAR-UNIDATA", "pubTime": "20191013T141125.577322", "baseUrl": "https://hpfx.collab.science.gc.ca/~pas037/WMO_Sketch/", "relPath": "/20191013T14/GTS/EBUM/IS/ISND10_EBUM_131408_6fe5dde9fa25a5337518052b898dec9b.bufr", "integrity": {"method": "md5", "value": "b+Xd6folpTN1GAUriY3smw=="}, "size": 2651}
`

Then I subsciribe through the broker using just plain mosquitto_sub (the plain paho client, no code of mine.) and I see:
`
{"from_cluster": "DDSR.CMC,DDI.CMC,DDSR.SCIENCE,DDI.SCIENCE", "mtime": "20191013T141911.5303936", "mode": "664", "source": "UCAR-UNIDATA", "to_clusters": "DDI.CMC,DDSR.CMC,DDI.SCIENCE,DDI.SCIENCE", "atime": "20191013T141911.5303936", "content": {"encoding": "utf-8", "value": "SAIL41 BIBD 131418\r\r\nMETAR BIBD 131418Z 10005KT 9999 -RA SCT035 BKN045 07/02\r\nQ1004=\r\n\r\r\n\u0003"}, "pubTime": "20191013T141911.535184", "baseUrl": "https://hpfx.collab.science.gc.ca/~pas037/WMO_Sketch/", "relPath": "/20191013T14/GTS/BIBD/SA/SAIL41_BIBD_131418_fcd847efd70d3b168ecb1740ac83b7cf.txt", "integrity": {"method": "md5", "value": "/NhH79cNOxaOyxdArIO3zw=="}, "size": 90}

`

Which still looks fine.   I really don't get where the mal-formed messages are coming from.

**Comment by josusky** [comment]
Hi Peter, you are so fast that I cannot follow :-)
The discrepancies that I have reported were received from broker at "oflkd011.dwd.de", topic "xpublic/v03/post/+/GTS/EDZW/#".
But meanwhile Antje has reported:
"as a first step we replaced "sum" by "integrity" (MD5 base64 encoded) and added the file size as "size" (in bytes)."
so you might be hunting an already fixed bug ... or you really lost me here.

**Comment by josusky** [comment]
Hi Peter,
here is a brief update, when I subscribe (with paho_c_sub) to the broker mentioned above the received messages look like this:
Example 1
{
   "to_clusters" : "DDI.CMC,DDSR.CMC,DDI.SCIENCE,DDI.SCIENCE",
   "mode" : "664",
   "source" : "UCAR-UNIDATA",
   "sum" : "d,ad5e8cd9729caf81483f954442d1b3d9",
   "from_cluster" : "DDSR.CMC,DDI.CMC,DDSR.SCIENCE,DDI.SCIENCE",
   "atime" : "20191016T061606.178546429",
   "parts" : "1,177,1,0,0",
   "mtime" : "20191016T061606.178546429",
   "baseUrl" : "https://hpfx.collab.science.gc.ca/~pas037/WMO_Sketch/",
   "pubTime" : "20191016T061606.181493",
   "relPath" : "/20191016T06/GTS/EDZW/SA/SADL43_EDZW_160600_RRA_ad5e8cd9729caf81483f954442d1b3d9.txt",
   "integrity" : {
      "value" : "rV6M2XKcr4FIP5VEQtGz2Q==",
      "method" : "md5"
   }
}
 
Example 2 
{
   "pubTime" : "20191016T061715",
   "relPath" : "20191016T06/GTS/EDZW/IS/A_ISMI99EDZW160600_C_EDZW_20191016061601_00283024",
   "size" : 420,
   "baseUrl" : "http://oflkd011.dwd.de/wmo/data",
   "integrity" : {
      "value" : "IjpEqvD7z3xyDbxsJIUtrA==",
      "method" : "MD5"
   }
}

**Comment by petersilva** [comment]
So... I think I was really confused, and I should slow down.  I thought you were comparing messages acquired using an AMQP client of yours that connected to hpfx.collab.science.gc.ca. to those produced in MQTT on oflkd011.dwd.de, but I now I think that all the messages were acquired via a single mqtt subscription from the .de server?  and you just saw two different types, the UNIDATA ones looking like mine (example 1), and the other ones being original German ones (example 2), so your comments were related to different messages received over the same MQTT feed?  is that right?

**Comment by josusky** [comment]
Yes, that’s right. Different format of messages from the same broker.

**Comment by petersilva** [comment]
OK.  I am going to check on my side a little more.  I do not yet understand how they could get such messages (with parts instead of size)

**Comment by petersilva** [comment]
OK, so the other broker was using obsolete (a few months old) code to upconvert v02 messages.
now that they are using native v03, it´s fine. closing ...
