### ISSUE TITLE
option for sr_poll to only poll when has_vip.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#29]
The sr_poll do_poll script executes on all participants in HA configs (whether or not has_vip is True). In the original use case, the poll script must execute on the backup node to keep the ''ls'' state uptodate on the backup nodes so that only files which haven't been transferred come over when a failover occurs.

in many other (almost all) cases, one really wants to run the poll script only on the active node.
so should add a option to sr_config.py

poll_runs_on_all_nodes (default: False)

and set it to true for the (original) NWS case, but have the default be False.

import of feature request #66 from sourceforge.

**Comment by petersilva** [comment]
simpler answer is perhaps just add a plugin entry point:

on_poll_no_vip

change so that on_poll runs only when it has the vip;

on_poll_no_vip runs when it does not have the vip.

To have something run all the time, specify the same routine for both entry points.

**Comment by petersilva** [comment]
Noureddine has me convinced that it already works the way most people expect (only runs on_poll when has_vip is True) so I might be confused, and this is just a low priority enhancement, rather than a bug.

**Comment by habilinour** [comment]
poll  with do_poll updates "ls state" file and posts the messages regardless the VIP. Users should be aware they need to add some extra code to the plugin to avoid posting the same file by different nodes in the same cluster of only node is supposed to post the file. he man page does not mention that issue or behavior.

**Comment by habilinour** [comment]
but this means  the "ls state" file would not be updated. Is this what we should expect??? If the VIP moves to another node, the process would post whatever is  found in the destination directory!!!

**Comment by petersilva** [comment]
that's why the poll has to run on both nodes, or the state files are supposed to be shared... on pxatx... the nodes shared disk, so having one side poll was good.  in this case, I gather the disk is not shared.  not clear what should be done... a winnow?

**Comment by petersilva** [comment]
I think the if it does not have the vip, it should not publish... but it should still poll... It is weird that it is publishing on both sides.

**Comment by habilinour** [comment]
I agree. The active node should poll  but it should not publish.

**Comment by petersilva** [comment]
I think that is how it already works... are you saying that sr_poll does not work this way already? or that a plugin is doing something that breaks this logic?

**Comment by habilinour** [comment]
if the poll does not have do_poll plugin, it works as expected, both nodes poll but only the active one does the publish. If the poll has do_poll plugin, both nodes poll and publish. The plugin has to test if the node has the VIP to avoid publishing if it is not the active one.

**Comment by petersilva** [comment]
OK so the answer here (for now) is to modify the plugin to check whether it has the vip or not ?

**Comment by habilinour** [comment]
yes

**Comment by petersilva** [comment]
yeah, I´m looking at sr_poll in v2, and the do_poll processing is the one that does the posting... so if you put a plugin to replace it, you need to write each plugin to pay attention to whether it has the vip or not.

**Comment by petersilva** [comment]
once the parent tests if it has the vip, what does it do?  In the v2 API the plugin returns True/False or nothing... (void) there is no way for the parent to post messages it doesn´t have.

**Comment by habilinour** [comment]
It makes sense

**Comment by petersilva** [comment]
so for now... people writing plugins need to run self.has_vip() or parent.has_vip() before they post... and in v03, the polls just return a list of messages, so we can check has_vip() in the parent.... so for v02, no fix is expected, but I will add v03 tag so that it gets fixed there.

**Comment by petersilva** [comment]
users don't need to do anything about has_vip and parallel polls, etc...

**Comment by petersilva** [comment]
sr3 works this way naturally.
