### ISSUE TITLE
binding not updated when adding new subtopic

### ISSUE THREAD

**Issue by junhu3** [MetPX/sarracenia#301]
For ex, we have a sender q_something and originally we have 2 subtopic but when adding a new subtopic and restarted the sender process, the binding is not added in the queue. For we have to manually adding the new subtopic in the queue or cleanup/delete/restart the queue.

**Comment by junhu3** [comment]
It's fixed in the new version

**Comment by petersilva** [comment]
I think this only happens when there is some mismatch in queue parameters, like durable=no vs. yes... then the bindings may fail... Did you see any binding or other failures during startup when this happens?
