### ISSUE TITLE
[WARNING] extended option file_rxpipe_name = ['<fname>'] (unknown or not declared)

### ISSUE THREAD

**Issue by endlisnis** [MetPX/sarracenia#311]
I'm using v2.20.2b2, with file_rxpipe_name, but every time I start, I get this warning:
`2020-02-22 11:42:38,898 [WARNING] extended option file_rxpipe_name = ['/home/rolf/weather/rxpipe'] (unknown or not declared)`

The program (mostly) works after that.  I do get sporadic pipe errors as well, but I feel those are unrelated and I will report those separately.

Here is the conf file that I use:

broker amqps://anonymous:anonymous@dd.weather.gc.ca/

subtopic observations.swob-ml.#

mirror True
reject .*/partners/.*
reject .*/moored-buoys/.*
accept .*

use_pika False

file_rxpipe_name /home/rolf/weather/rxpipe
on_file file_rxpipe

**Comment by petersilva** [comment]
the documentation perhaps isn't great... You need to create the named pipe, using a command like so:
`
mknod /home/rolf/weather/rxpipe p
`

then start the subscriber, and you chould be able to read the file names from the pipe.

**Comment by petersilva** [comment]
working on the error message also...

**Comment by petersilva** [comment]
v2.20.02b3 has the fix to suppress this warning.  when you get a chance, you should upgrade and confirm. thanks.

**Comment by endlisnis** [comment]
I tried v2.20.02b3 and I no longer see the error.  Thanks.
