### ISSUE TITLE
time is out of sync on some servers in dd.weather.gc.ca cluster

### ISSUE THREAD

**Issue by matthewdarwin** [MetPX/sarracenia#317]
Go to 
http://zamez.org/httplint?url=https%3A%2F%2Fdd.weather.gc.ca

Keep hitting refresh.  Notice the time is off by a lot sometimes, and definitely doesn't go up second by second.

Is NTP running on all the servers correctly?

**Comment by petersilva** [comment]
fixed now... they tell me.

**Comment by matthewdarwin** [comment]
Thanks, looks good.
