### ISSUE TITLE
Instance missing - Keeping sr_subscribe alive

### ISSUE THREAD

**Issue by gastoneb** [MetPX/sarracenia#319]
[This issue has also been posted on the [meteocentre forum](http://meteocentre.com/help/msc-open-data/43/sr_subscribe-workers-keep-failing).]

I run `sr_subscribe my_config start` to download a dataset that gets updated daily. But every couple days, sr_subscribe hangs and I get `sr_subscribe my_config 01 instance missing` (I have 4 instances) when I check sr_subscribe status. Then I have to manually restart sr_subscribe. I get the same behaviour on Windows and on Linux machines. 

My current workaround has been to schedule a script that calls `sr_subscribe my_config start` once a day, but that's kind of hacky. Does anyone know why sr_subscribe falls over like this? What does "instance missing" mean? Is there a way to keep sr_subscribe alive? Is this what sr_audit is meant to solve? If sr_audit is meant for this purpose, could you please update the sr_subscribe docs to explain that audit and subscribe should usually be run in conjunction? (I didn't find anything useful on [the subscribe getting started page](https://github.com/MetPX/sarracenia/blob/master/doc/subscriber.rst).) Thank you!

**Comment by petersilva** [comment]
you can automate this with:
```
sr start

```

which will start up an sr_audit process which runs *sr sanity* every five minutes or so.
*Sr sanity* does sanity checks, looks for missing processes, and/or logs that have not been written to in a while, and starts up or restarts any missing or stuck instances.

I didn't know about the open data forum.  I just joined. Thanks!

**Comment by gastoneb** [comment]
Good to know. Thanks I will try that!

**Comment by petersilva** [comment]
I can't answer on the forum yet... awaiting approval.

**Comment by petersilva** [comment]
This still should not be happenning, but it is hapenning to everyone... so it is a real bug.  old versions used to be tougher than this.

**Comment by gastoneb** [comment]
`sr start` seems to work well for me on Linux. On my windows build though, I still have to manually intervene once a day to resuscitate sr_subscribe. I have a client who I've set this up for on Windows, and his anecdotal experience is you have to keep your shell open to keep it alive.

**Comment by petersilva** [comment]
oh... windows... less tested environment... yes... @benlapETS ?  I remember I had this issue that if I start it up manually from a command shell, it exits when I exit the shell. but I think people need to create a service? or something?  Did you have this working?

**Comment by petersilva** [comment]
the windows aspect is not addressed, but v2.20.04b2 subscribe should crash less on Linux.  If you could upgrade and see if  sr_audit has less restarting to do, that would be helpful.

**Comment by benlapETS** [comment]
@gastoneb there is a way to keep the process alive documented here:
https://github.com/MetPX/sarracenia/blob/master/doc/windows/Windows.rst#running-sarracenia-without-a-command-prompt

 try this and give us some feedback!

**Comment by petersilva** [comment]
added commit a1bd18b94ea5f39809c67d57fce460cdc7ab0e41 to make windows manual, systemd integration, and use of sr command more prominent.

**Comment by gastoneb** [comment]
That should work @benlapETS .
