### ISSUE TITLE
What causes ".1" files?

### ISSUE THREAD

**Issue by gastoneb** [MetPX/sarracenia#322]
On some occasions my sr_subscribe job downloads a file with the ".1" extension. E.g. `CMC_geps-raw_VGRD_TGL_10m_latlon0p5x0p5_2020031712_P270_allmbrs.grib2.1`. Usually a couple times per day out of 1200 file downloads. There is an actual grib2 file there too, but the file is always incomplete. I have to manually delete the grib file and rename the ".1" file to remove the suffix. 

Is there any way sarracenia can handle this automatically? Do you know what is causing this?

**Comment by petersilva** [comment]
you config includes 

accel_wget

and wget, by default will not overwrite files.  I think you need the " --backups=1  " option on wget, as per here:
https://stackoverflow.com/questions/30418188/how-to-force-wget-to-overwrite-an-existing-file-ignoring-timestamp

above the *plugin accel_wget*  line in your config, try adding:
```
accel_wget_command wget --backups=1

```

**Comment by petersilva** [comment]
you might need /usr/bin/wget --backups=1 ... (with the path... not sure)

**Comment by gastoneb** [comment]
Thanks Peter. I only used the accel_wget file because I saw it in an example config file. Downloads are fast enough without the option, so I will delete the line.

**Comment by petersilva** [comment]
great! fwiw... the buit-in python stuff will consume a little more cpu on your side, that's really the only downside.
