### ISSUE TITLE
Provide specific messages for reasons for binding errors.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#324]
Binding calls fail for a number of reasons.  some are innocuous (binding already exists) some are a big deal (mismatched characteristics.)  We need detailed error messages to tell the difference between the two cases.

examples:   mismatched expiry, durable, etc... could mean that binding topics do not happen, and feed will not work.

**Comment by petersilva** [comment]
around line 476 in sr_amqp.py is the problem... need more in the try/except.

**Comment by benlapETS** [comment]
There is nothing there, we would need more accurate infos:
![image](https://user-images.githubusercontent.com/11091581/78370634-e83ad200-7594-11ea-9c59-013e76f1e9b6.png)

**Comment by benlapETS** [comment]
every bind calls are correctly managed at the higher level :
> line 530
```
                try:
                    self.bind(exchange_name, exchange_key)
                    last_exchange_name = exchange_name
                    bound += 1
                    continue
                except AMQPError as err:
                    self.logger.error("bind queue: %s to exchange: %s with key: %s failed with %s"
                                  % (self.name, exchange_name, exchange_key, err))
                    self.logger.error("Permission issue with %s@%s or exchange %s not found."
                                  % (self.hc.user, self.hc.host, exchange_name))
                    self.logger.debug('Exception details:', exc_info=True)
                except Exception as err:
                    self.logger.error("Unexpected error: {}".format(err))
                    self.logger.debug("Exception details:", exc_info=True)
```
> line 553
```
            try:
                self.bind(last_exchange_name, exchange_key)
            except AMQPError as err:
                self.logger.error("bind queue: %s to exchange: %s with key: %s failed.."
                                  % (self.name, last_exchange_name, exchange_key))
                self.logger.error("Permission issue with %s@%s or exchange %s not found with %s"
                                  % (self.hc.user, self.hc.host, last_exchange_name, err))
                self.logger.debug('Exception details:', exc_info=True)
            except Exception as err:
                self.logger.error("Unexpected error: {}".format(err))
                self.logger.debug("Exception details:", exc_info=True)

```
If one is getting Unexpected error it is a catch all exception care we need to gather more info on the real exception thrown to adapt our handle, please run in -debug to get more detail msg.
If one is using ctrl-^c or mess with the signals I dont garanty what will happen as we dont want to  catch BaseException, this is just bad coding practice that must be remove from sarracenia.

BTW we could investigate using BaseException to see what is happening and then we would take action to correct that bad behaviour. But if the binding still fails silently then the problem is definitly not there.

**Comment by petersilva** [comment]
experimenting... started up static_flow, and let it run... after it was done... I played with sr_shovel rabbitmqtt_f22 ...  If i add durable to the config (after it already exists) I get:

```
020-04-15 17:46:44,760 [ERROR] sr_amqp/build, queue declare: q_tsource.sr_shovel.rabbitmqtt_f22 failed...(tsource@localhost) with Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'q_tsource.sr_shovel.rabbitmqtt_f22' in vhost '/': received 'false' but current is 'true'
2020-04-15 17:46:44,760 [DEBUG] Exception details: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarra/sr_amqp.py", line 568, in declare
    self.qname, msg_count, consumer_count = self.channel.queue_declare(self.name, passive=False,
  File "/usr/lib/python3/dist-packages/amqp/channel.py", line 1148, in queue_declare
    return queue_declare_ok_t(*self.wait(
  File "/usr/lib/python3/dist-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/usr/lib/python3/dist-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/lib/python3/dist-packages/amqp/connection.py", line 511, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/lib/python3/dist-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/lib/python3/dist-packages/amqp/connection.py", line 517, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/lib/python3/dist-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/lib/python3/dist-packages/amqp/channel.py", line 279, in _on_close
    raise error_for_code(
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'durable' for queue 'q_tsource.sr_shovel.rabbitmqtt_f22' in vhost '/': received 'false' but current is 'true'
2020-04-15 17:46:44,760 [INFO] reading from to tsource@localhost, exchange: xs_tsource
20
```

so already a good error message... but it does not fail... it just goes blithely on...
```

020-04-15 17:50:56,072 [DEBUG] using channel_id: 3
2020-04-15 17:50:56,073 [DEBUG] Channel open
2020-04-15 17:50:56,073 [DEBUG] declaring queue q_tsource.sr_shovel.rabbitmqtt_f22
2020-04-15 17:50:56,073 [DEBUG] queue_declare AMQP or AMQPLIB is used
2020-04-15 17:50:56,073 [DEBUG] Channel open
2020-04-15 17:50:56,073 [ERROR] sr_amqp/build, queue declare: q_tsource.sr_shovel.rabbitmqtt_f22 failed...(tsource@localhost) with Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'q_tsource.sr_shovel.rabbitmqtt_f22' in vhost '/': received '672000' but current is '300000'
2020-04-15 17:50:56,073 [DEBUG] Exception details: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarra/sr_amqp.py", line 568, in declare
    self.qname, msg_count, consumer_count = self.channel.queue_declare(self.name, passive=False,
  File "/usr/lib/python3/dist-packages/amqp/channel.py", line 1148, in queue_declare
    return queue_declare_ok_t(*self.wait(
  File "/usr/lib/python3/dist-packages/amqp/abstract_channel.py", line 88, in wait
    self.connection.drain_events(timeout=timeout)
  File "/usr/lib/python3/dist-packages/amqp/connection.py", line 505, in drain_events
    while not self.blocking_read(timeout):
  File "/usr/lib/python3/dist-packages/amqp/connection.py", line 511, in blocking_read
    return self.on_inbound_frame(frame)
  File "/usr/lib/python3/dist-packages/amqp/method_framing.py", line 55, in on_frame
    callback(channel, method_sig, buf, None)
  File "/usr/lib/python3/dist-packages/amqp/connection.py", line 517, in on_inbound_method
    return self.channels[channel_id].dispatch_method(
  File "/usr/lib/python3/dist-packages/amqp/abstract_channel.py", line 145, in dispatch_method
    listener(*args)
  File "/usr/lib/python3/dist-packages/amqp/channel.py", line 279, in _on_close
    raise error_for_code(
amqp.exceptions.PreconditionFailed: Queue.declare: (406) PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'q_tsource.sr_shovel.rabbitmqtt_f22' in vhost '/': received '672000' but current is '300000'
2020-04-15 17:50:56,074 [INFO] reading from to tsource@localhost, exchange: xs_tsource
2020-04-


```

so also a good error message. but it does not treat this as catastrophic.

**Comment by petersilva** [comment]
OK with the patch, it no longer ignores declare errors.   Does anybody rely on ignoring such errors?

**Comment by petersilva** [comment]
@habilinour  reports, this error should not cause looping... To be confirmed:

`sr_sarra_get_japan_grib2_03.log:2020-04-16 03:51:47,019 [ERROR] sr_amqp/build Type: <class 'amqplib.client_0_8.exceptions.AMQPChannelException'>, Value: (406, "PRECONDITION_FAILED - inequivalent arg 'x-expires' for queue 'q_feeder.sr_sarra.get_japan_grib2.SHARED' in vhost '/': received '86400000' but current is '604800000'", (50, 10), 'Channel.queue_declare') `

**Comment by petersilva** [comment]
Another error in ops... we need to ignore?:

```
r_poll_wifs_grib_01.log:2020-04-16 12:42:00,638 [ERROR] could not declare exchange xs_NOAA-WIFS (NOAA-WIFS@localhost) 
sr_poll_wifs_grib_01.log:2020-04-16 12:42:00,638 [ERROR] Type=<class 'amqplib.client_0_8.exceptions.AMQPChannelException'>, Value=(403, "ACCESS_REFUSED - access to exchange 'xs_NOAA-WIFS' in vhost '/' refused for user 'NOAA-WIFS'", (40, 10), 'Channel.exchange_declare') 
Enter your message

```

This one is for exchanges... not changed yet, but is truly harmless... because subsequently, if there is an issue with posting, it will loop there... so leave as-is?

**Comment by petersilva** [comment]
we can turn the exchange declaration error into a warning priority...

**Comment by benlapETS** [comment]
I see that this error happened with amqplib client... is there also an example with amqp client or maybe it handles it differently ?

**Comment by petersilva** [comment]
with the last patch, declaration failures can be avoided by explicit option, so if there was a case in use depending on going through failures, they can just add *declare_queue off* to their config and still it will work.  by default, it will now loop on queue declaration errors.  People should fix them.

**Comment by petersilva** [comment]
The current try/except logic, will print the message regardless of the specifics of the library... so it is likely OK as-is.

**Comment by michelgrenier** [comment]
from the old days... amqp limitation : once a queue is created with its options (durable,...etc), none of these options can be modified thereafter... this is amqp...

The bindings are different and can be changed...  Something that was missed at the time, and unless you changed it, sarracenia did not keep a list of -last- bindings on disk and manage the deletion of obsolete bindings when a modified config is read in...

To change a queue's options at the old state of things one would : 

copy original consuming config and give it another name like _2 suffix (x_2.conf). 
Modify queue options, modify  queue name  with _2 suffix too
start new consuming process

As soon as one product is processed by newer config : 
stop old process, and delete its queue.

**Comment by petersilva** [comment]
yes... we just need to do it for several hundred configs on 12 brokers at the same time.

**Comment by petersilva** [comment]
good in 2.20.04b3.
