### ISSUE TITLE
sr_subscribe status ... does nothing and freezes forever

### ISSUE THREAD

**Issue by endlisnis** [MetPX/sarracenia#326]
I run 10 instances.  I was having some network trouble, and only 2 of the threads were running.  I ran "python3.7 /usr/local/bin/sr_subscribe stop ../rolf.conf" and then "python3.7 /usr/local/bin/sr_subscribe status ../rolf.conf" but the status command just hung there forever.

Now trying to start or check the status just sits there.  The command never ends, and there is no output.

**Comment by petersilva** [comment]
I see that if the thing reading the named pipe is stopped.  If you start your named pipe again, is it better?

**Comment by petersilva** [comment]
If this is what I think it is... the named pipe plugin is read (as are all configs) and it tries to open the pipe as part of initialization.  so it will work when the thing reading the pipe is running, and hang when it isn´t... but I could be wrong, hence the request for the confirmation of behaviour.

**Comment by endlisnis** [comment]
I think the pipe got into a weird state.  It could not be read from, or written to; and I had to restart my system to resolve the problem.  But I find it strange that I couldn't even START the service while the pipe was broken.  I would have expected to be able to start the service, and just have each instance blocked on trying to write to the pipe.  No log entries were produced while this was happening.

**Comment by petersilva** [comment]
I wrote fix and the patch number and it auto-closed... that's a bit to uh... self-confident for me...

yes. I think I should re-write the plugin to only open the pipe when actually writing to it... currently it opens the pipe for writing when the module is initialized.  I should probably change that. OK didn't take that long... just copy the one from the repo, to your ~/.config/sarra/plugins, and it should not hang anymore...

https://github.com/MetPX/sarracenia/blob/master/sarra/plugins/file_rxpipe.py

It will be included in the next version.

**Comment by petersilva** [comment]
Please re-open if this isn't solving your problem.

**Comment by petersilva** [comment]
I just re-opened... please confirm that it solved your problem, then close.  I don´t like auto-closing...

**Comment by endlisnis** [comment]
I'm fine with closing this one without confirmation.  Because I'm not in that situation anymore.  If it every happens again, I'll re-open.
