### ISSUE TITLE
sr - add hostname on default queue name

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#33]
pattern: 
queue_name q_${BROKER_USER}.${PROGRAM}.${CONFIG}.${HOSTNAME}

shows up in a lot of definitions in the DDSR cluster, where there are 8 worker nodes, and 1 broker.
...
I don't know about this. If you have multiple nodes and a shared file system, which is a pretty common case, putting the hostname in there will cause them to use separate queues. it isn't clear that it is smart to change that default... but there are specific cases where it is clearly desirable.

on ddsr clusters, where we have multiple nodes and NO shared disk, the hostname in queue names is clearly always necessary.
...
on DDSR now that each node has it's own broker, the HOSTNAME should not be in the queue names.
but it is still often useful.   It is a common thing, but whether it should be the default is a question... i dunno.
...
was: https://sourceforge.net/p/metpx/feature-requests/58/

**Comment by petersilva** [comment]
dummest version: have a setting 

Queue_name_includes_hostname  on|off

?

**Comment by petersilva** [comment]
when is not having the hostname in the queue helpful?   

* when you have a whole bunch of shared-nothing nodes (no common disk) that share download responsibilities from a common broker.  This would be all the ddsr transfer nodes, for example.  They should not have hostnames in the queue name when consuming from the shared broker.

* in case multiple nodes downloading together, where you have a shared ~/.cache, you need to use statehost=True to split it out, per node, and then you want shared (no hostname) in the queue name as well.

* if you have an HA configuration, where multiple nodes are sharing a vip, then having the hostname in the queue is counter productive.

So in lots of complicated clustering cases, it is better not to have a hostname... but you could declare a *cluster* name,
and have that used, when specified to override the hostname.

In cases where all consumers are on a single host, which is very common for clients,

**Comment by petersilva** [comment]
@junhu3 @habilinour @kurt2x   We are close to being able to do a release... could implement this enhancement easily if there was a consensus for it... but I don´t get what to do yet.  If we add a default where it uses the hostname, but when a cluster is specified, we use that instead... does that make sense to people?

**Comment by petersilva** [comment]
example: 

today, default is: queue_name q_${BROKER_USER}.${PROGRAM}.${CONFIG}

according to proposal, new default would be:

queue_name q_${BROKER_USER}.${PROGRAM}.${CONFIG}.${HOSTNAME}

except when cluster is specified, when it would be:

cluster goc-dx
queue_name q_${BROKER_USER}.${PROGRAM}.${CONFIG}.${CLUSTER}

so with goc-dx, where we have goc-dx1 and goc-dx2... the queue_name would always list goc-dx.
but if you leave out the *cluster* directive, it will add the hostname, which will change the default queue to
be different on the two nodes.

the *cluster* directive could be in default.conf and overridden for particular configs when HOSTNAME is really wanted.

**Comment by petersilva** [comment]
or just call it hostname (to override the fqdn?)

**Comment by habilinour** [comment]
Specifying the cluster name in the config to override the hostname in default.conf makes sense.

**Comment by petersilva** [comment]
@kurt2x  maybe you're interested in commenting on this?

**Comment by petersilva** [comment]
I don't like messing with hostname because hostname might also be used as a directory in state file storage.  so settings like overriding HOSTNAME, or having a vhostname would probably be confusing.  cluster is ok, I guess.  other names for this concept:

share_group, share_with, share, team, grappe, 

whatever it is called, the value defaults to the hostname, and you can override it in any config file.... I starting to like *grappe* It is the usual french word for "cluster" ... but it refers to fruits on a vine, which strikes me as more organized, like their on the same team or grouped together... it gives the idea of sharing more than "cluster" does, which doesn't imply any team work... just that a bunch of things are in the same area.

so something like:

grappe hoho

and the default for queuename includes ${GRAPPE} so when people want shared downloads,
they override *grappe*.

I dunno.

**Comment by petersilva** [comment]
grappe also is a bit similar to *group* ... so it provides a bit of a hint.

**Comment by andreleblanc11** [comment]
I think I actually like `group` better than `grappe`. AFAIK I don't think it's already a config option. I think that grappe would be confusing to anybody not already familiar with french or vineyard terminology lol.

I think also the idea would be to set this variable inside of `default.conf`?

**Comment by petersilva** [comment]
* The problem with *group* is that it is already used a lot, and so is easily confused with unix groups (like a gid thing.) and process groups and this is neither of those... it's a label used to group instances that will share a common queue to download data from a queue that is shared between them.
*  It's like people pulling together on a rope, being on a chain gang, or operating in synchrony like a flock of starlings.   
* This identifier is only used when talking to a broker. In amqp it would be part of the queue_name, in mqtt it would be part of the share-id...  
* some other collective noun would be ok: flock (of birds), shoal (of fish), gang (of workers), team, gaggle (of geese), fleet (of ships), herd (of sheep), band (of musicians), choir (of singers), pack (of wolves), prid (of lions)... bunch (of grapes, flowers, ... the thing is called sarracenia... which is a flowering plant.) swarm of bees. parade (of elephants?)

"Yes, we get groves, stands, lawns, copses, hedgerows, shrubberies, spinneys, thickets, coppices and brakes — all anonymous assemblages of nobody-cares-which plants. "  -- https://medium.com/@andy_murdock/soon-to-be-rejected-new-collective-nouns-for-plants-6423000c5807#:~:text=Yes%2C%20we%20get%20groves%2C%20stands,barrens%2C%20peat%20bogs%2C%20heath.

You want a word that is a bit of a hint as to what it's about without being confusing to overuse of common words for different uses.  It would be nice if it indicated synchronicity, working together smoothly.... like a flock of starlings

maybe "gang"  (chain gang) kind of negative... maybe choir ? fleet? give the idea of moving together with common purpose.

**Comment by petersilva** [comment]
or add another word "flowGroup" ... subscribeGroup, transferGroup, ...

**Comment by petersilva** [comment]
grove ( of sarracenia ) ? multiple sarracenia working together?

**Comment by reidsunderland** [comment]
I'm confused, because the default queueName is unique already: `q_<brokerUser>.<programName>.<configName>.<random>.<random>`.  I don't see any harm in adding hostname to that (or replacing one of the random numbers with hostname?). 

It might be an issue if you're on a cluster using shared storage and not using statehost, but I think there would still be a race condition in that case with the existing default using random numbers anyways.

**Comment by reidsunderland** [comment]
I do think adding some kind of cluster name variable that we could define in default.conf and then use in a custom queueName could be useful.

But what @junhu3 and I were wanting is to add the hostname to the default queueName that gets generated by sr3 when you don't specify any queueName in your config or default.conf.

**Comment by petersilva** [comment]
## Why HOSTNAME is a problem in share environments.

If you are subscribing in an environment with a shared home (very common in HPC.) then you can have multiple nodes sharing the download queue... that would be the normal default.  but if you have HOSTNAME in the default queue... they will all declare different queues... and instead of sharing, they will be downloading everything redundantly and independently.

Another thing that could happen when .cache is shared ... is that the first host on which the subscribe is started will declare the queue, and then the other hosts will use it... not actually being on the host in question.  so the first guy that starts up is on host1, and then the other instances are on host3 and host4, but they would read the queue setting that says host1 and use that.  I think that would be more confusing than helpful.

## Why *cluster* isn't enough...

Even if you have a cluster declaration, in cases like ddsr, there are some shared subscriptions among the nodes (where hostname is inappropriate) and some on that need to be local (where it is better using a local broker.) in both cases, HOSTNAME is unhelpful.

There are lots of other cases in clusters where HOSTNAME is helpful.

**Comment by petersilva** [comment]
What about a keyword:    *sharing*  that can have values:  "${HOSTNAME}", "${CLUSTER}", or something else.  *sharing* defaults to ${HOSTNAME} but overrides allow arbitrary values.

We could also get rid of the random-id's if that's helpful... or include them in the sharing part.

**Comment by reidsunderland** [comment]
> If you are subscribing in an environment with a shared home (very common in HPC.) then you can have multiple nodes sharing the download queue... that would be the normal default. but if you have HOSTNAME in the default queue... they will all declare different queues... and instead of sharing, they will be downloading everything redundantly and independently.

We will have the same issue with the default queue names using random numbers too, whether hostname is in the queue name or not.

`q_<brokerUser>.<programName>.<configName>.<random>.<random>`

With a shared home and **no queueName defined in the config**: 
- if statehost is true every node will create its own queue with different random numbers.
- if statehost is false, whichever node starts up first will write the qname file to the .cache on the shared home and *hopefully* every other node will read that file and use the same queueName. But you could get conflicts if they all start up at the same time and try to read/write the qname files. 

--- 

The sharing (or `sharedQueue` ?) option seems like a good solution. I think keeping at least one of the random ID's is probably a good idea.

There's a chance of conflicts with a queuename like `q_anonymous.subscribe.dd_swob.bobs-pc`

**Comment by petersilva** [comment]
*queueShare* ... is more consistent with other variables and groups it with the queue settings... seems right ... I actually found the half-implemented queue_suffix in the code.

for the race condition with multiple nodes, it's a good point... we could add locking to get around that.

Another thought about the random id's ... it helps with security when people cannot guess your queue names ... maybe the randomizing helps... not sure.

**Comment by petersilva** [comment]
I implemented something:

```

SSC-5CD2310S60% sr3 show subscribe/hpfx_citypage | grep queueName
2024-07-16 16:23:20,874 70327 [INFO] sarracenia.config parse_line ./hpfx_citypage.conf:26 if download is false, directory has no effect
2024-07-16 16:23:20,876 70327 [INFO] sarracenia.flow metricsFlowReset looking for old metrics for /home/peter/.cache/sr3/metrics/subscribe_hpfx_citypage_00.json
 'queueName': 'q_anonymous_subscribe_hpfx_citypage_peter_SSC-5CD2310S60.',
SSC-5CD2310S60%

```

queueShare defaults to "${USER}_${HOSTNAME}"

I think that's super useful when you have many people on the same machine.
There might be security objections, but I think they are defused because they are
under user control.  The user can choose to use any other string... and in any event the entire purpose of these names is to help us identify the owner for support reasons, so it seems reasonable to me.

I'm just unsure what things will be broken by this default.

**Comment by petersilva** [comment]
I found some conflicts between documentation and implementation.  
documentation says:
```
By default, components create a queue name that should be unique. The default queue_name components create follows the following convention:

q_<brokerUser>.<programName>.<configName>.<random>.<random>

```
using periods as spacing... but when I look in the code... It was using underscores.
if anybody has any opinions now is a good time.

**Comment by petersilva** [comment]
* After a good discussion, consensus default for queueShare is: ``${USER}\_${HOSTNAME}\_${RAND8}"
* periods as spacing confirmed.

branch updated to implement.

**Comment by reidsunderland** [comment]
I found the commit that changed the default queueName from `q_username.component` to `q_username_component`. 

17ee5d0cfd8ef20ccb376c9714624ea192e94939


```diff
-                    queue_name = 'q_' + self.broker.username + '.sr_' + component + '.' + cfg
+                    queue_name = 'q_' + self.broker.username + '_' + component + '.' + cfg
```

**Comment by petersilva** [comment]
@petersilva didn't explain much about why he made that change... It looks like he just removed three "extraneous" letters ... '.sr' from the string... not really intending to change any delimiter but just getting rid of extra unneeded ones... it could have been '.' and done the same deed... dunno why it's that way.

**Comment by petersilva** [comment]
That same patch shows that *anonymous* user is treated specially.  It might not be weird to default to using RAND8 only in anonymous case...
