### ISSUE TITLE
rename *heartbeat* to avoid conflict with rabbitmq 3.6 feature.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#332]
there are tasks invoked at *heartbeat* intervals to clean, or print routing statistics, doing garbage collection on the cache, or verifying current memory usage.  These tasks are usually packaged as heartbeat routines.  as if rabbitmq 3.6, the broker uses *heartbeat* to refer to a feature in sarracenia that was called *pulse*.  Pulse has been removed from Sarracenia as part of work on #236 but we now have an unfortunate conflict of terminology between Rabbitmq *heartbeat* and Sarracenia *heartbeat*.

sugges replacement of hb_ -> pm_  ?   heartbeat -> on_periodic_maintenance  ... other ideas? routine?  ...  janitor ... on_janitor j_   ... tidy tidy_   on_tidy 

Just rename all the existing plugins and references to heartbeat, replace them with the new word.

**Comment by petersilva** [comment]
https://www.rabbitmq.com/heartbeats.html

the rabbitmq feature.

**Comment by matthewdarwin** [comment]
how about "housekeeping"?

**Comment by petersilva** [comment]
hk_ on_housekeeping... the would be kool because the hb becomes hk, so people might not even notice ;-)

**Comment by petersilva** [comment]
housekeeping was adopted and implemented and has been part of sr3 for some time now.
