### ISSUE TITLE
Downloading old data

### ISSUE THREAD

**Issue by gastoneb** [MetPX/sarracenia#340]
Hi, hpfx has data going back over a month now, and I'd like to download some of that. My config file for sr_subscribe only downloads new data, and it wasn't clear from the docs and examples how to pull in the old data too. 

My config file is something like
```
#debug true
broker amqps://anonymous:anonymous@hpfx.collab.science.gc.ca/
instances 4
expire 2d
#mirror True
logrotate 2
subtopic *.WXO-DD.model_hrdps.continental.grib2.*.000.#
directory /foo
accept .*CMC_hrdps_continental_TMP_TGL_2_ps2.5km*
```
Did I miss something? Thanks. I can also write a script to do this, but I thought that was not the preferred way now.

**Comment by petersilva** [comment]
I don´t think you missed anything. Sarracenia is to get notifications of fresh data as soon as it is available.  When people use things like beautiful soup to poll a web folder over and over, that consumes many orders of magnitude more bandwdith than the notification methods of Sarracenia.   Real-time clients are the target audience for it.  It isn´t really about old data.

There are lots of good tools to just get a whole web tree, a one liner like this will get a days´ worth:

wget -r -np -nH --cut-dirs=3 -R index.html https://hpfx.collab.science.gc.ca/20200612/WXO-DD/model_hrdps/continental/grib2/00/000/

You can iterate over the days if you please.

( got this from here: https://stackoverflow.com/questions/23446635/how-to-download-http-directory-with-all-files-and-sub-directories-as-they-appear  )

I'm not sure there is a reason to use something like sarracenia for retrieving old data... welcome ideas you have about how such a thing would be useful... It would be easy to do I suppose, we just haven't seen the need yet.

**Comment by petersilva** [comment]
I guess the idea is you download a tree and apply the accept clauses and plugins the same as would the real-time ?  yeah... we have sr_poll that does that with a different mindset (real-time still, but for sites that we don't get notifications) could probably do that in the future.

**Comment by gastoneb** [comment]
In the past we've had issues with tools like wget or requests handling retries of failed downloads, and switching to sarracenia had mostly fixed that problem for us. But for a one-off job I think wget should be fine. I was also under the impression from the mailing list that sarracenia was the preferred tool for downloading data from dd and hpfx, although I guess that mainly applies to new data. I understand what you're saying about people building their own polling tools. 

Anyway thanks. I wouldn't worry about adding this as a new feature.

**Comment by petersilva** [comment]
OK, thanks for that.   One thing to keep in mind is that the structure of hpfx, with the root directory being the day makes retrieval of past days possible/easier.  On dd.weather.gc.ca we keep 6 hours of data from most models, so you cannot retreive yesterday's regional from there.  You have to get it pretty quickly or it disappears.  Different data has different lifetimes, and in many datasets, they use the same filename and overwrite it over and over again, so for some cases, real-time is the only way to obtain the data.  with wget, you will only get the last version of a file written when to retrieve.
