### ISSUE TITLE
Review plugin API through the accel plugin case

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#356]
We now have a new plugin API which has been described in #290 and which solved the old unfriendly way from v2 where the import was happening in a different place than the invocation (module context != runtime context), so plugins developper had to import everything he needed inside the routines he was creating. With what has been done in v03 it is much cleaner now and it works well with most of the plugins, which are elegantly callable from flow. Unfortunatly, the approach seems to be uncooperative with plugins involving do_download, do_get, do_put, do_send. Because of a protocol layer of classes between flow and the plugin.

accel_wget plugin is a good example and which is now unusable . Anytime we reactivate it for config/sarra/download/* components,the static flow fails. A good way to reproduce is to run the static test normally and then stop the watch and poll, and just play with foreground of the sarra component. It will crash every time the plugin is invoked.

The problem has something to do with the new API mixed in with do_get call, in the plugin/ directory. What fails first is plugin/accel_wget.do_get . It has "no connect" member in the class, trying to inherit it from sarra.transfer.https.HTTP , but then the constructor fails because the plugin constructor diverges from transfer constructor that take different arguments.

Solutions tried:

1. Splitting into 2 classes in the same file ... the plugin/_init/loadlibrary then complains heavily
2. Building 2 separate plugins, but the problem stayed the same:
    - plugin/accel with the on_message part
    - plugin/accel_wget with the http/download part and this one inherit from transfer.https.HTTP

Solution Proposal:

1. Creating a plugin that inherits from transfer/(sftp,https) and just override the one routine we need. But the question is:
    - How to do an api where you can inherit most from the existing transfer class and just override what you need ?

Complication:

1. Plugins are actually called from flow/_init_ , then, not a parent of transfer

**Comment by benlapETS** [comment]
I just tried the static test with wget activated and sarra failed with that trace:

```
Traceback (most recent call last):
  File "/home/benoit/git/sarracenia/sarra/instance.py", line 207, in <module>
    i.start()
  File "/home/benoit/git/sarracenia/sarra/instance.py", line 199, in start
    self.running_instance.run()
  File "/home/benoit/git/sarracenia/sarra/flow/__init__.py", line 310, in run
    self.do()
  File "/home/benoit/git/sarracenia/sarra/flow/sarra.py", line 31, in do
    self.do_download()
  File "/home/benoit/git/sarracenia/sarra/flow/__init__.py", line 885, in do_download
    ok = self.download(msg, self.o)
  File "/home/benoit/git/sarracenia/sarra/flow/__init__.py", line 941, in download
    ok = self.proto.connect()
AttributeError: 'Transfer' object has no attribute 'connect'
```

Is that the problem we are talking about ?

**Comment by petersilva** [comment]
yes. That is it.  proto is instantiated as a Transfer protocol object.  all the subclasses of Transfer define connect, but perhaps a part of the problem is that the entrey points in the subclasses should be defined in the main with @abstractmethod tag? something to try...

**Comment by petersilva** [comment]
for example of @abstractmethod usage, can look at flow/__init__.py which uses ABC and that decorator.

**Comment by benlapETS** [comment]
Is there a plan to add many more transfer protocol (is there any other anyway) for the whole v03 lifecycle ?

**Comment by benlapETS** [comment]
This is a usecase where the factory pattern is needed. Let me try something, I'll try to complete that today.

**Comment by benlapETS** [comment]
Through some hacks that I made in Flow.download (which would need some refactoring, because there are some wacky things in it), I managed to reach Flow.get (the success place for wget.do_get) 

```
    # generalized get...
    def get(self, msg, remote_file, local_file, remote_offset, local_offset,
            length):

        scheme = urllib.parse.urlparse(msg['baseUrl']).scheme
        logger.warning('scheme={}, self.plugins={}'.format(scheme, self.plugins))
        if ((hasattr(self,'plugins') and ( 'do_get' in self.plugins )) and \
            scheme in self.plugins['do_get'] ):
            return self.plugins[scheme]['do_get'](msg, remote_file, local_file,
                                                  remote_offset, local_offset,
                                                  length)
        else:
            return self.proto.get(remote_file, local_file, remote_offset,
                                  local_offset, length)

```

where it takes the wrong path (invoking self.proto.get(...)). I printed out the scheme and the whole plugin dict to see what is going on (man I miss the debugger that was all setup on my broken machine):

```
2020-09-11 17:18:23,086 [WARNING] sarra.flow get scheme=download, self.plugins={'ack': [<bound method Message.ack of <sarra.plugin.gather.message.Message object at 0x7f51ac4fc7
f0>>], 'do_poll': [], 'gather': [<bound method Message.gather of <sarra.plugin.gather.message.Message object at 0x7f51ac4fc7f0>>], 'on_messages': [<bound method Retry.on_messag
es of <sarra.plugin.retry.Retry object at 0x7f51ac4fcfd0>>, <bound method ACCEL_WGET.on_messages of <sarra.plugin.accel_wget.ACCEL_WGET object at 0x7f51ac4fce50>>, <bound metho
d V2Wrapper.on_messages of <sarra.plugin.v2wrapper.V2Wrapper object at 0x7f51ac4fcdf0>>], 'on_data': [], 'on_files': [], 'on_housekeeping': [<bound method Retry.on_housekeeping
 of <sarra.plugin.retry.Retry object at 0x7f51ac4fcfd0>>, <bound method V2Wrapper.on_housekeeping of <sarra.plugin.v2wrapper.V2Wrapper object at 0x7f51ac4fcdf0>>], 'on_html_pag
e': [], 'on_line': [], 'on_part': [], 'on_posts': [<bound method Retry.on_posts of <sarra.plugin.retry.Retry object at 0x7f51ac4fcfd0>>], 'on_report': [], 'on_start': [<bound m
ethod Retry.on_start of <sarra.plugin.retry.Retry object at 0x7f51ac4fcfd0>>, <bound method ACCEL_WGET.on_start of <sarra.plugin.accel_wget.ACCEL_WGET object at 0x7f51ac4fce50>
>, <bound method V2Wrapper.on_start of <sarra.plugin.v2wrapper.V2Wrapper object at 0x7f51ac4fcdf0>>], 'on_stop': [<bound method V2Wrapper.on_stop of <sarra.plugin.v2wrapper.V2W
rapper object at 0x7f51ac4fcdf0>>, <bound method Message.on_stop of <sarra.plugin.gather.message.Message object at 0x7f51ac4fc7f0>>, <bound method Message.on_stop of <sarra.plu
gin.post.message.Message object at 0x7f51ac4fc3a0>>], 'post': [<bound method Message.post of <sarra.plugin.post.message.Message object at 0x7f51ac4fc3a0>>], 'load': ['sarra.plu
gin.retry.Retry', 'sarra.plugin.accel_wget.ACCEL_WGET', 'sarra.plugin.v2wrapper.V2Wrapper', 'sarra.plugin.gather.message.Message', 'sarra.plugin.post.message.Message'], 'sftp':
 {'do_get': <bound method ACCEL_WGET.do_get of <sarra.plugin.accel_wget.ACCEL_WGET object at 0x7f51ac4fce50>>}, 'scp': {'do_get': <bound method ACCEL_WGET.do_get of <sarra.plug
in.accel_wget.ACCEL_WGET object at 0x7f51ac4fce50>>}, 'ssh': {'do_get': <bound method ACCEL_WGET.do_get of <sarra.plugin.accel_wget.ACCEL_WGET object at 0x7f51ac4fce50>>}, 'fis
h': {'do_get': <bound method ACCEL_WGET.do_get of <sarra.plugin.accel_wget.ACCEL_WGET object at 0x7f51ac4fce50>>}}
```

As I understood the <scheme> and the "do_get" seem to be inverted from what the check is looking for, than it turns to the proto because it can't find the "do_get". 

Also I notice that the scheme 'download' is only a hack that was introduced in the plugin to prevent the instanciation of the default protocol. Then the protocol 'download' doesn't exist as it should.

Should we remove that scheme classification in the plugins dict and just use the method ("do_get") as the key or should we review the whole download procedure which is in my own opinion very ugly (which means need a good refactoring/rethinking). And also review the way we register plugins and check if we gather them the right way after (which means the way we inventoried it).

For today I think I can just hack it to make it work to see if there are other problem spawning out of it.

**Comment by petersilva** [comment]
yeah, that *if* is just a copy/paste from v2 and is not really supposed to be used... I think only the *else* claused is supposed to be used in the current code v3 from there... the idea was for the class instantiation to pick the correct proto, and not use that if at all (it might all go away), but for that to work:

            self.proto = sarra.transfer.Transfer(self.scheme, self.o)

has to instantiate something plugin related.  The scheme would be something like "download" or "wget" and the idea was to instantiate a plugin as some kind of subclass, in this case of sarra.transfer.https, perhaps called sarra.transfer.https.wget and have it use the parent class for all operations except the ones for which methods in the subclass are defined...  If that could work, it would be fairly elegant.  I do not think effort spent on the if clause is likely to be worthwhile.

I think it might not work using the same "import" mechanism used for other plugins... perhaps we just add a new word to the grammar "proto"

     transfer_protocol sarra.transfer.sftp.wget.Wget

That way, the whole if goes away,  have a different load library perhaps dedicated to loading protocols.
then the the v2 config:

    plugin accel_wget 

becomes in v3:

    accel_proto wget
    import sarra.plugin.accel.Accel
    transfer_protocol sarra.transfer.sftp.wget.Wget

which I guess is okish.   I was trying to do everything with "plugin" and I think it was too much... perhaps a second configuration directive for transfer_protocols will make it elegant and obvious.

On  the download routine: code is copied, pretty much verbatim from v2... with only minimal changes... probably best to get to a state where we can run all the tests before we try to change more than is necessary.

**Comment by benlapETS** [comment]
Two things that wrong within what you are actually doing in v3:

- Transfer.__init__() : you are using the constructor of the parent class as a factory method using reflection to instanciate their child, this is anti-pattern and completely wrong and doing so you are breaking the class hierarchy and trying to rewrite the way python instanciate classes. That way also you will also gives the burden to the plugin developper to use that anti python way of instanciate his plugin, he will not like that. Let me rewrite this if you want.

- v2 in v3: Also maybe we should remove those v2 code fragment you left behind and you decide it will not be reused in v3 so it would help debugging

**Comment by petersilva** [comment]
For transfer.init, the purpose was to have a single class to instantiate that can be any type of protocol. That is, in a message, the retrieveal URL, can be SFTP, HTTP, or any future protocol that could be added, such as bittorent, or interplanetary file system, or S3.   So regardless of the protocol actually used, doing it this way allows use of a single constructor that will instantiate whatever protocol is needed by that message.  This replaced v2 code where there were if statements that checked the protocol and then instantiated the specific class for the specific protocol with a single constructor that would work in all cases.

If you have a better way of doing it please provide an example.  What sort of reference do you have to call this "an anti-pattern" and accuse me of "breaking the class hierarchy" and " anti-python"... Opinionated fact-free accusations are not helpful. They don't provide anything constructive to work with. Don't do that. If you want to call something an anti-pattern, point to a reference for why that is the case and explain things. With an explanation and some guidance, criticism is team building and constructive. Without explanation, it's just abuse.  

Consider two approaches to answering your second point:

    Yes Obviously, v2 code was always intended to be removed! Why are you even asking? 
    To do otherwise would be anti-pythonic.

vs.

    yes the strategy in the refactoring is to remove v2 code once it is fully replaced by v3.  The old snippets are there 
    specifically because it hasn't been replaced. Once that is done, it should indeed be removed.

In the former case, needless emotion is injected that will just create conflict needlessly... and it is assuming the other guy is an idiot... and perpetuating idiocy, by stating the objection without any clue as to the rationale behind it. In the latter case, one is explaining the current state, which may be helpful in future cases.  I guess if you are looking for a rule... any time you are tempted to say "anti-pythonic" ... realize that interpretation of that is very subjective, and all it does is start a discussion.  It isn't saving anyone any time using that word.  If all it means is "I don't like it" then further reflection is needed to understand why you have that reaction... and you do need to write out the reasons, so others can understand them and learn, or disagree with you, raising points you hadn't considered, or didn't evaluate the same way.

**Comment by benlapETS** [comment]
Ok, one important part of a review is the critic, this is what I have done in my previous comment, and yes it starts a discussion which I wanted to do. This is correct to say I have not provide any solution yet, I will now try to provide solution based on what I think is the purpose of your code.

You are trying to solve a software engineering problem which has a well-defined pattern to solve it: the [Factory method pattern](https://en.wikipedia.org/wiki/Factory_method_pattern). The reason why it is anti-pattern is that your Creator method is inside the the init part of the constructor,  which make it anti python (did not use pythonic which I reserved for styling issues), as the object has already been instanciated in \_\_new\_\_. A solution that might be inspiring is [here](https://stackoverflow.com/questions/28035685/improper-use-of-new-to-generate-classes/28076300#28076300) which gives good clues how to rethink the solution... to be completed

**Comment by petersilva** [comment]
OK. use of Factory pattern sounds promising.

**Comment by benlapETS** [comment]
Ok, few things to discuss here:
- What is expected from the `opt = copy.deepcopy(options)` line in plugin.load_library() ?
   - It seems to be causing some troubles when the options are updated after the library was loaded.
   - It also showed me that the code was running with 2 instances of the same library in different part of the code, if unwanted (which seems to be the case), it is almost certain it will have some adverse side-effects. 
       - To experience those side-effects, one could activate/deactivate `deepcopy`, activate/deactivate `Singleton` following all combination to see what kind of side-effect is happening with each combination. The problem will differs (different configs missing) depending on the version of the config (original vs copy) and depending what register provided the instance (in Flow.plugins vs in Transfer._classes)
       - Part of the problem is because the library get instanciated and registered in 2 parts of the code. From the Flow perspective, the first instanciation/registration occurs in the loadPlugins() part and the second occurs in the do() part. I don't know which one would be preferred. Is the first part is the old-fashion way and will change gradually to the second ? or the opposite ? or a mix of the 2 ? I can't answer that alone, and it seems like a requirement question (meaning: what need would require such a transition or status quo?)
        - Part of the solution is to add a [Singleton](https://www.tutorialspoint.com/python_design_patterns/python_design_patterns_singleton.htm) pattern to Transfer so we enforce that 0 or 1 instance only will be registered for all of its subclasses (including plugins). I implemented the Singleton as a Metaclass (could have also used an annotation, Metaclass seems more intuitive for me, tell me what would you prefer) so our problem is transitive the Singleton flavor will be easy to remove when the transition is done. Moreover, this solution is reusable, if we need it elsewhere, we could put it in a utility module (like pattern.py, meta.py or annotations.py...) to regroup those kind of generic solutions.
 
- For the credential problem:
    - Faking the scheme was the root cause of the problem and it won't be necessary anymore.
    - The solution is to use:
        1. the new instanciation/registering process for the code to decide by itself what library to use:
            - the logic is in the parent Transfer and I went with the inner Factory method (__init_subclass__(), __new__(), _classes) I proposed in my last comment (the rationale is on [Stackoverflow](https://stackoverflow.com/questions/28035685/improper-use-of-new-to-generate-classes/28076300#28076300)). Though, it could be necessary to separate in a real factory method pattern if we want that solution to be generic and reusable elsewhere (Metaclass or annotation). Should I?
            - on the ACCEL_WGET example (why not ACCEL_HTTP ?): the class kwargs `scheme` ensure that the plugins will register itself for http and https protocols and replace the default which is Https. As it inherit from Https, the default behavior for http already exists from the parent and the plugins developper has the freedom to decide what he override.
        2. then plugin override could everything that is callable by the Flow and add its own internal logic:
           - In the ACCEL case we only needed to override **on_message** for debug logs and **do_get** to decide if we download from the parent or if we use our a custom logic depending on the threshold.

- BTW, there seems to be a lot of duplicated code in ACCEL plugins (WGET and SCP) why not regroup common logic into a parent ?

- there would be a lot of other subject to talk about v3 (good/bad things)... but I think this will be enough for the current pull request.

**Comment by petersilva** [comment]
This comment is much better than before.  the references are good, and can be explored.  That being said, I have concerns about this approach:

* the use of kwargs removes any hints to the programmer about, say mispelling keywords and such.  It's a powerful mechanism, but it is kind of a tool of last resort... to be applied sparingly. it makes the code harder to use as a developer/ API users.  I googled a bit to find a discussion of this sort of thing, and found: http://ivory.idyll.org/blog/on-kwargs.html... Hardly definitive, but it gives a flavour of what the issues are. It is always debatable... but I think we can likely do without them in our case.

* similarly, \__new__ is also a tool of last resort.  Yes, one can use it, it probably is not really needed for such a simple case.

* the use of multiple inheritance, similarly is complicated in practice,  can be elegant (indeed this application does provide a solution in less code than more pedestrian approaches) but is inherently complicated in the long run.   

I'm not sure, but perhaps the multiple inheritance is at the root of the multiple instantiation problem you found above (the singleton discussion?) The Transfer objects need to be created on the fly, to reflect the protocols present in messages received.  they should also be destroyed/replaced when a message with a different protocol is received.*  The plugins, by contrast are instantiated on start, and then live for the lifespan of the instance.  using multiple inheritance for objects with different life spans is difficult to understand.

*hmm... lifespan is interesting... might want to maintain multiple active protocol objects... but that is likely a future, distinct issue... but it could be combined here... hmm... leave it alone for now.

If we can makes things simpler... it is better.  I understand python can do this sort of thing, but in this case, it is akin to swatting a fly with a firearm.  I was not particularly happy with the ABC-based approach that was there before ( fwiw, it came from here: https://stackoverflow.com/questions/18020074/convert-a-baseclass-object-into-a-subclass-object-idiomatically )
and so replacing it with something simpler is good, and a plain old factory (as applied to Integrity and flow classes in recent patches) is probably doable for Transfer as well (eshewing multiple inheritance, __new__, and kwargs, and resulting in code of comparable (likely smaller) size.) ( https://python-3-patterns-idioms-test.readthedocs.io/en/latest/Factory.html )

this:
                self.o.settings['scheme'] = self.scheme  # TODO this is a hack remove that
                self.proto = sarra.transfer.Transfer(self.o)
                del self.o.settings['scheme']  # TODO this a hack to remove that.

is also a bit odd... would prefer something in the call itself.  I am confused by the reference to plugins in Transfer. There are not supposed to be any plugins in Transfer.  Plugins are plugins for flow.  We use plugins in flow to select alternative Transfer classes to be used in different circumstances.   In retrospect, the "accel*" plugins were not a good choice for study, as they are a special case and lead to confusion.  The "normal" case for Transfer subclassing is implementing entire protocols, where it is plain old pure sub-classing. The accel case is a bit more subtle. 

Things that a good answer would do...  I'm hoping we can just end up with something like:

    self.proto = sarra.transfer.Transfer.factory( url_scheme_from_message, options )

Another key discriminator is that *if* in get... Ideally the if would disappear, we should always be calling the proto's get.

Perhaps make a separate branch for this alternate approach?

additional unrelated to the general approach of the patch:

in 1b0176a7a770de821bfada3c40db9fe6ca305a4d 

*  Path(msg['new_dir'], msg['new_file']).stat().st_size  ... in accel_wget... the *stat()* call does an io metadata operation, which, in large volumes, is relatively expensive.  would prefer to obtain the value from a previous call, rather than incurring another io call to get a number we should already have handy, if possible.

* every time I use deepcopy, I am worried... I think the rationale for it was to ensuree plugin options not override those of the flow itself.  so plugins get their options from flow, but they can change them radically and not affect the parent.  All of the libraries are loaded at the end of the startup process, so all parsing is done already.  There should be no timing issue.  That said, I don't know if it is needed at all, it might have been a just a crutch during the refactor and certainly results in extra copies.

**Comment by benlapETS** [comment]
As a first read of your comment, I would say be carefull with dated info it could be base on an old way of thinking (aka like it was with python2). I don't say the argument is not valid, but I am always skeptical about every comments that date more than 5 years that contains python2 snippets unless there are some recents updates which take it into account.

I believe the multi inheritance seems the right solution as you want a plugin (some piece of code to be developed by anybody external to sarra) to be integrated to sarra and be able to send or download files (which is the purpose of Transfer objects). Then, conceptually, I think it makes sense.

**Comment by petersilva** [comment]
agree about the dangers of py2 stuff, and I worried about the thread's age as well.  in this case, the thread's arguments were substantially the ones I was worried about and I think are substantially unchanged (just the implementation is better in py3.)

We are accomplishing an "accellerator" functionality, but there is no need for it to be in one file/class/plugin. the life span of transfer class object is quite different from that of a plugin, there is no common entry point in the two classes.  They are not at all the related to one another. 

* The plugin is a plugin to Flow, and is used to override the choice of transfer mechanisms....

* Transfer is a class for doing transfers. 

Perhaps this is helpful: Transfer class is not just for sending or downloading files, it is also to list remote directories, for use by poll, and change file metadata...   The way v3 is intended to be directly extensible/embeddable, so someone should be able to create a new component by subclassing 'flow', or 'Transfer'.   The plugin class is a way of describing a generic mechanism that is a little easier than subclassing, but I don't think 'plugin' encompasses all plugins.  The main goal of the Transfer class is would enable people to add additional transfer classes, such as S3, bittorrent, ipfs, etc... hopefully, they would just declare new Transfer subclasses to do so.  There is no reason to have such extensions use the "plugin" class.  It's the same idea
for moth/  which expects new message protocols just to subclass it.

For this second type of extension by subclassing, the option grammar would need another word.  I think the "import" keyword is probably the one to use, that just imports a class into sarra.  "import" could be used to import arbitrary modules, a way of adding a new moth subclass (aka message protocol), or perhaps a new flow component or Transfer protocol. Use of the word "import" gives python programmers the right idea.  Import is the right name for that, but it is already used by the flow plugins which is indeed a problem. I think need to rename the current 'import' keyword to in [ 'flow_plugin', 'fplugin', 'fp' ]

**Comment by benlapETS** [comment]
- I think using import would be confusing for an external developper who wants to add features to sarra as what he is really doing is not importing sarra into his code but he is pluging his code into sarra. Maybe what you means is that you want sarra to support 2 different sets of plugins:
- One set that uses definite entry points (on_start, on_message, on_...)
- the other set that would works with overrides would more correspond to [template methods](https://fr.wikipedia.org/wiki/Patron_de_m%C3%A9thode) with the subclasses some from our base code like Https, Ftp, ... and other from the plugins ACCEL_SCP, ACCEL_WGET, MY_OWN_ACCEL, ...

As I understand from this accel plugins wouln't include on_start and on_message anymore as we would mixin anymore ?

**Comment by petersilva** [comment]
ok... so new approach:

* first patch... make Transfer just a simple factory (no code behaviour change just change the constructors to work the same way.)
* second patch... ( I will do in v03_wip ) will change the option language, so import --> flow_plugin, and 'import' does a normal python import.
* third patch.. ( not discussed above, but offline together ) add default value to define_plugin_option(
* fourth patch... define subclass of class wget(sarra.Transfer.https.Https) (for 'import' ing) and a separate file class in a separate file as a flow_plugin accel_wget(sarra.plugin.Plugin) (with the on_start and on_message stuff, to change the url.)

**Comment by petersilva** [comment]
ok in the case where the stat was after scp/wget fork... next to that the stat is negligeable..

**Comment by petersilva** [comment]
ok, 2nd patch done, commit: e20c1c7b19dc954a9442688dcab4a41352ce170a 
so import keyword now works like normal python import, and what was called 'import' in v3 code is now called flow_plugin
I tested import with an abritrary class, and a stub that subclassed Transfer, and it worked.

**Comment by petersilva** [comment]
oh... and please provide a pull request when the first patch is ready.  would like to merge in stages as well.

**Comment by petersilva** [comment]
I am still puzzling over changing the name of flow_plugin to make it more obvious that it does not encompass all extension mechanisms... *flow_callbacks* I think I will change the name of the class from sarra.plugin to sarra.flowcb much clearer.  Not calling it 'plugin' will clarify that it is for adding custom callbacks from flow instances.

**Comment by benlapETS** [comment]
Job done:

- patch 1 in commit 05160126
- patch 3 in commit 375eab00
- patch 4 in commit 8a7ac038

pull request to follow...

**Comment by petersilva** [comment]
re-factored:
   
- name of *plugin* classes changed to *flowcb* (flow_callbacks) 7da795e4cc97f6edd8e01dbef5cb9878e8f2483d 4d7ef72a6d0dfdda88d8ea9ce5fa7dccc6dc5412

- added getAceelerated to API of Transfer class, so acceleration is now built-in.
ca3c942a41faeac6375ab140910a5afcf7b906ef

Removed all linkage to plugins for accelerator function. wasn't clean no matter how it was done.

this work was done in v03_wip branch...
