### ISSUE TITLE
sr needs to support application keys for authorization.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#360]
Kurt Hoffmann @kurt2x :
  
it looks like for this to work the sr_http.py needs to be modified to allow custom headers to be configured after
```

self.req = urllib.request.Request(self.urlstr)
# need some way of configuring this next line via the configuration file, something like: 
# customHeaders Authorization Bearer TOKEN
self.req.headers['Authorization'] = 'Bearer ' + token 
I got an identification token from the source for the ssc-hpc account we have with them. https://ladsweb.modaps.eosdis.nasa.gov/profile/#app-keys

```

**Comment by petersilva** [comment]
Do it with with ~/.config/credentials.conf 

https://ladsweb.modaps.eosdis.nasa.gov/ auth_token=string?file containing string?

**Comment by petersilva** [comment]
I'lll take a look to see how hairy it is.

**Comment by kurt2x** [comment]
this description of the feature seems very relevant:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication

**Comment by petersilva** [comment]
OK, @kurt2x ... there is now a branch issue360, which allows you to put:
```
https://ladsweb.modaps.eosdis.nasa.gov/ bearer_token=89APCBF0-FEBE-11EA-A705-B0QR41911BF4

```
in the credentials.conf file.  It will supply a bearer authorization token as decscribe in the noaa hint.
So it is addressing the original topic of the issue.  perhaps try it out and confirm.  Unfortunately, it gets
stuck rapidly, because an on_html_page plugin is needed to understand the output from the nasa web portal...
so it doesn't solve the whole problem.

**Comment by petersilva** [comment]
commit: 98d47edcb4b6a62983732bfb0aa76c2db305e8ae

**Comment by petersilva** [comment]
Suggestion for @tysonkaufmann 

* no-one has implemented an on_html_page plugin before, so aside from the 1 example, it is unknown.
* might be good to attempt to create some training/guidance material as part of this (input to the programmers guide.)

**Comment by petersilva** [comment]
@kurt2x  @tysonkaufmann  Was this ever needed/tested? The code is sitting on this branch... never brought into mainline, because no confirmation that it helps...

**Comment by kurt2x** [comment]
I still have to test it out on my laptop, just haven't had a chance yet.

**Comment by kurt2x** [comment]
it works! I was able to download data using the bearer_token option

**Comment by petersilva** [comment]
merged to master branch.  It will be included in next release.
