### ISSUE TITLE
(403) ACCESS_REFUSED - access to queue ... in vhost '/' refused for user 'anonymous'

### ISSUE THREAD

**Issue by accu-knauthg** [MetPX/sarracenia#372]
Sarracenia seems fantastic, but it seems `anonymous:anonymous` doesn't work.

Do the docs need to be updated so people know what is required to get access?

```
[ERROR] sr_amqp/build could not declare queue q_COMPANY.sr_subscribe.alerts-ca.0.0 (anonymous@dd.weather.gc.ca) with Queue.declare: (403) ACCESS_REFUSED - access to queue 'q_COMPANY.sr_subscribe.alerts-ca.0.0' in vhost '/' refused for user 'anonymous'```

**Comment by accu-knauthg** [comment]
This is my config file:

```
broker amqps://dd.weather.gc.ca/

queue q_COMPANY.sr_subscribe.alerts-ca.0.0
durable True
expire 5d
message_ttl 3600000
reset False
prefetch 1

# see https://dd.weather.gc.ca/alerts/cap/

exchange xpublic
subtopic alerts.cap.#
directory /home/azureuser/alerts-ca
```

**Comment by petersilva** [comment]
the queue name is constrained by the username... q_COMPANY is not allowed to user anonymous... you would need to use q_anonymous.COMPANY.... 

valid choices for queue names are described here:
https://github.com/MetPX/sarracenia/blob/main/doc/sr_subscribe.1.rst#queue-queue-name-qn-name 

"Users can override the default provided that it starts with q_<brokerUser>."

I made that change to the queue_name, and it then started up ok.
but I did not wait long enough for a warning to appear.

sr_subscribe will remember what queue_name you have chosen, so when you change it, you probably need to do:

sr_subscribe cleanup cap.conf

then you can start it.   It might work then.

Also, you might need a line in credentials.conf like:

amqps://anonymous:anonymous@dd.weather.gc.ca

on linux, credentials.conf would be in the ~/.config/sarra/ directory.
if you are on some other platform it will be different.

**Comment by accu-knauthg** [comment]
Thank you @petersilva so much for getting back to me so quickly. I thought I'd followed the instructions but what you write makes lots of sense. I'll try that right now.

**Comment by accu-knauthg** [comment]
@petersilva That worked, I'm in! I'm grateful to you for your quick response, and of course for the software itself. Closing this ticket.
