### ISSUE TITLE
Every https download fails after upgrading to Linux Mint 20.2 (python3-pyxattr instead of python3-xattr)

### ISSUE THREAD

**Issue by endlisnis** [MetPX/sarracenia#378]
I recently upgraded from Linux Mint 20.1 to 20.2 and afterwards every single file download has been failing.

I have tried restarting my computer and reinstalling the python modules involved.

I have also tried manually downloading the files using "curl" on the command line, and that works just fine.
[sr_subscribe_rolf_01.log.gz](https://github.com/MetPX/sarracenia/files/6824402/sr_subscribe_rolf_01.log.gz)

I have attached one of the log files showing the errors and here is my .conf file:

```
broker amqps://anonymous:anonymous@dd.weather.gc.ca/

instances 8

# All stations
subtopic observations.swob-ml.#
# subtopic nowcasting.#

# Only station CYQL
mirror True
reject .*/partners/.*
reject .*/moored-buoys/.*
# reject .*/.*-minute.*
accept .*
expire 4h

use_pika False

# file_rxpipe_name /home/rolf/weather/rxpipe
# on_file file_rxpipe

```

**Comment by petersilva** [comment]
weird.  works for me fine I copied your config, started it up and downloaded a dozen or two swobs... no issue.
your log file show no errors either. ... hmm... your config does not have a "directory" line in it... so it will download to a subdirectory of wherever you start the sr_subscribe in... could you be looking for the files in the wrong place?

**Comment by petersilva** [comment]
the log shows " /home/rolf/weather/swobMirror" is that where you intended to write the files?

**Comment by endlisnis** [comment]
Look at the END of the log file.  They were working at the beginning but then failed.

**Comment by endlisnis** [comment]
> the log shows " /home/rolf/weather/swobMirror" is that where you intended to write the files?

Yes, that is where I intended to write the files.

I tried setting up a docker container using the newest ubuntu image, and it worked fine using my exact configuration; so it's clearly something to do with my Linux Mint installation.  I'm going to try a docker container for Mint v20.2 and see if it works in there.

**Comment by endlisnis** [comment]
I tried it on a fresh docker container for Linux Mint v20.2, and it worked just fine with my config file.  So there is obviously something wrong with my local setup that is triggering this failure.  But the error logs just say:
`2021-07-15 11:27:13,967 [ERROR] Download failed 3 https://dd4.weather.gc.ca//observations/swob-ml/20210715/COGE/2021-07-15-1525-COGE-AUTO-minute-swob.xml`

Is that "3" an error code?

**Comment by petersilva** [comment]
"failed 3" is an error code that means something bad happenned, and it didn't have a more precise idea...
my guess is would be that your container doesn't have permission to write where you want it to?

**Comment by endlisnis** [comment]
To clarify, when I run it in a docker container, then everything works perfectly.

The situation that fails is when I run it natively.  I checked the permissions, and I don't see any problem.

I have a backup system that can poll the server if the AMQP service runs into a problem, and it has no trouble writing to that location (both of these services run as my account).

**Comment by endlisnis** [comment]
I managed to debug sr_subscribe and get this traceback:

```
Traceback (most recent call last):                                                                             
  File "/home/rolf/.local/lib/python3.8/site-packages/sarra/sr_util.py", line 519, in download                 
    self.set_local_file_attributes(new_file,msg)                                                               
  File "/home/rolf/.local/lib/python3.8/site-packages/sarra/sr_util.py", line 766, in set_local_file_attributes
    x = sr_xattr( local_file )                                                                                 
  File "/home/rolf/.local/lib/python3.8/site-packages/sarra/sr_xattr.py", line 108, in __init__                
    d = xattr.xattr(path)                                                                                      
AttributeError: module 'xattr' has no attribute 'xattr'                                                        

```

**Comment by endlisnis** [comment]
And my "xattr" module is provided by a package named:
python3-pyxattr/focal,now 0.6.1-2 amd64 [installed,automatic]

Which seems to be included by default on Linux Mint v20.2.

**Comment by petersilva** [comment]
sigh... it appears that there are multiple python libraries that provide different modules under the name "xattr", and there seems to be a conflict.  I think the module you actually want is python3-xattr... you might want to test.. you can try replacing the package in your container, and it might work...

as to what I need to do to fix it... have to think about it.

**Comment by petersilva** [comment]
API of pyxattr:
```
        >>> xattr.listxattr("file.txt")
      ['user.mime_type']
      >>> xattr.getxattr("file.txt", "user.mime_type")
      'text/plain'
      >>> xattr.setxattr("file.txt", "user.comment", "Simple text file")
      >>> xattr.listxattr("file.txt")
   
```  
API of python3-xattr:
```

    >>> x = xattr.xattr("file.txt")
   >>>
    getxattr(f, attr, symlink=False)
    
    listxattr(f, symlink=False)
    
    removexattr(f, attr, symlink=False)
    
    setxattr(f, attr, value, options=0, symlink=False)


```

**Comment by endlisnis** [comment]
I was able to remove python3-pyxattr and install python3-xattr instead.  This resolved the problem.  Files are downloading again.

I don't know why the other package was installed -- I'm now a little afraid that I've broken some other python program that relied on the **other** xattr module.  But this works now.

**Comment by petersilva** [comment]
thanks for confirming that is the problem... I have to think about what to do with the code to deal with the two API's. In a future version this problem should go away.

**Comment by petersilva** [comment]
@cleaaum patches are for v2 so far.   v3 outstanding.

**Comment by petersilva** [comment]
v2 patches accepted into main.  will be included in next release (unfortunately missed the one made today.)
