### ISSUE TITLE
wrong type passed to durationToSeconds in config.py (v03)

### ISSUE THREAD

**Issue by cleaaum** [MetPX/sarracenia#381]
value of nodupe_ttl in config.py is initially 120, which is passed to durationToSeconds causing no issue, but eventually becomes "off" causing an error. This is the output from running a config file.

self.nodupe_ttl value:  120
self.nodupe_ttl value:  120
self.nodupe_ttl value:  off
2021-07-26 12:20:51,929 [ERROR] sarracenia durationToSeconds durationToSeconds, conversion failed for: of
self.nodupe_ttl value:  off
2021-07-26 12:20:51,932 [ERROR] sarracenia durationToSeconds durationToSeconds, conversion failed for: of

**Comment by petersilva** [comment]
not sure what is going on... 
I see this in sarracenia/config.py/fill_missing_options ... perhaps it needs to be there sooner? 


```
        if hasattr(self, 'nodupe_ttl'):
            if (type(self.nodupe_ttl) is str):
                if isTrue(self.nodupe_ttl):
                    self.nodupe_ttl = 300
                else:
                    self.nodupe_ttl = durationToSeconds(
                        self.nodupe_ttl)
        else:
            self.nodupe_ttl = 0

```

**Comment by petersilva** [comment]
I think you figured this out... can it be closed, or is there still an issue?
