### ISSUE TITLE
sr cleanup deleting exchanges when it should not.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#382]
cleanup done by a client is needed to delete queues when removing a consumer... because it will not be in use for a prolonged period.

current algorithm looks at all user configs known (to the machine & user) and if it finds no other dependencies, it removes the exchange, as well as the queue.

It cannot know if there are other users of the exchange. (affects both v2 and v3)

**Comment by petersilva** [comment]
Also user sr_audit --users foreground.   deleted xs_feeder user.

The configuration has a mix of amqp: and amqps: mixed

if you see the entry in the credentials file, but no declared role... probably should make an error message, and not delete anything.

**Comment by petersilva** [comment]
two weeks ago... also deleted users which were not properly declared... causing issues on dev. server.

**Comment by MagikEh** [comment]
We can consider adding simulate/dry-run to just indicate what actions /would/ be taken if the command were run otherwise?

**Comment by MagikEh** [comment]
Issue #465 is related to this, assigning to Clea, close them together?

**Comment by petersilva** [comment]
Raised priority because it is an issue that prevents use of what should be routine maintenance interventions.  Analysts are doing complicated manual interventions to avoid running audit and cleanup functions.

A new suggestions... the only *dangerous* thing is removing exchanges.  So why not put a --dangerWillRobinson guard around deleting exchange?

in order for cleanup to delete exchanges, one has to provide --exchangeDeclare --dangerWillRobinson

normal clean up just will not remove exchanges (but will still declare them.)
That sound like a reasonable resolution of the tension...

**Comment by petersilva** [comment]
Also... exchange deletion might be better construed as an admin function (using rabbitmqctl or rabbitmqadmin) rather than AMQP calls... since AMQP provides no introspection.  Using an administration interface..  can query for  bindings and examine them...

**Comment by petersilva** [comment]
otoh, @tysonkaufmann just found: 

https://www.rabbitmq.com/amqp-0-9-1-reference.html#exchange.delete

there is a bit "if-unused" that can be set on the operation, that would probably solve this problem entirely, by only deleting exchanges that have no bindings.

**Comment by petersilva** [comment]
The if-unused flag makes it super simple... but need to run the flow tests... to see whether it the existing sr3 cleanup code works there... by confirming exchanges which are created by the flow tests, are deleted at the end.  There may be an issue with order of operations, where all queues deletions, or at least bindings should be done before all exchange deletions.

**Comment by reidsunderland** [comment]
When doing sr3 cleanup on a subscriber config with only broker (no post_broker), the output shows:

```
reid@sarra-test1:~/sr_insects/static_flow$ sr3 cleanup subscribe/q_f71
cleanup: 2023-01-31 14:37:47,347 43117 [INFO] sarracenia.moth.amqp getCleanUp deleteing queue q_tsource_subscribe.q_f71.84261747.53975698
 remove q_tsource_subscribe.q_f71.84261747.53975698 from xs_tsource_poll subscribers: ['q_tsource_subscribe.q_f71.84261747.53975698'] 
no more queues, removing exchange xs_tsource_poll
2023-01-31 14:37:47,354 43117 [ERROR] sarracenia.moth pubFactory no broker specified
removing state file: /home/reid/.cache/sr3/subscribe/q_f71/subscribe.q_f71.tsource.qname
```

`no more queues, removing exchange xs_tsource_poll` (from sr.py) should probably be changed to something like "No local queues found for exchange %s, attempting to remove it...". Then moth will output a message about whether or not it was actually removed.

sr.py is also calling pubFactory and causes the error "[ERROR] sarracenia.moth pubFactory no broker specified".  (Because there's no post_broker).

Is cleanup only supposed to remove exchanges for configs with a `post_broker`?

**Comment by petersilva** [comment]
OK accepted the PR for sr3... do we want to backport to v2 as well?

**Comment by reidsunderland** [comment]
I think so, it's an easy change that makes cleanup a lot safer
