### ISSUE TITLE
environment variables not honoured in config file arguments. (v2 only)

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#386]
issue reported internally to GoC (not publically accessible): https://gccode.ssc-spc.gc.ca/ec-msc/msc-geomet/-/issues/269
by @tomkralidis 

in a config file:
```
discard ${SET_DISCARD}

```
is always false, regardless of what value is set in the environment variable SET_DISCARD.

short version: !@$#!@ v2 parser... 

This happens because the option parser, inexplicably literally parses *${SET_DISCARD}* for truth value instead of what it resolves to ( the former being in *words[1]*, and the equivalent with variable substitutions being applied being in *words1*
noticed 

* this affected pretty much all boolean and integer options.
* only affects v2.  v3 does the right thing, with 30% less code. oh well.

**Comment by tomkralidis** [comment]
Thanks @petersilva !

**Comment by petersilva** [comment]
https://github.com/MetPX/sarracenia/issues/386

**Comment by petersilva** [comment]
https://github.com/MetPX/sarracenia/releases/tag/v2.21.08
