### ISSUE TITLE
why is memory check missing? perhaps rewrite all v2 hb_* as v3 hk_*

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#395]
Periodic processing is a feature in Sarracenia, necessary for various maintenance tasks. in v2 it was referred to as heartbeat, which made it sound like it should happen way too often, and as there was a completely separate feature called *pulse* (which has a different interval) ... anyways... in v3 the name is *housekeeping* which is much closer to a good description... it happens often but not too often.

There are some built-in plugins that were in v2, that don't seem to run in v3.  In particular, 
in v2, there is hb_memory... in v3, either old hb_memory should work (upward compad) or there should be a new hk_memory.  This is important because paramiko has a memory leak and if we don't restart periodically, the processes grow without bound and eventually server crashes.

perhaps rewrite all of them (not that many exist.)

**Comment by petersilva** [comment]
look in flow/__init__.py  Flow class: __init__.py  for append( to 'load' thing...

**Comment by MagikEh** [comment]
Run a dynamic flow test, smtp server or something with Parameko (known memory leaks)

**Comment by MagikEh** [comment]
Confirmed that memory is reclaimed via the currently supplied method! I saw a `subscribe/u_sftp_f60` instance memory usage go down after a restart!!

(Had to set `hb_memory_multiplier` to 1.002 to trigger a few times)
`tail -f ~/.cache/sr3/log/*.log | grep Memory | grep -v cpu_times | grep -E " [14-9][\.0-9]+%|restart|$"`

![image](https://user-images.githubusercontent.com/6865027/151257194-ca09a31a-df42-4283-a7b9-732a005a5a15.png)

**Comment by petersilva** [comment]
great!

**Comment by petersilva** [comment]
sounds ready for a pull request.

**Comment by petersilva** [comment]
merged. great!
