### ISSUE TITLE
realpath & realpath_filter discussion

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#399]
This issue will discuss the design and implementation of *realpath* ( *man 3 realpath* ) related options in sr3 and sr3c.  These options are used to adjust if and when the realpath library is called on paths, as a sort of normalization.  It isn't clear what the effect of different approaches are in the broader HPC mirroring case, so several approaches are implemented, it is time
to narrow things down to perhaps a single correct answer (best) or fewer options.

use case:

In the hpc case, batch jobs are run, and a temporary working directory is established for the lifetime of the job. Since the directory is erased at the end of the job, it is clearly inappropriate to post files from there, as, by the time the subscriber attempts to copy the file, it will be gone. So the working directory is excluded with a *reject* clause.

On the other hand, the jobs need to have a permanent effect. When final output files are to be persisted, the jobs create a symbolic link to the permanent location where these final outputs are written, and the rest of the job writes through that symbolic link.

so realpath related options, in this use case, are intended to resolve the symbolic link so that the actual, permanent path is used, so that it is included in the files to be posted for (for subscribers to subsequently copy.)

It would appear that None of these options have any effect on subscriptions.  These options only affect posting.
in the HPC use case, as the C implementation is doing all the posting, that means it is the only implementation that affects the results.

Surveying source code and changelogs. deducing what was done... *realpath* feature originally implemented by Peter Silva in 2017 ( 2cac12d3d3acbf9ec800257bcbe6660fb8b26023 ), then Michel Grenier added *realpath_filter.*  It looks like, at first we thought it would affect posting and consumption, but after experiments we concluded that it should only affect posting and it was split into two options:   realpath_filter and realpath_post.  the former limited application of realpath library call to accept/reject clauses, and the latter applies it more broadly. 

( also some tweaks from benoit lapointe, and michael Sarraga... in 2018/2019... )

v2 options defined:

* realpath -- normalize every path prior to processing. (likely was the 1st approach taken.)
   * only in C implementation... but C accepts *realpath_post* as a synonym.
* realpath_filter  - apply realpath normalized paths before comparison for accept/reject clauses.
  * implemented in both C and python in v2.
* realpath_post -- normalize every path prior to processing.
   * only exists in python v2 implementation.

So what is called *realpath* in v2 C is called *realpath_post* in v2 python.  *realpath_post* is apparently undocumented.
... sigh...

meanwhile, realpath_filter likely does "the right" thing... and realpath_post was likely the first attempt.. that does the wrong thing.  How I suspect it will turn out:

*realpath_filter* behaviour is likely the right thing to do, all the time... no need for an option. We should just hard-code that to on...

so the option should go away... once we figure out it actually does do the right thing.  need to make sure.

so suggested settings for HPC mirroring case C are:
```

     realpath_filter on
     realpath_post off (aka realpath)

```
If that works in the HPC mirroring case, then likely will just hard-code that behaviour (removing the option.)

**Comment by petersilva** [comment]
figure out what realpath_filter does in v2, and implement same in v3... a forward-porting exercise.

**Comment by petersilva** [comment]
This is only used in HPC mirroring case.... not a blocker until we want to deploy there....

**Comment by petersilva** [comment]
audited sr3 code:

* realpath_post is implemented... as far as I can see, similarly to v2.

* realpath_filter is not implemented.  

So likely sr3 should implement the realpath_filter behaviour once it is clear that is the right one.  It does not affect anything in the HPC mirroring case because all posting is done by the C implementation.  This would be just to increase commonality of behaviour of the two implementations.

**Comment by petersilva** [comment]
effect of above two sr3 (python) patches:

* realpath_filter -> realpathFilter
* realpath_post -> realpathPost
* realpath -> synonym for realpathPost

(realpathFilter still not implemented though.)

**Comment by petersilva** [comment]
actually... reviewing code from v2, realpath_filter is not implemented in the v2 python either... the reference to it is in a piece of dead code, so actual posting never uses it.  The only implementation is in C currently.

**Comment by petersilva** [comment]
probably the best way to address this is with an on_stop handler in the renaming plugin.
I don't know if that will actually work in v2... might have to defer to sr3.

**Comment by petersilva** [comment]
this is related to: https://github.com/MetPX/sarrac/issues/101

in latest version... metpx-sr3c has:

* realpathFilter ... apply realpath resolution for accept/reject filtering
* realpathPost ... apply realpath resolution for url posts.
* realpathAdjust 0-9   ... adjust what portion of the path is resolved with realpath
   *  realpathAdjust -1 ... all but the last path element is resolved.
   * realpathAdjust 5 ... the first five path elments are resolved.

This is implemented in C in 3.23.01p3 ...

**Comment by petersilva** [comment]
once proved out by the C-side, should implement on the python side.

**Comment by Padmalathas** [comment]
#please-close
