### ISSUE TITLE
v2 to v3 transition documentation

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#411]
Providing some guidance to analyst used to large v2 configurations...

**Comment by petersilva** [comment]
no... it is the same in v2... it's just that v2 evolved over time... you can go look in doc/UPDATING.rst ... no just looked...
it happened at some point, likely in 2017/2018... This change is not a v3 thing.

What is message_broker? I might have forgotten that? does that exist?

**Comment by petersilva** [comment]
found the relevant bit in UPDATING::

2.17.11a1
---------

**BUGS**: Ugly log message from syntax error in where:
Message: '%s does not have vip=%s, is sleeping'
Arguments: (('sr_winnow', '192.168.xx.yy'),)
Shows up when using VIP. Fills log with garbage.


*SHOULD*: Change document_root -> base_dir (same for post\_ variations.) The code still
understands the old values, but you will see a warning message advising you to change it.

*SHOULD*: Change ${PDR} -> ${PBD} to mirror above change. There will be no visible
effect of this, but at some future release, PDR will be dropped.

*SHOULD*: URL option to post_base_url option.  Will still understand old values, but
warning will result.

*SHOULD*: Use post\_ versions in sr_post, so now it is post_base_url, post_base_dir,
post_exchange. Again, code still understands previous settings, but will warn.

*NOTICE*: Now prefers to use pika library if available, but falls back to amqplib
library available on older OS's.  amqplib will be deprecated over time.

**Comment by petersilva** [comment]
OK, I think this is done:

* https://metpx.github.io/sarracenia/How2Guides/UPGRADING.html
* https://metpx.github.io/sarracenia/How2Guides/v2ToSr3.html

@MagikEh Perhaps Review the documents... improvements welcome.

**Comment by MagikEh** [comment]
# Docu Meeting Notes:
- In browser translate mangles the technical docs (autogenerated files get function names and raw code translated...)
- There's a TODO list in the OP in order of precedence (top to bottom)

**Comment by petersilva** [comment]
so @cleaaum implemented *convert* and this isssue is about v2 to v3 transition... we should perhaps add a note about use of convert to:

* https://metpx.github.io/sarracenia/How2Guides/UPGRADING.html#v2-to-sr3 and
* https://metpx.github.io/sarracenia/How2Guides/v2ToSr3.html

And then we can close this issue? I am not sure what else there is to write about v2 to sr3 transition.
