### ISSUE TITLE
Review directory placement 

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#425]
Why are files placed where they are? How was the choice of directories made?

There are a few different standards for file placement (on Linux):

* The File Hierarchy Standard, (DFHS https://wiki.debian.org/FilesystemHierarchyStandarda ) which leads here: https://refspecs.linuxfoundation.org/fhs.shtml
  describes trees outside of a user's account.

* The XDG directory specification https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
  describes standard trees within user accounts.

* readable discussion of XDG: https://lzone.de/examples/Glib%20XDG%20Migration

The two trees conflict.  For example: configuration files, according to FHS, go under /etc, under XDG ~/.config (XDG_CONFIG_HOME)
Run-time data goes  XDG_DATA_HOME ( ~/.local/share ), XDG_DATA_DIR ( /var/local/share, /usr/share ) , XDG_STATE_HOME ( ~/.local/state ),
XDG_CACHE_HOME.  

To make the application portable, there is the python appdirs module https://refspecs.linuxfoundation.org/fhs.shtml which applies
XDG specification on Linux, and uses OS appropriat(ish) schemes on Windows and Mac.  use of this module avoids any custom code
for preference and run-time file storage.

For daemons, established practice is to use the FHS, but... it is also is well established practice that daemons and/or
service processes should not be run as root.

It is part of Sarra's design that ordinary users can run Sarracenia in their accounts... for which XDG is the guide.
It took a while to figure out ( https://github.com/MetPX/sarracenia/issues/370 ) when a user had used this environment
variable in one context, but failed to set it in a cron job. Moving log files seems to be a request that happens,
but sr3 sanity will read them, so the tool as a whole needs to know about file placement.

Sarracenia makes the choice of following XDG for even the special user involved when running as a daemon.
Is that a correct choice?  Discuss.

Perhaps this document should be an issue.

There is also another debate to be had about the use of *statehost* in a clustered environment.  the *statehost* environment
adds a level of directory with the host name it it to the directory hierarchy for the state ( ~/.sr3/cache/hostname/log,poll,etc... )
It is clear that that is needed in cases where there is a shared file system,   (  https://github.com/MetPX/sarracenia/issues/348 )
When this setting is improperly omitted, you end up with processes on multiple hosts writing to the same log file, causing confusion.   Also pidfiles do not make much sense to be shared across servers.  So it would make some sense to have
at least certain state files always shared.

https://github.com/MetPX/sarracenia/issues/348

**Comment by petersilva** [comment]
@MagikEh reports that changes of hostname resulting from spinning up containers could be confusing... 
is there anything to take in from this: 

https://github.com/wmo-im/wis2node/blob/main/docker/metpx-sr3/Dockerfile

**Comment by MagikEh** [comment]
re: [Containerization](https://www.redhat.com/en/topics/containers/whats-a-linux-container)
- Docker supports using [--hostname](https://docs.docker.com/config/containers/container-networking/#ip-address-and-hostname)
- Linux containers (LXD,LXC,LXCFS,distrobuilder) obtain a hostname from [the container name](https://discuss.linuxcontainers.org/t/lxd-override-hostname-defined-in-etc-hostname/2563)

From this we can put the onus on users to setup the environment such that if they want consistency between container runs, they should set them up such that the hostname is the same.

**Comment by MagikEh** [comment]
> Statehost is busted, see #348 
 --Peter
