### ISSUE TITLE
on_html_page porting.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#426]
v2 plugins have an on_html_page callback, and it is called from within transfer protocols in v3, rather than from the flow where v3 plugins are supposed to call from.  Need to understand how to transform.

**Comment by MagikEh** [comment]
This will break a couple of polls if we push do dev machines.

Since sr3 can be installed alongside sarra.v2, we can pull (sarra.v2->sr3) configs over one by one until things break and leave those on sarra..

Document the broken configs in an issue, fix if you can, ask/talk about it if not.

**Comment by petersilva** [comment]
OK. now have complete coverage of use cases for on_html_page, and the resulting solutions are more compact.  So that's good.  
* should the naming be reviewed? keep "on_html_page"
* I can't tell whether on_line, and on_html_page are the same thing? the data_handler seems to handle one line at a time, but the signature is dictated by html.parser. so perhaps both entries are still ok.
* Do we worry about auto-translation, or just say... read the porting book and barf, when on_html_page, or on_line found in a plugin?

**Comment by petersilva** [comment]
To give an idea of why this design is used. relevant code in v2:
```

fractal% wc -l sr_poll.py plugins/line* plugins/html_page.py 
  713 sr_poll.py
   46 plugins/line_date.py
   38 plugins/line_log.py
   57 plugins/line_mode.py
   85 plugins/html_page.py
  939 total

```

in sr3 
```
fractal% wc -l flow/poll.py flowcb/poll/__init__.py
   80 flow/poll.py
  454 flowcb/poll/__init__.py
  534 total
fractal% 

```
roughly 50% code size reduction.  Also for plugins comparing v2 plugin to v3, is similarly more compact:

```
 v2:   74 nasa-mls-nrt.py
sr3: 31 flowcb/poll/nasa_mls_nrt.py

```

Not just smaller, but also easier to understand, as using sub-classing is a more elegant and understandable method for people to write future plugins, and they can write the minimum poissible code.
