### ISSUE TITLE
Option to have configs default to System (Daemons)

### ISSUE THREAD

**Issue by MagikEh** [MetPX/sarracenia#432]
![FHS Diagram](https://i.imgur.com/0vfM4dm.png)

The [File hierarchy standard](https://wiki.debian.org/FilesystemHierarchyStandard), describes standard file placement.
the FHS is an evolution of long standing practice with Linux, and provides many options: one could install in /etc & /var, as well as portions in /srv for services to other systems, and for "non-essential" software, there is /opt.  In addition, the FHS allows for placement of files in "User directories."  

best practice for running application daemons/services is to define a username and group for each application, to better idenfity processes and permissions used by the service. The code currently works from the user's perspective using the freedesktop.org XDG base directory specification (https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) which provides consistent placement regardless of the user running the application, be it a system user, or an ordinary user.  Directory placement, is taken care of on unix/linux, Mac, and windows, using a single python library: appdirs.

Placement with FHS ( under /etc, /var, etc...) will not allow for cases where configurations are intended to be shared across multiple file systems (the NFS share case.) and so likely configs would end up in /srv, or /opt which are optionally NFS mounts. It is not clear what advantage there is from placement of  /opt/sr3/etc vs.  home/sr3/etc ... or /home/sarra/etc... or /opt/sr3/logs  vs. /home/sr3/logs. Especially when one could easily, as a system administrator:

  ln -s /opt/sr3 /home/sr3

To relocate there if desired, or even just assign the home directory of the user to be /opt/sr3.  In both cases the existing code, which has no special case for system placement, will find and place files correctly. Also use of FHS standard, should it be chosen, then creates the question of what to do on MAC and Windows.  Similar standards would have to be investigated. There is also, within use of current XDG standard, the ability to re-locate files as desired. @junhu3 suggests users instead create an aliased link from the configs/data to the user's XDG_CONFIG_HOME/XDG_CACHE_HOME.

Raised by issue #425

Cons:
- Current design uses single code base to address all use cases on all platforms.  Adoption of FHS requires additional code to separate, user vs. system case, and add undefined placement required for Windows and Mac. - the addition adds complexity, for an unclear benefit, since similar configurations are achievable by administrator
  choice.  

Pros: 
- User choice? 

The first step in progressing on this would be to define the tree to use on Linux.  Then add Windows and Mac. If someone wants advance this idea, they would need to do that.  for now, this is considered useless additional complexity, hence the wont-fix

**Comment by petersilva** [comment]
@MagikEh  reopening, assigning to you... for the FAQ creation and inclusion part?

**Comment by MagikEh** [comment]
- [x] Add a FAQ to the [`/docs/Home.rst`](/MetPX/sarracenia/blob/v03_wip/docs/Home.rst) 
- [x] mentioned this issue as well as 425.
