### ISSUE TITLE
sr3 status  config ignored when has never been used.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#435]
if you add a file to the configuration directory, but it has never been run, it does not show up.
to reproduce:

* add a file to the config tree anywhere under ~/.config/sr3/\<component>/x.conf
* run sr3 status

x will not show up.

**Comment by cleaaum** [comment]
Also noticed another bug when trying to fix this one: **sr3 remove component/config** will only remove the config but not the associated state file.

**Comment by petersilva** [comment]
go ahead and fix that. it's a good thing to clean up.

**Comment by petersilva** [comment]
merged ! yeay!
