### ISSUE TITLE
v02 to v3 config translator

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#438]
@cleaaum @tysonkaufmann both suggested a config file translator to say:
*given a ~/.config/sarra/x/y
* produce a file ~/.config/sr3/x/y   
* with the v2 keywords replaced by canonical v3 ones, and 
* comment/marking likely problems.

**Comment by petersilva** [comment]
fwiw... now that I'm playing with docker/docker-compose etc... it might be worth considering switching to YAML format for v3.  Other similarly stylish formats didn't have the concept of time (top early, bottom of file later in time) but docker works that ways, so it must be possible.  Building a translator such as described here would be a first step to doing that.  Not sure it's worth it... but fun to think about.

https://yaml.org/spec/1.2.2/#chapter-1-introduction-to-yaml

**Comment by petersilva** [comment]
might want to look at, it lists the translation things:

* https://metpx.github.io/sarracenia/How2Guides/UPGRADING.html

It would probably be good to have this functionality.

**Comment by petersilva** [comment]
if you have time after the mqtt stuff, we should talk about this... I more and more think this would be great to have, and it should be straight-forward...

**Comment by petersilva** [comment]
probably an easy way to do a standalone tool would be to 

Have a thing that accepts A and B as arguments.
Look up whole line in sarracenia.config.convert_to_v3
Look up 1st field in line in sarracenia.config.synonyms
 
following parsing code extracted from sarracnia.config..

```

import sarracenia.config

with b as opent(B,'w'):
    a = open(A,'r')
     for i in a.readlines():
          l = i.strip()
          line = l.split()
          k = line[0]
          if k in sarracenia.config.Config.synonyms:
                k = sarracenia.config.Config.synonyms[k]
            if (k in sarracnia.config.convert_to_v3):
                self.log_flowcb_needed |= '_log' in k
                if (len(line) > 1):
                    v = line[1].replace('.py', '', 1)
                    if (v in convert_to_v3[k]):
                        line = convert_to_v3[k][v]
                        k = line[0]
                        if 'continue' in line:
                            logger.info( f'{cfg}:{lineno} obsolete v2: \"{l}\" ignored' )
                        else:
                            logger.info( f'{cfg}:{lineno} obsolete v2:\"{l}\" converted to sr3:\"{" ".join(line)}\"' )
                else:
                    line = convert_to_v3[k]
                    k=line[0]
                    v=line[1]
            if k == 'continue':
    
```
the code there is mostly copy/past from config.py (just search for convert_to_v3 to find it.)

if you use those existing data structures in the new code... (via import)
There is no danger of having to update multiple places when converting...
and the script can be short and simple.

**Comment by petersilva** [comment]
oh... there are writes missing... oops... exercise left to the reade :-)

**Comment by cleaaum** [comment]
Thank you ! So I am wondering is this is the same procedure as what we were supposed to do with the configs in dev-px5/6 to translate the configs? is this just a way to automate that process?

**Comment by petersilva** [comment]
It automates the mechanical part of the work... rather than copying the
files over manually and then editing them,
the easy substitutions are done by the script.  but some plugins will cause
problems and require extra work.

It should make the conversion a lot easier and quicker.

**Comment by cleaaum** [comment]
Idea for now: use the command _sr3 convert component/config_ to convert a v2 config to a v3 config. Here, component/config is in the ~/.config/sarra/x/y directory and we write a new translated config into the ~/.config/sr3/x/y directory. 

My first patch enables the _convert_ action as a command, and theres a basic function in sr.py called _config_converter()_. For now it simply copies all contents of a v2 config to the v3 config directory. Next patches will actually translate.

**Comment by petersilva** [comment]
Please rebase from v03_wip... the patches are huge because of the yapf run...

**Comment by petersilva** [comment]
oh, and the approach sounds reasonable.  :-)

**Comment by cleaaum** [comment]
Update: I added the code in the flow_setup script to test the converter for the flow test. These are the current failing tests (better than the 13/31 I was getting). The C related tests are expected to fail.

test 4 FAILURE: compare contents of downloaded_by_sub_u and posted_by_shim differ
test 5 FAILURE: compare contents of downloaded_by_sub_amqp and linked_by_shim differ
test 6 FAILURE: compare contents of posted_by_shim and sent_by_tsource2send differ
test 7 FAILURE: compare contents of downloaded_by_sub_amqp and cfile differ
test 26 FAILURE: no successful results, 2nd item! post test2_f61         (1111) should have about half the number of items as shim_f63   (0)
test 28 FAILURE: no successful results! cpost both pelles should post the same number of messages (0) (0)
test 29 FAILURE: no successful results! cdnld_f21 subscribe downloaded (0) the same number of files that was published by both van_14 and van_15 (0)
test 30 FAILURE: no successful results! veille_f34 should post as many files (0) as subscribe cdnld_f21 downloaded (0)
test 31 FAILURE: no successful results! veille_f34 should post as many files (0) as subscribe cfile_f44 downloaded (0)
test 32 FAILURE: Overall 22 of 31 passed (sample size: 1111) !

**Comment by petersilva** [comment]
OK why are all the trees different... did you look at the sums/ sub-directory of log (which has the checksums of all files in each tree... it is what those comparisons are based on.... if it is one file or something, that is probably fine... if there are a lot of things... hmm...

**Comment by cleaaum** [comment]
Well I added it in case the answer was yes (only an extra few lines). If not necessary we can just delete the branch. Also its recursive - hope that is ok.

**Comment by petersilva** [comment]
help stuff added and merged. Great!
