### ISSUE TITLE
Implement CI/CD (replacement of Travis-ci.com) and auto test, and auto-builds.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#445]
We had CI/CD wit builds on every commit working with Travis-ci using free account.
Policy change at vendor.  now no free access.  Need to strategize.

**Comment by petersilva** [comment]
got  .github/workflows/static_flow.yml added to v03_main branch.   The test now passes (most of the time? why not always, I triggerred and re-run and it fixes it.)  Added a badge for that also.

added flakey_flow also, but it doesn't pass, and I think that failure reflects reality... I don't think flakey fully works on my local machine either... so that is staying on v03_issue445 branch for now.

**Comment by petersilva** [comment]
Now we have one example flow... Other flows to implement:

* static_mqtt_flow (change MQP=mqtt in default.conf, run static test.)
* flakey_flow (not yet working, involves fixing flakey_flow.)
* flakey_mqtt_flow
* dynamic_flow
* dynamic_mqtt_flow

The ones that don´t mention mqtt are using rabbitmq as internal broker, rather than mosquitto.
It may make more sense to label with with _amqp_ ... (e.g. static_amqp_flow)

**Comment by petersilva** [comment]
These are all done using a vm approach.  Could also build some based on a more de-composed / cloud-centric way.

**Comment by petersilva** [comment]
good inspiration: git clone https://github.com/SynoCommunity/spksrc
* auto-build on pull request, and much more.
* auto- build binary packages...
* hint from @th0ma7

**Comment by petersilva** [comment]
should also add build/test for different python version.  3.6, 3.7, 3.8, 3.9, as well as 3.10.

**Comment by reidsunderland** [comment]
See note on #407.

When Python is installed using the [setup-python](https://github.com/actions/setup-python) action, any packages that were installed using apt (e.g. `python3-xattr`) are not available to this Python version.

We are going to modify `flow_autoconfig.sh` to install necessary packages using pip in these situations, but we might want to 
 ensure that pip is not used for Python versions that are included in Ubuntu versions.

For example:

| OS                  | Python Version     | Python Package Source |
|----------------|---------------|-------------------------|
| Ubuntu 20.04 | 3.10             |  pip  |
| Ubuntu 20.04 | 3.9                | pip |
| Ubuntu 20.04 | 3.8 (default) | Ubuntu apt |
| Ubuntu 18.04 | 3.10             |  pip  |
| Ubuntu 18.04 | 3.9                | pip |
| Ubuntu 18.04 | 3.8          | pip |
| Ubuntu 18.04 | 3.6 (default)          | Ubuntu apt |

One way to do this might be to disable/not use the [setup-python](https://github.com/actions/setup-python) action for Python 3.8 on Ubuntu 20.04 and Python 3.6 on Ubuntu 18.04?

**Comment by petersilva** [comment]
perhaps remove pip install . from above flow_autoconfig.sh  in the github workflow?  the flow_autoconfig.sh should take care of installing everything needed.

**Comment by petersilva** [comment]
The matrix is great... it goes most of the way, but it is still only on ubuntu-latest.  ideally would have job test ubuntu 22.04 (jammy) 20.04 (focal), and 18.04 (bionic) as well.

**Comment by petersilva** [comment]
debian packaging might work on ubuntu 22.04, but not sure if it will work on any earlier release.

**Comment by reidsunderland** [comment]
Adding `erlang-diameter` and `erlang-eldap` to the `flow_autoconfig.sh` script's `apt install` line fixed it.

```
Reading package lists...
Building dependency tree...
Reading state information...
findutils is already the newest version (4.6.0+git+20170828-2).
net-tools is already the newest version (1.[60](https://github.com/MetPX/sarracenia/runs/5755565266?check_suite_focus=true#step:4:60)+git201[61](https://github.com/MetPX/sarracenia/runs/5755565266?check_suite_focus=true#step:4:61)116.[90](https://github.com/MetPX/sarracenia/runs/5755565266?check_suite_focus=true#step:4:90)da8a0-1ubuntu1).
openssh-server is already the newest version (1:7.6p1-4ubuntu0.6).
librabbitmq4 is already the newest version (0.8.0-1ubuntu0.18.04.2).
librabbitmq4 set to manually installed.
python3-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.5).
git is already the newest version (1:2.35.1-0ppa1~ubuntu18.04.1).
The following additional packages will be installed:
  erlang-asn1 erlang-base erlang-corba erlang-crypto erlang-edoc
  erlang-erl-docgen erlang-eunit erlang-ic erlang-inets erlang-mnesia
  erlang-odbc erlang-os-mon erlang-parsetools erlang-public-key
  erlang-runtime-tools erlang-snmp erlang-ssh erlang-ssl erlang-syntax-tools
  erlang-tools erlang-xmerl libjs-sphinxdoc libjs-underscore librabbitmq-dev
  metpx-sr3 ncftp python3-amqp python3-appdirs python3-argcomplete
  python3-argh python3-cffi python3-humanize python3-jsonpickle
  python3-paramiko python3-pathtools python3-ply python3-psutil
  python3-pycparser python3-vine python3-watchdog python3-xattr socat
Suggested packages:
  erlang erlang-manpages erlang-doc xsltproc fop erlang-ic-java
  python-amqp-doc python3-simplejson python3-numpy python3-gssapi
  python-ply-doc python-psutil-doc
The following packages will be REMOVED:
  esl-erlang
The following NEW packages will be installed:
  erlang-asn1 erlang-base erlang-corba erlang-crypto erlang-diameter
  erlang-edoc erlang-eldap erlang-erl-docgen erlang-eunit erlang-ic
  erlang-inets erlang-mnesia erlang-nox erlang-odbc erlang-os-mon
  erlang-parsetools erlang-public-key erlang-runtime-tools erlang-snmp
  erlang-ssh erlang-ssl erlang-syntax-tools erlang-tools erlang-xmerl
  libjs-sphinxdoc libjs-underscore librabbitmq-dev metpx-libsr3c
  metpx-libsr3c-dev metpx-sr3 metpx-sr3c ncftp python3-amqp python3-appdirs
  python3-argcomplete python3-argh python3-cffi python3-humanize
  python3-jsonpickle python3-paramiko python3-pathtools python3-ply
  python3-psutil python3-pycparser python3-vine python3-watchdog python3-xattr
  rabbitmq-server socat xattr
0 upgraded, 50 newly installed, 1 to remove and 102 not upgraded.
```

Opened PR #495.
