### ISSUE TITLE
`sr3 remove` fails, must `sr3 stop` already stopped, then `sr3 remove` works...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#447]
Take a configuration that was stopped normally (or perhaps run in the foreground) 
Some config that is otherwise now not running, `sr3 remove` refuses to remove on first try... must `sr3 stop` the stopped config... then `sr3 remove` works... 

```sh
fractal% sr3 status
status: 
Component/Config                         State        Run  Miss   Exp Retry
----------------                         -----        ---  ----   --- -----
subscribe/dd_amis                        stopped        0     0     0     0
      total running configs:   0 ( processes: 0 missing: 1 stray: 0 )
fractal%

fractal% sr3 remove subscribe/dd_amis
2022-01-31 13:53:12,242 [ERROR] root remove cannot remove subscribe/dd_amis while it is running! 

fractal% sr3 stop subscribe/dd_amis
Stopping: ...already stopped

fractal% sr3 remove subscribe/dd_amis
2022-01-31 13:53:22,288 [INFO] root remove removing /home/peter/.config/sr3/subscribe/dd_amis.conf 
```

**Comment by petersilva** [comment]
there is a similar bad display...  if a configuration is disabled (it's configuration is renamed to .off it shows up as "stopped" instead of disabled.

Also some use cases (docker) want config directories to be read-only.
we could re-implement *disable* but having a file exist in the state directory instead of renaming a config file.  I'm not sure if this is part of the same issue or not?

**Comment by cleaaum** [comment]
Looking at this stopped instead of disabled issue now - I am not able to reproduce the bug. It shows up as disabled for me when it is renamed to .off. Was it maybe only happening for a specific component?

**Comment by petersilva** [comment]
as discussed... it only happens with "foreground" ...

**Comment by cleaaum** [comment]
I also added an exception for the KeyboardInterrupt everytime you stop a config in foreground. It displays two lines now instead of the whole exception.

**Comment by petersilva** [comment]
merged!
