### ISSUE TITLE
code reference.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#463]
Reviewing api documentation, we want to have a comprehensive code 'code reference' to display documentation of entire source tree, separate from the much smaller API reference.

new issue for that.

something to do with sphinx-apidoc.

**Comment by petersilva** [comment]
manually buildiing things noticed:
* the apidoc seems to invoke the python or perhaps part of importing... so any standalone scripts that run get executed.
* need to exclude standalone scripts sarracenia/examples/*.py
* the plugins/  is for v2 plugins, likely best to exclude those as well.


built a list like so:
```

find sarracenia -type f -name '*.py' | sed 's+/+.+g' | sed 's/\.py$//g' | sed 's/\.__init__//g'  | egrep -v 'examples|plugins|sarracenia.sr_|sarracenia.sr' >module_list

```
builds a module_list than you can then create a static code.rst with...
then run this python to build an rst source snippet:

```
f=open('module_list','r')

for l in f.readlines():
    m=l.strip()
    print( '%s\n%s\n' % ( m, '-'*len(m) ) )
    print( f'.. automodule:: {m}' )
    print( f'   :show-inheritance:')
    print( f'   :members:')
    print( f'   :private-members:')
    print( f'   :special-members:')
    print( '' )

f.close()
```

Can built a static one for now... but would be much better to have something that used autowhatever properly.

**Comment by petersilva** [comment]
uh... @reidsunderland ? I think the manually built one is fine... I have re-arranged it in a bunch of different ways, so it is substantially manually tweaked now.  split into code.rst and flowcb.rst (for just the callbacks.)
I think we can just close this...

**Comment by reidsunderland** [comment]
Sure, that works for me. Thank you!
