### ISSUE TITLE
sr3 shows files that don't end in conf...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#480]
```
cd ~/.config/sr3/subscribe
echo hohoconf >hoho.conf~
echo hohoconf >hohoconf
echo hohoconf >hohoconf.off
echo hohoconf >hohoconf.tmp

fractal% sr3 status
status: 
Component/Config                         State        Run  Miss   Exp Retry
----------------                         -----        ---  ----   --- -----
subscribe/hoho.conf~                     stopped        0     0     0     0
subscribe/hohoconf                       stopped        0     0     0     0
subscribe/hohoconf.off                   stopped        0     0     0     0
subscribe/hohoconf.tmp                   stopped        0     0     0     0
      total running configs:   0 ( processes: 0 missing: 0 stray: 0 )
fractal% 

```

sr3 should only display files that end in .conf

**Comment by petersilva** [comment]
um... the files should not be read as 'configs' unless they end in .conf.  
for example, if you look in v2 config directories are more .inc files than .conf... those .inc files should never show up in status.  so when reading the configs, my guess is that it should simply ignore files that to not end in .conf

**Comment by cleaaum** [comment]
Okay I fixed the logic. Now I am just wondering if the state "unknown" is even useful anymore since it was only given to files that don't end in .conf or .inc. If we skip these files then "unknown" seems useless now.

**Comment by petersilva** [comment]
unknown was there because originally the logic set all states to unknown, and then as the state was determined it was changed.  That way, if there is a bug in the logic and some conf is not identified as stopped, partial, or started, it would be obvious, since it would say 'unknown'.

**Comment by petersilva** [comment]
when you are comfortable and it is passing flow tests for you, please submit a pull request.
