### ISSUE TITLE
Add mqtt broker testing in CI/CD flow testing.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#506]
noticed a commit had completely broken mqtt support.   95b48fbc4a27b336f9925ffea8773a4a0231534b
and it was there for a while without detection, until I started testing mqtt again.
fixed by: f24613384227038df6ccdac300918c933386784f

need to add flow testing that includes mqtt to prevent such regressions.

**Comment by petersilva** [comment]
mosquitto broker is used for internal ...

**Comment by petersilva** [comment]
I think having reliably working MQTT support is a must have for sr3.

**Comment by petersilva** [comment]
working on this branch... v03_wip_issue506.  What I have learned so far:
* mqtt support was completely broken when encodings were introduced in April, sigh...
* mqtt support that was there was initially targetted at supporting only v03 format (encoding.)
* mqtt now supports v02 format also.
* topic are now fully separated from message decoding.

so now the above is working in the branch... but the flow tests still fail horribly... I think there are some message loss issues.
so the question is, do I merge this v03_wip and keep working? or maintain a long running parallel branch?

I'm tending towards merging, and then keep working some more on the branch.

**Comment by petersilva** [comment]
merged... but continuing to work on the branch...

**Comment by petersilva** [comment]
OK more work on the branch now passing like 34/37 tests... but there is still one case where it looks like directory posts are disappearing.

**Comment by petersilva** [comment]
new branch v03_issue506_3 being spawned as result of squash merge of previous work.    tests with mqtt still do not quite pass working on it.

**Comment by petersilva** [comment]
All work in progress has been merged... There is now the static_flow and dynamic_flow in the CI/CD running on every commit to v03_wip. Unfortunately, other tests do not work reliably yet.

* flakey_broker
* restart_broker

Still fail... so it's not done... but it is at least a little bit in the CI/CD...

**Comment by petersilva** [comment]
I moved this from blocker to in progress, because it mqtt is now in the CI/CD... so it should stay non-broken.

**Comment by petersilva** [comment]
@reidsunderland  fixed amqp.py for restarts (option to drain retry queue on exit.) and something about returning instead of looping... could be the root cause of the above failures.

**Comment by reidsunderland** [comment]
Maybe that's not it... there was a `while True` loop in putNewMessage for AMQP so it would loop on failure and never return False. But I just looked and MQTT doesn't have a loop so it would be returning False on an error and the message would go into the post retry queue.

**Comment by petersilva** [comment]
update:  
* work on #617 had re-broken MQTT, but after patches last two days, back to status quo:  static and dynamic pass, but none of the tests with error recovery (flakey & restart) do.

* Also, now that we have "maint"... that test does not support MQTT at all.

**Comment by petersilva** [comment]
ok, so now MQTT is working in normal circumstances. and provably so.
the error recovery cases (tested by flakey_broker and restart_server) are not working.  Will open a new issue for that ( #693 ) but at least this will keep mqtt support from breaking invisibly.
