### ISSUE TITLE
sarracenia.encoding.v02 ERROR

### ISSUE THREAD

**Issue by endlisnis** [MetPX/sarracenia#515]
A recent update to v3_wip branch cause this chatter in my logs for every download:

2022-04-14 21:09:45,673 [ERROR] sarracenia.encoding.v02 mine asking for: text/plain, comparing to text/plain

**Comment by petersilva** [comment]
sorry. leftover debugging stuff. removed.

**Comment by petersilva** [comment]
cf7ad157fd131b2c62c5bbdc9b0c5b833bc488c3

**Comment by endlisnis** [comment]
I no longer see this.
