### ISSUE TITLE
Ubuntu 22.04: add to GitHub Actions Flow Tests (pre-requisite: build packages for 22.04)

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#520]
Ubuntu 22.04 is now available for use in GitHub Actions: https://github.com/actions/virtual-environments/issues/5490

I tried adding it to the matrix, but there is no sarrac package available so it fails: https://github.com/MetPX/sarracenia/runs/6390311450?check_suite_focus=true

**Comment by petersilva** [comment]
for v03, the c package should be called metpx-sr3c. Indeed it was missing...
It's built now ;-)

https://code.launchpad.net/~ssc-hpc-chp-spc/+recipe/metpx-sr3c-daily

**Comment by reidsunderland** [comment]
Thank you!

The error was "No Sarra C package available. Cannot test." from [sr_insects/prereq.sh](https://github.com/MetPX/sr_insects/blob/main/prereq.sh#L81) so "sarrac" was my mistake.

It works! https://github.com/MetPX/sarracenia/runs/6395381021?check_suite_focus=true 🎉
