### ISSUE TITLE
DESTFNSCRIPT  porting advice

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#536]
figure out how people are supposed to modify DESTFN plugins to work in sr3.

**Comment by MagikEh** [comment]
DESTFN ~= DESTination File Namer

Works on a per-accept statement basis and defines the file's final name to be applied on the destination server.

**Comment by petersilva** [comment]
in sarracenia/__init__.py there is, in updateFieldsAccepted(...

```

       if options.destfn_script:
            options.new_file = filename
            ok = options.destfn_script(options)
            if filename != options.new_file:
                logger.debug("destfn_script : %s becomes %s " %
                             (filename, options.new_file))
                filename = options.new_file
                token[-1] = [filename]

```

Which I think will either crash, or at best, do nothing good.
Probably need to think about a modernized API... maybe accepting a message ?

**Comment by petersilva** [comment]
difference between DESTFNSCRIPT and an after_accept:

* the after_accept operates on a group of messages, the script on a single message.
* The DESTFNSCRIPT scope is an accept statement (only applies when a given accept is triggering treament.) 

One proposal:
* feed it a message. have it return a modified message.

**Comment by petersilva** [comment]
Another option is to invoke v2 encapsulation.  This involves building a v2 message, calling the script, and then "noticing" all the changes in the v2 one to bring back to the v3 one.   would make old scripts work unchanged, but likely be very expensive at run time.

**Comment by petersilva** [comment]
OK... have a mechanism... it is kind of clumsy...


* moved the routine updateFields from sarracenia/__init__ .py -> flow/__init__.py
* moved the routine sundew_getDes* from config.py -> flow/__init__.py 
* with the two moves, it means can be invoking destfn with the right parent (can have an entry point in flow, and use flowcb class as parent class.)
* added destfn as an entry point to flowcb ...   destfn( self, msg ) -> str:    self.o has the options... 
* added destfn subdir to flowcb/

**Comment by MagikEh** [comment]
Resolved by pr [550](https://github.com/MetPX/sarracenia/pull/550)!
