### ISSUE TITLE
generalize ${X-yD} parsing to work with a sarra interval.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#55]
There is some hard coded parsing that sees a substitution such as:

${YYYYMMDD-1D}  and manually substitutes subtracting 1 day (24*3600) from the current time to calculate the value.  Ideally the code would parse the value after the minus sign as a sarra interval,
so you could enter 1h, 3w, 1m or 4d and it would all be correctly dealt with.

This would enhance consistency with the rest of the configuration language.

**Comment by petersilva** [comment]
Hey Wahaj? This is done, right? You have the honour of closing the issue.

**Comment by MuhammadWahajTaseer** [comment]
Yes, it's done!

**Comment by petersilva** [comment]
Kurt Hoffmann says this doesn´t work in sr_poll to a remote directory.   Missing case.

**Comment by Wahaj10** [comment]
Just talked to Kurt about it, turned out to be a configuration issue.
