### ISSUE TITLE
Improve RPM packaging.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#57]
currently using distutils RPM packaging.  It doesn´t do dependencies, it doesn´t install man pages.
It is only minimally in the correct format.

**Comment by petersilva** [comment]
need to figure out how to use: https://openbuildservice.org/help/

**Comment by petersilva** [comment]
current procedure: https://github.com/MetPX/sarracenia/blob/master/doc/Install.rst#redhatsuse-distros-rpm-based

**Comment by petersilva** [comment]
Salut Ben, 

tel que discuté, de faire en sorte que OBS marche serait vachement bien.

**Comment by benlapETS** [comment]
Oui je m'occupe de cela aussitot que #184 est regle

**Comment by benlapETS** [comment]
Ok, it is possible to build rpms through OBS, like I easily did for an openSUSE distro. The result of that is available [here:](https://software.opensuse.org//download.html?project=home%3Ablapointe%3Ametpx%3Asarracenia%3AopenSUSE&package=metpx-sarracenia). The package are missing several dependencies but at this point I just wanted to show that was feasible.
The real show stopper is for CentOS and RHEL distros. It looks like a more bumpy road to deploy RPMs through OBS there. I did several experiments trying to work around the main show stopper that kvm-qemu image provided for each of those OSes does not include python3 and it seems impossible to activate it easily through the .spec file. Python 3 installation would require to go through SCL that is unmanageable by the .spec file in OBS. The current state of my experiment can be consulted [here](https://build.opensuse.org/package/show/home:blapointe:metpx:sarracenia:centos/metpx-sarracenia#). It as a commit history which speak for itself of every possible workaround that I tried.

**Comment by petersilva** [comment]
gave it a good try... leave it aside for now...

**Comment by petersilva** [comment]
in v03, added dependency to the bdist_rpm stuff for what the package names should be. Confirmed that it installed well on fedora34 with dnf... so some progress.

**Comment by petersilva** [comment]
This is solved by #740 went through a lot of work that builds perfect RPM's for fedora39, and likely redhat 9.
It is likely that there is no solution for older releases.
