### ISSUE TITLE
1112 poll items... um... why?

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#573]
many of the tests have 1 extra item, being polled.
in static and flakey we should see 1111 items polled, but there is a single, extra item.

**Comment by petersilva** [comment]
@tysonkaufmann reproduced the problem... he sees one file being posted twice.   the downstream subscriber rejected is (checksum) but why is the poll posting twice?  working on a new environment to help debug.

**Comment by tysonkaufmann** [comment]
From testing it seems that sometimes the last item in the worklist on a poll appears as the first item in the subsequent worklist on the next batch. Needs more testing.

**Comment by petersilva** [comment]
fwiw... this is actually annoying at this point.. there is a stubbornness where one test will fail (e.g. static_flow on ubuntu 18.04) and it will fail upto four times before finally succeeding...  so it would be a good thing to sort this out.  Now is probably a good time to look into it, because just when through weeks of tumoil of adding "directory" events (causing changes in all tests.)

The addition of the directory events seems to have made things closer to perfect, and more consistent, so it is less off than it used to be, but it seems to be more consistently slightly off than it used to be.

**Comment by petersilva** [comment]
OK, I found one source of this issue... when cpost notices files, it notices them immediately (no batching.) so, timing dependent, for some files it gets a first event from INOTIFY about the CREAT (0 bytes) and then a subsequent event with the modify writing the correct content.  that is the source of a handful of extra files in cveille stuff. (cpost... not poll.) not sure if that is the whole thing though.  patch here:

https://github.com/MetPX/sr_insects/commit/aef440042ba3b6d7205aba3fdc7c84335bb68b77

**Comment by petersilva** [comment]
similar thing for downloading of the zero byte files noticed by veille...

https://github.com/MetPX/sr_insects/commit/0652de39fc1242013e7f790d0869fdf202469b53

**Comment by petersilva** [comment]
I'm not seeing the poll error at all in current testing... but there is another error where one of the file tree comparisons fail...   c amqp vs. cfile...  hmm...
