### ISSUE TITLE
Get French man pages reviewed by knowledgeable francophones

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#58]
La traduction initiale à été éffectué par http://deepmind.com, qui est parmi le meilleurs traducteurs basé sur l´intelligence artificielle, mais il reste que ce n´est pas suffisant.  Il reste plein d´incohérences dans les docs. Plusieurs on passer à travers des bouts de la doc, mais il faut continuer à reviser.

**Comment by petersilva** [comment]
Alain St-Denis did some drudgery... confirmed it is awful...

**Comment by petersilva** [comment]
Sandrine did some more... yup, the rest is still awful.

**Comment by petersilva** [comment]
On a eu des fleurs d´un usager.  Yé!

**Comment by MagikEh** [comment]
Closing old issue in favor of new one #539.
