### ISSUE TITLE
debating how to set acceptUnmatched

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#601]
In the filter phase, we have a list of incoming messages.
* we expose them to all reject/accept clauses.
* there are messages which have not been explicitly matched.
What do we do with them?

Currently, we require a manual setting *acceptUnmatched* .

With *acceptUnmatched True*, those files are accepted.

*AcceptUnmatched on* is entirely equivalent to accept .*  (except it is faster because no regex to evaluate. (fixed by faf73a55b9304be800c6e287f339cf2b1ccd5fdb)

We set the default to a fixed value:

in flow/
     __init__.py : False
    poll: True
    post: True
    report: True
   sarra: True
   sender: True
   subscribe: False
   watch: True
   winnow: True

ugh...  but I think the real issue here is whether there are accept/reject patterns provided.
If we want acceptUmatched to be set to something that makes sense, it would be based on the contents of the accept/reject patterns.

case 1: no patterns at all provided...

* if there are no accepts or rejects provided, then setting acceptUnmatched to False resorts in nothing ever being processed, which is useless. It makes more sense for it to be automatically set to True

case 2: only rejects in patterns... again results in nothing ever being accepted if the default is False... so again it makes sense to set it to True

case 3: only accepts in patterns... seems logical, anything not explicitly accepted is rejected.  So in this case, it should be set to False

case 4: mix of rejects and accepts... seems logical to reject anything not explicitly accepted. so it would be set to False.

If we take the above 4 cases

Say we apply logic: that uses the above four cases to decide what to do.

imagined case 5: started with only rejects...
```

reject my1.*
reject my4.*

```

so take case 2... only rejects in pattern.. so guessing that everything else is accepted... 
If you receive files   

received flow: my1file, my2file, my3file, my4file, my5file.

accepted flow: my2file, my3file, my4file, my5file

now say you add an accept...

```

reject my1.*
accept my2.*
reject my4.*

```

for the same input flow...

received flow: my1file, my2file, my3file, my4file, my5file.

accepted flow: my2file

according to case 4, now because you added an accept, acceptUnmatched flips to false so you surprisingly accept fewer files than before...

hmm...  Does that make this more confusing than helpful?

option 1: current state

it just is set to a default per flow, that makes sense.

in v2, many poll configurations from internal examples seem to expect *acceptUnmatched True*, but it is currently False.  Changine that...  ( 5b41ec299df655c1d113ce83820e26a529b3878d )

Ideally, the goal would be to get rid of acceptUnmatched, and just have it do the right thing always, but case 5, makes me thing that getting rid of it is inelegant.  Need a better idea for how to set it automatically.

**Comment by andreleblanc11** [comment]
It all depends on the way the accept/reject clauses are set up in the case 4 you've described. Since accept/reject are based on REGEX patterns, there shouldn't be more than one accept and reject per config in my opinion. It could summarize all of the desired accepts into one line.

With that in mind, `acceptUnmatched` would be better off to be set to `False` in all cases since all of the desired accepts would have already been treated while respecting the rejects. This takes into consideration that `accept` comes prior to `reject` inside of the config.

Maybe though im not understanding how the clauses exactly work lol. Is there a use case where using `reject` or `accept` more than once was necessary?

**Comment by petersilva** [comment]
There are hundreds of cases in existing configurations with many reject and accept clauses.  If you want to put files in different directory trees, then you have multiple directory settings, with an appropriate accept for each directory.  Just have a look at ECCC internal configurations and grep for reject and accept.

**Comment by petersilva** [comment]
I'm leaning towards making * acceptUmatched true* the default for all components.  that is how it is currently set in sr3 for all components except subscribe... and that yields the best compatibility with v2.  But making this change is just an incompatibility for subscribe... perhaps can use the v2 to sr3 conversion stuff to deal with that change in defaults, then it would be clean.

**Comment by petersilva** [comment]
ok did this for sr3-3.00.25.
