### ISSUE TITLE
Config file overrides options given at cli

### ISSUE THREAD

**Issue by MagikEh** [MetPX/sarracenia#701]
`sr_shovel --debug foreground $CONF` has the `--debug` flag overwritten by the `loglevel warning` given in the $CONF. 

Observed in sarra v2.21.08

**Comment by MagikEh** [comment]
We stumbled upon this one while following up a page on the regional servers. Will need to be confirmed in recent versions.

**Comment by petersilva** [comment]
logging is really, really complicated in v2. Don't even try to fix it.
