### ISSUE TITLE
AM server plugin needs to listen on IP addresses that show up after startup.

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#722]
Related to ACDC 21631.

If a node is running an AM server and "obtains" a new IP address after the AM server has started, what happens?

For example, two servers are set up with two shared VIPs:

- node1 is primary node for 1.2.3.4 and backup for 1.2.3.5 
- node2 is primary node for 1.2.3.5 and backup for 1.2.3.4

Both nodes are running an AM server, listening for connections on port 5000.

Then node2 goes down, and node1 has both VIPs, 1.2.3.4 and 1.2.3.5.

If this happens in Sundew, the observed behaviour is that Sundew only listens for AM connections on 1.2.3.4 and nothing is listening to 1.2.3.5. I haven't verified this in the Sundew code.

The behaviour that we want is for the amserver plugin to listen for and accept connections from both (any?) IP address(es) without needing any manual intervention (restart).

The amserver plugin might already work the way we want it to, but we should verify and test.

**Comment by andreleblanc11** [comment]
The way the AM plugin works as of now is that the bind address is specified in the configuration file as `sendTo am://$HOST:$PORT`. In the example file, https://github.com/MetPX/sarracenia/blob/v03_wip/sarracenia/examples/flow/amserver.conf#L12, we use `0.0.0.0` so it accepts connections from anybody trying to connect to `$PORT`

While we were testing last year, we encountered a problem that we would accept random connections from random hosts so we added the `AllowIPs $IPv4_addr` option to limit the accepted range of hosts. 

So the AM plugin *should* already be adapted for this use case, but yes we should still test this to make sure of it 😄

**Comment by petersilva** [comment]
do this experiment:

* start up am server.
* Add a new ip address to the server, in addition to the existing ones, without restarting the flow.
* use a sender to try to connect to the server via the new ip address.

If that works, then we can close the bug report.

**Comment by petersilva** [comment]
if it does not work, then that is what we need to fix.... so it is helpful no matter what.

**Comment by petersilva** [comment]
might want to add SIGHUP process to restart the socket so it starts the listen again on receipt.

**Comment by andreleblanc11** [comment]
Did a test on the ncps.

I added a vIP on one of the nodes, added a new sender to send to that vIP (without restarting the local AM server).

It was able to receive new connections with that vIP.

**Comment by petersilva** [comment]
If that works, then we just close this issue as done!?

**Comment by andreleblanc11** [comment]
Yeah, I think so.

**Comment by andreleblanc11** [comment]
@reidsunderland what do you think?

**Comment by reidsunderland** [comment]
yeah I think it can be closed. That's great that it works
