### ISSUE TITLE
strip parameter should not be a global setting

### ISSUE THREAD

**Issue by EricFunk** [MetPX/sarracenia#80]
When mirroring data using sr_subscribe or sr_sender one may want to have differing levels of stripping the sub-directories within the same configuration file. 

For instance:

mirror true

subtopic *.hydrometric.csv.#
directory      /dir1/
strip 2
accept          .*

subtopic *.analysis.precip.hrdpa.grib.polar_steropgraph.#
directory      /dir2/
strip 5
accept          .*

Currently it would just use 'strip 5' for everything despite the 'strip 2' being present.

**Comment by petersilva** [comment]
while we are at this, likely want to make *mirror* setting depend on placement in the file as well.

**Comment by petersilva** [comment]
OK made a patch. I know it doesn't break anything, but someone would need to test it out.
perhaps build package locally, or try a daily.
