### ISSUE TITLE
`sr3 declare` vs `sr3 setup` in documentation

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#803]
https://metpx.github.io/sarracenia/Reference/sr3.1.html#actions

This says:
- "declare: creates the component’s resources on the server."
- "setup: like declare, additionally does queue bindings."

In the code declare and setup do the same thing.

**Comment by petersilva** [comment]
I was there... it was easy... please check out the PR.
Ended up just removing references to the setup command... so it was just deletions.
