### ISSUE TITLE
Unable to setup

### ISSUE THREAD

**Issue by yraheja77** [MetPX/sarracenia#845]
I am trying to setup downloading alerts using sarracenia and as a first step tried to download using dd_all.conf
The only thing I changed in the conf file is the directory. Rest all settings are as the example conf.
In the log files it gives an error 

"sarracenia.moth.amqp getSetup AMQP getSetup failed to dd.weather.gc.ca with [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)"

What am I doing wrong here?

[dd_all.conf.txt](https://github.com/MetPX/sarracenia/files/13495694/dd_all.conf.txt)

[subscribe_dd_all_01.log](https://github.com/MetPX/sarracenia/files/13495706/subscribe_dd_all_01.log)
[subscribe_dd_all_02.log](https://github.com/MetPX/sarracenia/files/13495707/subscribe_dd_all_02.log)
[subscribe_dd_all_03.log](https://github.com/MetPX/sarracenia/files/13495708/subscribe_dd_all_03.log)
[subscribe_dd_all_04.log](https://github.com/MetPX/sarracenia/files/13495709/subscribe_dd_all_04.log)
[subscribe_dd_all_05.log](https://github.com/MetPX/sarracenia/files/13495710/subscribe_dd_all_05.log)

**Comment by petersilva** [comment]
you can try adding:
```
tls_rigour lax

```
to the configuration file.... it might stop complaining about the mismatch, and work anyways.  The cert on our server is good, so is it possible there is an HTTPS_PROXY, say at a firewall that makes all the SSL certs get replaced? you might need to set HTTPS_PROXY (google for python HTTPS_PROXY for guidance on that.)
or just leave the setting at lax.

**Comment by petersilva** [comment]
closing ticket as source is non-responsive.  Can always open it up again if need be, just de-cluttering.
