### ISSUE TITLE
source_from_exchange not working (3.00.50)

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#860]
(messages waiting: 9)
2023-12-07 21:35:09,313 [INFO] sarracenia.moth.amqp getSetup binding q_feeder_sarra.get-ncep-gfs.06289546.49055673 with v02.post.pub.data.nccf.com.gfs.prod.# to xs_NOAA-NWS_ncep_gfs (as: amqp://feeder@ddsr-dev.cmc.ec.gc.ca/)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 248, in <module>
    i.start()
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 239, in start
    self.running_instance.run()
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 453, in run
    self.filter()
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 1059, in filter
    self.o.flatten)
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 817, in updateFieldsAccepted
    new_dir = self.o.variableExpansion(maskDir, msg)
  File "/usr/lib/python3/dist-packages/sarracenia/config.py", line 2129, in variableExpansion
    new_dir = new_dir.replace('${SOURCE}', message['source'

**Comment by petersilva** [comment]
#760 is BAAACKK!?

**Comment by petersilva** [comment]
work around as before is:

```

source NOAA-NWS

```
in the config.  but it should find it without having to do that.

**Comment by petersilva** [comment]
have a branch issue860:

I don't have obvious ways of reproducing the problem.  I don't know the root cause.  So... looked at the v2 code, and saw that the source from message stuff is being applied in v2 on receipt, rather than later one, as is done in sr3.  It looks like v2's method is right, so created similar logic.

There is an unrelated fix in the branch that I saw in one case RJ was trying, and another case I ran into myself, where I thought it was the first line of a configuration file caused a crash in the whole configuration parsing... but that isn't it... so unclear how to reproduce.

**Comment by andreleblanc11** [comment]
It looks like there's still a problem with sourceFromExchange on V3.00.50rc4

Here's how I was able to find `sourceFromExchange` to be broken..
```
grep source sarra/$CONFIG.conf
sourceFromExchange True

sr3 show sarra/$CONFIG.conf | grep source
 'source': 'feeder',
 'sourceFromExchange': True,

# Remove source from exchange and add the source with the config option

grep source sarra/$CONFIG.conf
# sourceFromExchange True
source PROVINCIAL

sr3 show sarra/$CONFIG.conf | grep source
 'source': 'PROVINCIAL',
 'sourceFromExchange': False,
```

**Comment by andreleblanc11** [comment]
The config is running without interruptions. However with `feeder` set as the source, the directory being created from the sarra has `feeder` in the directory structure.

**Comment by andreleblanc11** [comment]
Might be a false alarm.. the `exchange` resolves to xpublic from `sr3 show`. In the config the exchange is `xs_PROVINCIAL...`.

Might be an exchange problem instead

**Comment by andreleblanc11** [comment]
All around confusion.

When the sarra runs, the config output from the logs shows the correct exchange. `sr3 show` does not.

At the same time, `source` is still needed in the config for it to work, so will keep this issue open.

**Comment by petersilva** [comment]
@andreleblanc11 look at this PR: https://github.com/MetPX/sarracenia/pull/877

See if the explanations there make sense. It's already merged.  It may be what is confusing you.

**Comment by andreleblanc11** [comment]
I looked at it and it does make sens. 

I tried adding the commit in the PR and it corrected my issue!
