### ISSUE TITLE
Support Multiple VIPs?

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#880]
I'm wondering if we should support multiple VIP options? The config would run on a particular node as long as it has one of the defined VIPs.

My use case is downloading data from a source that only allows 4 concurrent connections. If the sarra config runs on ops, it would be possible to exceed the 4 concurrent connections. I assume 4 of the 8 nodes would get errors and eventually retry, but there could be contention. Supporting multiple VIPs would prevent this by only allowing 4 nodes to download at a time. There might be a better way.

Another use case I thought of is config portability. You could have a 3 VIP settings in a config, one VIP each for dev, stage and ops, and then you can run the config on any cluster without needing to edit the VIP in the config. That might not be a good/tidy thing to do, but it's a possibility.

**Comment by petersilva** [comment]
sure, should be straight-forward.
*  change the type of the vip parameter from str to list (move 'vip' from str_options to list_options ) in sarracenia/config.py
* change the search logic in sarracenia/flow/__init__.py/has_vip() is the only needed change.

and that should be it.

**Comment by petersilva** [comment]
oh... wait, I was thinking has_vip would be true if you have any one of several (OR) you are talking about AND... hmm...

**Comment by reidsunderland** [comment]
I am talking about OR :)

**Comment by petersilva** [comment]
so each of the 8 nodes has their own vip, you put four of those vips in as the setting, and then even with OR, it should do the job.  I don't know why OR vs. AND, but it should work either way.
