### ISSUE TITLE
`sr3 --users declare` not declaring users on RMQ broker

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#902]
Encountered on development.

I'm not able to declare new users on the rabbitmq broker. Here's how to reproduce the problem

*** 

Under `~/.config/sr3/admin.conf`, add the user you want to add as a source -> `declare source $NEW_USER`

Then add credentials under `~/.config/sr3/credentials.conf` -> `amqp://$NEW_USER:$PASSWORD@$BROKER/`

Then run `sr3 --users declare`. 

The newly added user will not get declared as per the log output. It will skip declaring the user and then start failing at declaring the exchange (if specified under a configuration)

```
2024-01-22 19:32:33,491 24892 [ERROR] sarracenia.moth.amqp putSetup AMQP putSetup failed to connect or declare exchanges ['xs_$NEW_USER']@$NEW_USER on $BROKER: (0, 0): (403) ACCESS_REFUSED - Login was refused using authentication mechanism AMQPLAIN. For details see the broker logfile.
2024-01-22 19:32:33,491 24892 [INFO] sarracenia.moth.amqp putSetup Sleeping 2 seconds ...

```

**Comment by andreleblanc11** [comment]
Sidenote, there are also a couple of instances in the documentation: https://metpx.github.io/sarracenia/How2Guides/Admin.html that reference to `sr` instead of `sr3`

**Comment by petersilva** [comment]
there is no password in your credentials.conf entry.  cannot declare a user without a password... the credential.conf entry just won't be understood.

Please don't use \\$VAR ... it won't work in a config file... it would need to be \\${VAR} I don't know if you are just saying the value that would be replaced... or you are actually setting a value and expecting it to be replaced... which it won't if sr's config parser is involved.. if this is written in a bash script it should be fine.

what literally is the entry placed in credentials.conf and admin.conf, (you can change the PW text to ChangeMe!  but leave the rest literal.

**Comment by andreleblanc11** [comment]
Sorry, I should've been more clear.

Those variable juste represent a general use case. They aren't variables declared in the configuration.

I also did try with and without a password. That output I pasted in the original post from the logs is when there is a password set in the credentials.

**Comment by petersilva** [comment]
It looks like your admin credentials are wrong, hence the refusal.

**Comment by andreleblanc11** [comment]
I've tried again a couple more times and its been working
