### ISSUE TITLE
sr3 doesn't declare exchanges (maybe users/sources too?) from admin.conf if they're not used in a config

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#907]
config:

```
# created by: sr3 convert winnow/rs_testing
vip 1.2.3.4

logrotate 3
#loglevel debug
nodupe_ttl 900s
nodupe_basis name

broker amqps://SOME-SOURCE@ddsr-dev/
exchange xs_SOME-SOURCE_WINNOW

queueName q_${BROKER_USER}.${PROGRAM}.${CONFIG}.ddsr-dev


post_broker amqps://SOME-SOURCE@ddsr-dev/
post_exchange xs_SOME-SOURCE

instances 1
identity arbitrary
```

```
2024-01-25 21:33:26,088 [ERROR] sarracenia.moth.amqp getSetup AMQP getSetup failed to ddsr-dev with Queue.bind: (404) NOT_FOUND - no exchange 'xs_SOME-SOURCE_WINNOW' in vhost '/'
```

sr3d show does show that exchangeDeclare is True.

I'm not sure if it's supposed to declare the source exchange or not? Maybe it's only supposed to declare the post_exchange?

This might apply to other components that have a (source) exchange and post_exchange like a sarra. I haven't had time to test.

**UPDATE**: a good way to address this is to have sr3 honour exchange declarations in the admin.conf file.  This issue is now about that.

**Comment by petersilva** [comment]
the convention is that posters declare exchanges, subscribers declare queues.
So whoever is posting messages to the exchanges that a winnow is subscribing to would do that declaration.  To avoid a race condition. one can do:

sr3 declare

before starting up both components.

**Comment by reidsunderland** [comment]
Nothing is wrong then, I just didn't know how it was supposed to work. The poster is DMS so I will manually create the exchanges for the case I ran into.

**Comment by petersilva** [comment]
I think... for that case, you can put:

declare exchange NameYouWant

in admin.conf... and then sr3 declare might do the right thing (not sure...)

**Comment by petersilva** [comment]
I'm not sure if the above works... but it might be (subject to discussion) a good idea for an improvement if it doesn't.

**Comment by reidsunderland** [comment]
I tried adding them to admin.conf with `declare exchange xs_.....` and `sr3d --dry_run --debug declare` didn't declare them. I think that would be a nice feature to have, it would be nice to manage these in sarracenia configs and not have to use the RabbitMQ interface

**Comment by petersilva** [comment]
re-opening as a place holder for getting the declare of stuff in admin.conf to work even if it isn't included in any component/flow configuration.

**Comment by petersilva** [comment]
yeah... so the weirdness here is ... how do you delete these exchanges ?
You kind of have to use something else. (broker gui or cli.) ... because the "normal" thing is a cleanup on a config... how do you cleanup one of these admin declared things?
