### ISSUE TITLE
sr3 can't determine message format when content-type is not set

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#910]
We receive v02 format messages from non-Sarracenia sources, and they don't set the content-type in the message. This is incorrect, but we want to try to deal with it.

We expect [content-type to be `text/plain` for v02 messages](https://github.com/MetPX/sarracenia/blob/df51bdf85d6ab562aa2a857953870e301a598ed4/sarracenia/postformat/v02.py#L23), so messages with no content type don't get decoded when this code executes:

https://github.com/MetPX/sarracenia/blob/df51bdf85d6ab562aa2a857953870e301a598ed4/sarracenia/moth/amqp.py#L124-L132

In an email, @petersilva said:

> I can look for ‘{‘ not being in the first few characters as a definite positive heuristic of v02.
> Another thing might be to establish a “default” if none of the guesses work…
> We could debate some other heuristics.

**Comment by petersilva** [comment]
It would probably good to test the branch on DMS to see whether it works... I'm worried about bytes vs. utf-8.

**Comment by petersilva** [comment]
It might need to be b'{' rather than '{' ...
