### ISSUE TITLE
inlineEncoding option not documented, partially implemented.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#917]

**Comment by andreleblanc11** [comment]
Discovered while working on AM server.

Todo:
- Add documentation for `inlineEncoding` in https://metpx.github.io/sarracenia/Reference/sr3_options.7.html
- Adding examples would be good too

**Comment by petersilva** [comment]
I pushed straight to development by mistake... finger problem while creating a PR.  Have a look at: 0c3b3914abdeff1e2240d6675f342905efa4f29a and see if it makes sense.

**Comment by andreleblanc11** [comment]
Yeah that's good
