### ISSUE TITLE
*rename* action to rename a configuration file.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#92]
to complement list, add, remove... would be nice to have rename.

**Comment by mjip** [comment]
I assumed that there would only be two valid ways to call the rename: 
sr_watch rename original.conf new_and_improved.conf
and
sr_watch rename --debug original.conf new_and_improved.conf/
sr_watch --debug rename original.conf new_and_improved.conf
In all these cases, the original.conf gets put as the last entry in the args array, which is what it uses to rename the file.

**Comment by petersilva** [comment]
sounds fine.
