### ISSUE TITLE
Tutorial "Server Admin: A Local Subscriber" is for v2

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#934]
https://metpx.github.io/sarracenia/Tutorials/Setup_a_local_subscriber.html

https://github.com/MetPX/sarracenia/blob/development/docs/source/Tutorials/Setup_a_local_subscriber.rst

**Comment by petersilva** [comment]
Started looking for v2 ish terms in the documentation...  found lots of left-overs.
working on a branch:
* replaced all occurrences of ' sr_post ' by ' sr3_post '
* replaced all occurrences of ' sr ' by ' sr3 '

looking at occurrences of sr_subscribe, the occurrences are a lot more complicated:

```

edcm-dirt22-1% find source -type f | xargs grep -l ' sr_subscribe '
source/Tutorials/Setup_a_local_subscriber.rst
source/Tutorials/Setup_a_remote_subscriber.rst
source/Explanation/CommandLineGuide.rst
source/Explanation/FileCompletion.rst
source/Explanation/Concepts.rst
source/Explanation/SarraPluginDev.rst
source/Explanation/History/talks/SarraIntro/configs_A2B/configs4broadcast.txt
source/Explanation/Sundew_Migration/sundew_pull_migration.rst
source/fr/Tutoriel/Mettre_en_place_un_subscriber_local.rst
source/fr/Tutoriel/Mettre_en_place_un_subscriber_distant.rst
source/fr/Explication/GuideLigneDeCommande.rst
source/fr/Explication/Concepts.rst
source/fr/Explication/SarraPluginDev.rst
source/fr/Explication/ConsiderationsDeployments.rst
source/fr/Explication/AssurerLaLivraison.rst
source/fr/CommentFaire/Exemples_Hydro.rst
source/fr/CommentFaire/source.rst
source/fr/CommentFaire/Admin.rst
source/fr/CommentFaire/MiseANiveau.rst
source/fr/CommentFaire/Ingestion_de_email_avec_Sarracenia.rst
source/fr/CommentFaire/v2ASr3.rst
source/fr/Contribution/v03.rst
source/fr/Contribution/modèle_de_page_man.rst
source/fr/Contribution/deltas.rst
source/fr/Contribution/assemblage_on_part.rst
source/fr/Contribution/Développement.rst
source/fr/Reference/sr3_post.1.rst
source/fr/Reference/sr3_cpump.1.rst
source/Contribution/man_page_template.rst
source/Contribution/on_part_assembly.rst
source/Contribution/v03.rst
source/Contribution/deltas.rst
source/Contribution/Development.rst
source/How2Guides/Email_Ingesting_With_Sarracenia.rst
source/How2Guides/Hydro_Examples.rst
source/How2Guides/source.rst
source/How2Guides/Admin.rst
source/How2Guides/v2ToSr3.rst
source/How2Guides/UPGRADING.rst
source/How2Guides/subscriber.rst
source/Reference/sr3_post.1.rst
source/Reference/sr3_cpump.1.rst
edcm-dirt22-1%

```

Manual review required.   I think there is considerable redundancy/room for confusion in that, for example, the following
three documents cover the same ground, all differently... wondering if there is room for rationalization:

* https://metpx.github.io/sarracenia/Tutorials/1_CLI_introduction.html
* https://metpx.github.io/sarracenia/How2Guides/subscriber.html
* https://metpx.github.io/sarracenia/Tutorials/Setup_a_local_subscriber.html
* https://metpx.github.io/sarracenia/Tutorials/Setup_a_remote_subscriber.html

Hmm...

**Comment by petersilva** [comment]
replaced ' sr_watch ' by ' sr3_watch ' globally... but I'm not sure if that works...  have to review because I don't think I ever use sr3_watch... I always do sr3 xxxx watch/...   so don't remember if the v2 invocation method works.

**Comment by petersilva** [comment]
my changes are on issue934_2 branch, fwiw...

**Comment by petersilva** [comment]
after scanning (already in the patches): sr3_watch does not exist. one must use sr3 start watch ... like all the other normal components.
