### ISSUE TITLE
Amazon AWS S3 Transfer Class

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#939]
We've discussed this before, but I realized there isn't an issue for it so I'm creating it now. 

It would be nice to have a proper transfer class for the S3 protocol. 

There's already an S3 poll plugin, but I don't think it's 100% universal and compatible with any S3 bucket we come across. I wrote a sender plugin to send data to S3, but that isn't on GitHub yet.

https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/poll/s3bucket.py

**Comment by reidsunderland** [comment]
and I forgot to mention @tysonkaufmann's S3 work here: https://github.com/MetPX/sr3-examples/tree/main/cloud-publisher-s3

**Comment by reidsunderland** [comment]
Adding more detail for @gcglinton and other readers about various options we might need to support beyond what is immediately obvious in the `s3://bucket-name/path/to/file.txt` URI format.

We sometimes need to work with non-Amazon S3 endpoints. 

- The Copernicus Marine S3 poll plugin has to connect to cloudferro.com endpoints: https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/poll/copernicus_marine_s3.py
- It publishes HTTPS URLs to be downloaded which already include the endpoint. The built-in HTTP transfer class can download these URLs like normal.
- But the poll process uses boto3 and we have to specify the endpoint there.

For another client, I had to authenticate using an access key ID, secret access key _and_ AWS session token. 
- In the [S3 sender plugin](https://github.com/MetPX/sarracenia/blob/c96bf63ad4cdf4a22f9b7ba09bc1eba879afc7c0/sarracenia/flowcb/send/s3CloudSender.py), I used the access key ID as the username, secret access key as the password (in the S3:// URL in credentials.conf), then defined an option in the plugin for `AWS_sessionToken`.

---

Ideally, an S3 transfer class would handle at least these two cases (specific endpoint and a session token). 

I was thinking it might be possible to set those options in the credential, like:

```
s3://access_key_id:secret_access_key@bucket/ endpoint=something.example.com aws_session_token=jr4983hjr943hf 
```

- In the endpoint case, it might also be useful to publish the endpoint as a field in the message, like `{ 'baseUrl': "s3://access_key_id@bucket/", 'relPath': "path/to/file.txt", 's3_endpoint': "something.example.com" }`
- This would allow subscribers to consume and download the message without needing to have the endpoint in their credentials.conf

---

In my S3 sender plugin, I also allowed using "None" where the bucket name usually goes in `credentials.conf` and the `sendTo` URL. I'm not sure if that's a good approach, but I think there are cases where we won't know the bucket name in advance _or_ will want to be able to a) send into multiple different buckets (`sendTo`) or b) poll multiple different buckets (`pollUrl`) using one config. 

For example, a sender might look like this:

```
sendTo s3://access_key_id@None/

directory bucket-1/dataset_ABC
accept .*source_data/ABC/.*

directory bucket-2/dataset-DEF
accept .*source_data/DEF/*
```

If we *need* to specify a particular bucket in the `sendTo` URL, we'd have to use two different sender configs for this data feed:

```
# sender1.conf
sendTo s3://access_key_id@bucket-1/

directory dataset_ABC
accept .*source_data/ABC/.*
```

```
# sender2.conf
sendTo s3://access_key_id@bucket-2/

directory dataset_DEF
accept .*source_data/DEF/.*
```


Poll examples:

```
pollUrl s3://access_key_id@None/ endpoint=abc.example.com

# poll multiple buckets in one poll

path source-bucket-1/source/dataset_abc
accept .*
# messages posted would look like baseUrl: "s3://access_key_id@None/" relPath: "source-bucket-1/source/dataset_abc/file1.txt"

path source-bucket-2/source/dataset_def
accept .*
# messages posted would look like baseUrl: "s3://access_key_id@None/" relPath: "source-bucket-2/source/dataset_def/file2.txt"
```

vs. two different polls:

```
pollUrl s3://access_key_id@source-bucket-1/ endpoint=abc.example.com

path source/dataset_abc
accept .*

# messages posted would look like baseUrl: "s3://access_key_id@source-bucket-1/" relPath: "source/dataset_abc/file1.txt"
```

```
pollUrl s3://access_key_id@source-bucket-2/ endpoint=abc.example.com

path source/dataset_def
accept .*

# messages posted would look like baseUrl: "s3://access_key_id@source-bucket-2/" relPath: "source/dataset_def/file2.txt"
```

**Comment by petersilva** [comment]
not sure if this is helpful might just add confusion, but I think you want to know about *path*  ... *path* is the sr3 version of v2 *get*...

* The path option can be used to affect the URL being polled.

* The directory option only affects where something is downloaded to locally.

I don't know if this makes sense but:

```

pollUrl s3://blahblah-pathtobucket/

path path1_within_bucket
path path2_within_bucket

```

should run the "ls" entry point in the transfer class for each combination of pollUrl+path, and generate messages for each of the files found as a result of each listing.

The directory & accept stuff is all downstream of transfer classes. It's interpreting the messages produced by the transfer class.

**Comment by petersilva** [comment]
Thanks to @gcglinton this is done!
