### ISSUE TITLE
raise_signal requires Python >= 3.8

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#948]
We support Python >= 3.6. On the older versions, this causes an exception.

```
./moth/amqp.py:407:            signal.raise_signal(signal.SIGINT)
./moth/amqp.py:481:            signal.raise_signal(signal.SIGINT)
./moth/mqtt.py:420:            signal.raise_signal(signal.SIGINT)
./moth/mqtt.py:501:            signal.raise_signal(signal.SIGINT)
```

```
2024-02-23 14:46:56,771 [WARNING] sarracenia.moth.amqp getNewMessage lost connection to broker
2024-02-23 14:46:57,781 [WARNING] sarracenia.moth.amqp getNewMessage failed q_feeder_sarra.get-cmems-oceanobs.88019679.07467901: module 'signal' has no attribute 'raise_signal'
```

**Comment by reidsunderland** [comment]
i'm testing `os.kill(os.getpid(), signal.SIGINT)` as a replacement

**Comment by petersilva** [comment]
perhaps investigate the idiom required for python 3.6?
there might be another way to express the same function?
EDIT: I see that's exactly what you are doing... sorry...

**Comment by petersilva** [comment]
Do we know what the concrete effect of this is on running instances? do they crash? mis-behave somehow?  shutdown improperly meaning we could be losing some data?

**Comment by reidsunderland** [comment]
The logs are already gone, and I haven't been able to reproduce the issue. raise_signal is only used when a stop is requested with please_stop.

The instance does not crash - the exception is handled by something and the instance keeps running and processing data. The observed symptom is that the instance doesn't stop when it's supposed to.

`sr3 stop` would eventually kill the process if it doesn't stop cleanly after being told to, so data loss is possible.

**Comment by reidsunderland** [comment]
`os.kill` seems to work fine, so I think it's worth merging, but I haven't been able to reproduce the issue and fully test the fix.

To trigger the issue, the instance has to be in the middle of getSetup or putSetup when it's told to stop.

**Comment by reidsunderland** [comment]
By writing the above comment, I realized it would be super easy to reproduce by using a bad broker setting. The config gets stuck looping in putSetup, then just try to stop the instance. 

It does not stop until it gets killed. 

With the change to `os.kill`, it shuts down cleanly. The fix is good :)

**Comment by petersilva** [comment]
is os.kill available on windows? I think it is... just trying to check all the angles... wondering why we used raise_signal in the first place... also... is raise_signal better somehow? should we do a python version test and use raise_signal when we can, or just always use os.kill... need to read a bit ... to judge those things... opinions?

**Comment by reidsunderland** [comment]
This discussion indicates that `raise_signal` was added for better Windows support and I found this discussion that talks about problems with `os.kill` on Windows: https://discuss.python.org/t/terminateprocess-via-os-kill-on-windows/30882

but I tested and confirmed `os.kill(os.getpid(), signal.SIGINT)` does work on Windows so I don't think we have a case where `os.kill` wouldn't work on Windows.
