### ISSUE TITLE
Review example configs and documentation to make it more clear that `topicPrefix v02.post` is needed to subscribe to our public brokers

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#961]
(I created this without a description because I wanted to get the issue number for to email to the client).

I'm not sure if they created the config on their own or found an old example somewhere. But it didn't have `topicPrefix v02.post` so it didn't work. When I tested it, I had `topicPrefix v02.post` in my default.conf, so it worked for me.

Alternatively, we could set up shovels and start publishing v03 messages as well?

**Comment by petersilva** [comment]
yeah.... hard to figure out how to make that move obvious/clear...

fwiw... all the examples include it.  e.g:

```

sr3 list examples
sr3 add subscribe/dd_amis.conf

```

**Comment by reidsunderland** [comment]
The client provided links to the documents they were reading:

- https://metpx.github.io/sarracenia/How2Guides/subscriber.html
- https://metpx.github.io/sarracenia/Tutorials/Setup_a_remote_subscriber.html

I added topicPrefix v02.post where it was needed.
