### ISSUE TITLE
Redesign poll to work like scheduled flow? (Because polls do not consume from queues until after sleeping for a long time)

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#974]
When a poll is running in a cluster, each node subscribes to messages posted by the node with the VIP to populate their duplicate suppression caches.

The problem is that the poll works like this:

1. Gather (poll for new messages and consume from queue)
2. Post messages received from the poll routine
3. Sleep
4. Repeat

This means that messages posted by the poll routine are not consumed from the queue until after the sleep.

For example, here's the queue of a poll with `sleep 15m`:
![image](https://github.com/MetPX/sarracenia/assets/4219654/44bb4563-f172-4407-a65e-fe746cdd02fd)

This isn't ideal, especially on polls that have a long sleep time and post a lot of messages. A poll with `sleep 1h` that posts 10,000 messages each time it runs would leave 10,000 messages × *n* nodes on the broker for an hour at a time.

Other components (usually) don't sleep for very long, so they always consume from the queue.

--- 

@petersilva, @andreleblanc11 and I discussed this, and we're considering changing the poll to work like like a [scheduled flow](https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/scheduled/__init__.py). 

The difference between a scheduled flow:

- Poll *polls* a source server and produces a new/different list of files/messages each time. 
- Scheduled flow posts the same files each time. 

But the scheduling would be the same: the user could either set a `scheduled_interval` (would replace the current `sleep` interval *just for polling*) or define `scheduled_hour` and `scheduled_minute`.

With this, the poll component would use `sleep` like the other components and just sleep for a short amount of time, and the poll would be scheduled separately.  The [Message](https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/gather/message.py) gather routine would run more often than the poll (every sleep interval) and the . 

We also get the benefit of being able to schedule polls to run at specific hours and minutes, which isn't an option we currently have.

**Comment by petersilva** [comment]
note that it will still accumulate messages in between housekeeping intervals.  Basically with this change it will do a gather each housekeeping interval, rather than each polling interval.

**Comment by petersilva** [comment]
@reidsunderland  noticed, in testing one of the branches that the polling interval now defaults to -1...  this happens because:

* in flow/poll.py  defaults set sleep to -1.
* in config.py we take 'sleep' setting and apply that as 'scheduled_interval'
  (but only if it's >0) so it doesn't get set at all...
* so if nothing is set, it should default to never polling.

Is that what you saw?

I'm wondering what the default should be.

right now, if a "scheduled_interval" is set, it takes precedence over scheduled_hour, and scheduled_minute... so setting a default_interval will make it impossible to use the other two.

**Comment by reidsunderland** [comment]
Yes, that's what I saw. I guess setting a default is tricky, maybe we should just log an error message if none of the 3 `scheduled...` settings are set for a poll?

**Comment by petersilva** [comment]
OK found an easy way to implement default polling interval, chose 5 minutes. implemented in the branch in the latest PR.

**Comment by petersilva** [comment]
during testing, we ran into (corrected) problems:

* housekeeping wasn't running when poll in wVip state ( e7e306ea10cccc1913d053f4d6ec3a4a3eba6973 )
* the wVip poll was claiming to be running ( e6c2ec822654a483a1cdfc4b2f4de55dc2253a0a )
