### ISSUE TITLE
compatibility conversion of directory to path for polls is misleading

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#986]
in a v2 poll (and only a poll), when a *directory* argument was provided, it referred to a pattern to match on the remote. Similarly, *get*, and *accept* are applied on the server, as globbing patterns.   

This is different from all other components, where *directory* refers to where your are downloading to, the destination to write to, and the accept/reject would use regular expressions, rather than globbing.

To improve consistency, we convert:  

* v2: directory -> v3: path

* v2: get -> v3: path

* v2: accept ... does not really match v3 accept.

v3 accept is the same in all components.

When converting from v2 to sr3, it is important/useful to convert *directory* verbs to *path*.

However, once at sr3... one can set *download True* and there may be polls that download files, so getting "directory" back to it's meaning in the other components would be a good thing.

**Comment by petersilva** [comment]
options:

* just remove the conversion. (would have to wait until converting from v2 is no longer an issue.)
* have it only replace directory during "convert" and leave it alone otherwise.
  * print a warning message to the effect that *directory* has no effect if download is off.

other ideas?

**Comment by reidsunderland** [comment]
I like this option:

>  - have it only replace directory during "convert" and leave it alone otherwise.
>     - print a warning message to the effect that directory has no effect if download is off.

**Comment by petersilva** [comment]
There is also idiosyncratic renaming support in poll, inherited from v2.  It was needed in v2 poll did not have on_message (in sr3 after_accept) entry point available.  in sr3 can use after_accept and all the normal renam processing works.

so there is this:
```

filename rename=hoho/

```
logic unique to filename being present in a poll.  There is also something unique happenning with self.o.rename option.  but rename is processed later in other components, and should now work the same way without any specific code in poll.

So removing that stuff.

**Comment by petersilva** [comment]
oh... and we looked through the hundred or so extant configurations, and nobody uses the rename functionality.
